spring:
  datasource:
    primary:
      jdbc-url: ENC(/+TieeRKA7WewOn9xbmnxA6OvrGpUxxYA+0kv4kP3LolYID1xxE+z0epGq6/jeyxXe/SVbchJUT0NgOYhI7t8N02H4OYCwodnLzjOQcojbzAiFRa5lDSTI8cEqT5cI0GwbgHw9wZ0xcdEjQ/30NT+Xes9CG8bsMOsKIqvL5iy+pPEAKJaognoHDBDNyJ4W4dMFx3x2S4U9S5o9/1gruxXAjFq2nTbLG3zwgAq05YCfMbDasWT44hNzbwBLnFzITQWTzpqwEGESOTzL2AhbhDWo5gErs6HG4vKxDUlOtlIRo=)
      username: admin
      password: djkteCbsupY3RCDkPDPS
    secondary:
      jdbc-url: jdbc:mysql://livedata-instance-1.c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/general?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: admin
      password: dRmBstReqberz!14Xm#
  redis:
    host: ENC(yEgKHT+2QaZWfuP3aJIXHwUOqsEkqQRBLDBNMDGhH8J5qAflg9wbRPZU0SIW9nFgC0CN575+tdF1JLNSDfDy/8bp4m09zEseWflZ5KXIGZ6tnGV9S92y7yAYZJhet3eH)
    port: 6379

mybatis:
  configuration:
    variables:
      dbMain: 77je_main
      dbLive: 77je_live
      dbLottery: 77je_lottery

liveCenter: 7701

# 代付额度
payAgentLimit: 50000
# 顺为代付额度
payAgentLimitShunWei: 50000
# 宾利代付额度
payAgentLimitBinLi: 50000
# 特仑苏代付额度
payAgentLimitTels: 50000
# 联付宝代付额度
payAgentLimitLianFuBao: 50000
# 马云代付额度
payAgentLimitMaYun: 50000
# 合众代付额度
payAgentLimitHeZhong: 50000
# newMax代付额度
payAgentLimitNewMaxPay: 50000
# 鲁班代付额度
payAgentLimitLuBanPay: 50000
# 银联代付额度
payAgentLimitYinLianPay: 50000
# 弗良代付额度
payAgentLimitFuLiangPay: 50000
# GoPay代付额度
payAgentLimitGoPayPay: 50000
# 爱农代付额度
payAgentLimitAiNongPay: 50000
# VIPPAY代付额度
payAgentVipPay: 50000
# 酷币代付额度
payAgentKuBiPay: 50000
