spring:
  datasource:
    url: jdbc:mysql://xxxxxx:3306/7702_main?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xxxxxx
  redis:
    host: xxxxxxx
    port: 6379
    password: xxxxxx

mybatis:
  configuration-properties:
    db-main: 7702_main
    db-live: 7702_live
    db-lottery: 7702_lottery
