spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://moli-dandu.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7710_main?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: admin
      password: ENC(eNEs8Zeo1ZxWlxk7DA8+KKdlWOyq4udWhsa9oqw9RfzxSqbbd7qqNppi8ROSNDYziS5U2jlyX4KlF9gAOzJYCg==)
    secondary:
      jdbc-url: jdbc:mysql://livedata-instance-1.c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/general?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: admin
      password: dRmBstReqberz!14Xm#
  redis:
    host: serven10.zczoyz.ng.0001.ape1.cache.amazonaws.com
    port: 6379

mybatis:
  configuration:
    variables:
      dbMain: 7710_main
      dbLive: 7710_live
      dbLottery: 7710_lottery

liveCenter: 7701

# 代付额度
payAgentLimit: 30000
# 顺为代付额度
payAgentLimitShunWei: 50000
# 宾利代付额度
payAgentLimitBinLi: 50000
# 特仑苏代付额度
payAgentLimitTels: 50000
# 联付宝代付额度
payAgentLimitLianFuBao: 50000
# 马云代付额度
payAgentLimitMaYun: 50000
# 合众代付额度
payAgentLimitHeZhong: 50000
# 滴滴代付额度
payAgentLimitDiDi: 50000
# newMax代付额度
payAgentLimitNewMaxPay: 50000
# 阳光代付额度
payAgentLimitYangGuangPay: 50000
# 大风车代付额度
payAgentLimitDaFengChePay: 50000
# 魯班代付额度
payAgentLimitLuBanPay: 50000
# 鼎丰代付额度
payAgentLimitDingFengPay: 50000
# 宏博代付额度
payAgentLimitHongBoPay: 50000
# 小月代付额度
payAgentLimitXiaoYuePay: 50000
# 银联代付额度
payAgentLimitYinLianPay: 50000
# 爱农代付额度
payAgentLimitAiNongPay: 50000
# 众家代付额度
payAgentLimitZhongJiaPay: 50000
# 老乡代付额度
payAgentLimitLaoXiangPay: 50000
# 弗良代付额度
payAgentLimitFuLiangPay: 50000
# 东东汇潮代付额度
payAgentLimitHuiYuanPay: 50000
# 杉德代付额度
payAgentLimitShanDePay: 30000
# GoPay代付额度
payAgentLimitGoPayPay: 10000
# 酷币代付额度
payAgentKuBiPay: 20000
# VIPPAY代付额度
payAgentVipPay: 200000
# 波币代付额度
payAgentBoBiPay: 50000