spring:
  datasource:
    primary:
      jdbc-url: ENC(p2y9mgf4jLFGYWxgRNGzKQwnN31bI3BNWxi9m9F2vXq9HIj2GaUCq+xYnSb9cMrMj+pP4w36IXofrvsy5tyGF/8ONV3z0swJ1WCcMVuI9LJkgWcnL+3KTLeSKPw3xZ97Zd3kqNPz+Gkgo//ePluIycDHE5y7it1QwBkPZ6Vrr5nL2qx+xfCaTLyAk57SyD7FhWpfuicPHwh2V7WL+WDiEOCx8kxAV1OAzYGUrM+pPc19HXaX6goGmjUD47lLy5vUkazj7tEKk1tluYVMU8cGnw==)
      username: ENC(fQDn4kqFyUNo4CQUicK4TcATB+mfbxftG6lMucxqpt5rymxcnGwK8qUMkUgZIlSl)
      password: ENC(Z+lAsmL3cb2GQLkUtVuVkllVVngHXGCgyJiHib21sw/tRmwLIjm7fMXtkuKq5Y0XfdnGp92fg40kv1RIo9s7FA==)
    secondary:
      jdbc-url: ENC(4DxCzpibIaqtORggExqisSoKMAeyoQVwMQnYVSozasWnn0l8EIlhua+GjuQqCHGMGziDUS9vANt5kZd1kX+rE1CsHBLmX4nMznkADUhRFEhm/xU0gRbkSZnFQs8Giyqb3XeHs/J7iWL9JUw8N4qXFVvVlgkeIXh8Vkl9vqHloU1H2fPJuJKKFaBsAoujiCLFLpt3xv28zhjLDRf0PoQuhQ==)
      username: ENC(jDRgsd9cVTXiNMHjD5IlkNjOebg/PbW+u9SBMuv2utvAmrM3jM8zco+dGyiSj6jJ)
      password: ENC(mS1O1/dDbcXbHD55+vlRGTtCniz2O0cexBeX+s7PovpIxGA4Zsadbkk9odJMLeDM)
  redis:
    host: ENC(xwgkdrtnGh5Jlke5dcfcZNCsgRBfUlI8LaTWfE7XDcZPfCBI+OfqkUE7uU9cmjf3VPxNC+6gu6A3WKv7F32eCrbBtiZdeMjdW/TSg1Oig+I=)
    port: 6379
    password: ENC(FGT6eClTJ/WC0bXvVCUwDAqKTsfOc36b+0bB2DsiZN+A8JhTBtO3IINWuBDRdIfDpmbN9ggLb5WP3w5Fb/0uoA==)

mybatis:
  configuration:
    variables:
      dbMain: 7705_main
      dbLive: 7705_live
      dbLottery: 7705_lottery

liveCenter: 7701

# 代付额度
payAgentLimit: 50000
# 顺为代付额度
payAgentLimitShunWei: 50000
# 宾利代付额度
payAgentLimitBinLi: 50000
# 特仑苏代付额度
payAgentLimitTels: 50000
# 联付宝代付额度
payAgentLimitLianFuBao: 50000
# 马云代付额度
payAgentLimitMaYun: 50000
# 合众代付额度
payAgentLimitHeZhong: 50000
# 滴滴代付额度
payAgentLimitDiDi: 50000
# newMax代付额度
payAgentLimitNewMaxPay: 50000
# 阳光代付额度
payAgentLimitYangGuangPay: 50000
# 大风车代付额度
payAgentLimitDaFengChePay: 50000
# 魯班代付额度
payAgentLimitLuBanPay: 50000
# 宏博代付额度
payAgentLimitHongBoPay: 50000
# 小月代付额度
payAgentLimitXiaoYuePay: 50000
# 爱农代付额度
payAgentLimitAiNongPay: 50000
# 众家代付额度
payAgentLimitZhongJiaPay: 50000
# 老乡代付额度
payAgentLimitLaoXiangPay: 50000
# 弗良代付额度
payAgentLimitFuLiangPay: 50000
# 东东汇潮代付额度
payAgentLimitHuiYuanPay: 30000
# 银联代付额度
payAgentLimitYinLianPay: 50000
# GoPay代付额度
payAgentLimitGoPayPay: 50000
# 酷币代付额度
payAgentKuBiPay: 20000