spring:
  datasource:
    primary:
      jdbc-url: ENC(/wQ52rypKQIVZUY7G/pE9kgvzUhtjKWkDtrV/gZfaUQDz62i8HZjdue/07WZ7v4KLeWAtCL/lBBVP2MKRQo3uswg36Ew1ZOYY4WQX3l7Ux8pZzYHHU6C7seUMZEahwWse1sKJo5LYkTFx1FNriy3ySZKg0yHV9mYNLs/iq9dpmcNNqU6NMnTKhTVcxw1ZsvGotTTbHJRIBOsCluNF4pD7BwgA8n4DCwKWzT6mvPcOeJgocfkbKrtx1sCs93RHRAbsd3TKUeTWSbC0MaC71zf08/rj1VFQSNuyREmSCORchE=)
      #jdbc-url: jdbc:mysql://dataolda.cluster-custom-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7702_main?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: admin
      password: djkteCbsupY3RCDkPDPS
    secondary:
      jdbc-url: ENC(AxjxThZpL1kolf6Yx5MuBFGbP5sST9IeCMFijDG2zLlFRliUQPMeQt3f8zHbDRllaYPjoIEYVe0QsxTZULfTmJNRk2uRDDYq6U7X33dY6Dxznc33PumGdlo/IblJu+gEJG3UlIZIjkB+wYPSP9N0qioZYHoxuAdyINa84LSUvEk0WXxHRBe1g592bKRm7PbnluKYxsSG60auGF8b9DTPCw==)
      username: ENC(NweOTIFHXJmN2GDkY9kx/du0wCaiuyffLLi90mmZw57PsRMcnQF+ctPChmhGqYdK)
      password: ENC(ekQ2imJG92Uk9ch+IgceOeH3xA8cR3ouY8e1zL4VS6T0rngXO+YlCdk+0Mpo5cKH)
  redis:
    host: ENC(xDr0eC47VErY81aSCanu2Ud6OmhQpJ8/Ic8MkJdfarL1N+SQWtlAg46ir0i//He/AL3sk/nRRInIX3sTNfBtorOwqwD1TjiX7A2ngLtI11gi1vdeZEAAAxJ9tdz1SRLE)
    port: 6379

mybatis:
  configuration:
    variables:
      dbMain: 7702_main
      dbLive: 7702_live
      dbLottery: 7702_lottery

liveCenter: 7702

# 代付额度
payAgentLimit: 30000
# 宾利代付额度
payAgentLimitBinLi: 50000
# 特仑苏代付额度
payAgentLimitTels: 100000
# 联付宝代付额度
payAgentLimitLianFuBao: 30000
# 酷币代付额度
payAgentKuBiPay: 20000
# VIPPAY代付额度
payAgentVipPay: 200000