server:
  tomcat:
    max-connections: 30000
    threads:
      min-spare: 100
      max: 1000
  shutdown: graceful
  port: 42002
logging:
  level:
    root: info
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: 7700
  application:
    name: platform-admin
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        ## 最小空闲连接数量
        minimum-idle: 1
        ## 空闲连接存活最大时间，默认600000（10分钟）
        idle-timeout: 120000
        ## 连接池最大连接数，默认是10
        maximum-pool-size: 200
        ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
        auto-commit: true
        ## 连接池名称
        pool-name: HikariPool
        ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        max-lifetime: 30000
        ## 数据库连接超时时间,默认30秒，即30000
        connection-timeout: 60000
        connection-test-query: SELECT 1 FROM DUAL
        validation-timeout: 3000
        login-timeout: 5
    secondary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        ## 最小空闲连接数量
        minimum-idle: 5
        ## 空闲连接存活最大时间，默认600000（10分钟）
        idle-timeout: 120000
        ## 连接池最大连接数，默认是10
        maximum-pool-size: 50
        ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
        auto-commit: true
        ## 连接池名称
        pool-name: HikariPool-data
        ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        max-lifetime: 30000
        ## 数据库连接超时时间,默认30秒，即30000
        connection-timeout: 60000
        connection-test-query: SELECT 1 FROM DUAL
        validation-timeout: 3000
        login-timeout: 5

  redis:
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        ##连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10s
        ## 连接池中的最大空闲连接
        max-idle: 10
        ## 连接池中的最小空闲连接
        min-idle: 5
        ## 空闲链接检测线程检测周期
        time-between-eviction-runs: 30s
    ## 连接超时时间（毫秒）
    timeout: 100000
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: GMT+8
  task:
    scheduling:
      pool:
        size: 30
      thread-name-prefix: grap-task-
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  lifecycle:
    timeout-per-shutdown-phase: 5s

pagehelper:
  autoRuntimeDialect: true

management:
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
    beans:
      enabled: false
    info:
      enabled: false
    conditions:
      enabled: false
    shutdown:
      enabled: false
    configprops:
      enabled: false
    auditevents:
      enabled: false
    caches:
      enabled: false
    env:
      enabled: false
    metrics:
      enabled: false
    scheduledtasks:
      enabled: false
    mappings:
      enabled: false
    loggers:
      enabled: false
    integrationgraph:
      enabled: false
    heapdump:
      enabled: false
    threaddump:
      enabled: false

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmxopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 120
#excel下载条数限制
downLoadLimit: 200000

live:
  encrypt:
    privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALfb9hIuNY7qZg0yO9QtiREbL4GbQTIEIwwjaChUkYdnfPfciDPslCxsKF6snSWlgN8Lwpw9/3NpvkheXCfZsvJ5m4K7TuUfbBuYkZsn0oO34XYhG5RFiCaB0R6MKA9qdqbJJ6Nzr4KlgtMTG11URD/zzd3o4XgF0XiR/vz3gB37AgMBAAECgYAoi0T0NWRyI5ZlipJO88uqDgin2AjEcs0XvCcX3a5J4bRZJDSU3rK+KQut9PqidqC4jutXcQSH+uWPJ9/Cmesv1P1ovSNMUW9+rdbpeV6NgkuqTPI7VQgiOy/44FpsCBC8Sk+DlpG0zMtlgyifXg5ITZ7G/6rFO9MgXIkhfl4FIQJBAPLrE844ehahDcSLyR2wARIZcfvTYAVP+O+8lZhV5cvvdAK4z9Wc3aI5zfR+GJLojeWTSsA/78GmLLB33oIKKXcCQQDBwq7vJEeqIkZY2R96uSsgVw/3tnMu8LK4O27xWnszT3/0ETF2ualcjzJZz75dxv/bOrShRCEOGaZwoQQcDNCdAkEAqTlYb8XqT09c/vn+Xf8Zj9lIDY2AC9NdcO0oLZpRXpNuduL2bjI8N+Ia9uLNDbKR/0dvwKQJyxaPdVPcHy0jGwJASHhIdalcJIYtSY3r+DrJpo7pqfzTl/ru3XldRWhSLB7P/LlxhrZqYfQtIOpSiUCk8ZpDdQ3GTz/IwNd4cgVZAQJBANeSmrEzWHsHF5zzoirfXmTAX1sI8uOlcWCyNpbbQ1eaPgsKCtsgUm2qfoqnfIttdXPPA/lSawoVn389CRq1X8Q=
  share:
    7701: 7703,7704,7705,7706,7709,7711,77jp,77xy,77ml,77je,77yt
    7708: 7710
    77baby: 77baby

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
