spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://pc-j6c1ah19tg2g51r3u.rwlb.rds.aliyuncs.com:3306/7703_main?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: ENC(v1g9jT15U5Rj/Y+/o4zJNuXtRcEnyuTPHR1gnUvYUYzZltQRmjrpNVQYdch3E4K7A6JKvRNU1FFqmRQ7dEPHfw==)
      password: ENC(BcGcqamgY/2aUcGdrr7PoyPJPWgvHNChl4tQojazzxSlJ0bfbqbTpXIBa0rLMxiu1WfdmGMzT8EHvqX5OpNWHQ==)
    secondary:
      jdbc-url: ENC(rQSm78M8lGPyB7F8JHr6ZDTtVYv4diNGJwz8PfKv2nZs4c4uFKFrLYNhoRqihhG07ieXgibrX0zyiT5JolgpOEzB1s7ub5lMyeX1revCZ1A6EzHk+dBUoHFfb2KTprxE6dbhwTN5R+Lw17vahYP3AN7/PaGiacPEvM0aFkTY/CAEPzBWENSzqp/eXISprAEfuOZFEpKp1w3hCPzaKkSL2VlSBLSx2SvutDUbGmOhrJw=)
      username: ENC(NweOTIFHXJmN2GDkY9kx/du0wCaiuyffLLi90mmZw57PsRMcnQF+ctPChmhGqYdK)
      password: ENC(ekQ2imJG92Uk9ch+IgceOeH3xA8cR3ouY8e1zL4VS6T0rngXO+YlCdk+0Mpo5cKH)
  redis:
    host: ENC(PIJEsx2eG3ruXvv5gSKBcxstYOnlsJi9CzrAyOJgyfzWKk74XdqECKpBpmErrczUlTznGQqD1b6pbDrC6bgQGqPsFCcgMKB3Q/uzrgwLXGo=)
    port: 6379
    password: ENC(uPJFxgjBH4319Jv9gOHIhyHmu1gg21ACb2FeqtgF1TI2F7vf52pFzMeOmXBMdEfmbmsmPDpFFbHwSgf2ixVb9A==)

mybatis:
  configuration:
    variables:
      dbMain: 7703_main
      dbLive: 7703_live
      dbLottery: 7703_lottery

liveCenter: 7701

im:
  # 群聊
  sendGroupMsg: http://alb-c8bpqf3la2md9yeih2.cn-hongkong.alb.aliyuncs.com/chat/sendGroupMsg/
  # 单聊
  sendMsg: http://alb-c8bpqf3la2md9yeih2.cn-hongkong.alb.aliyuncs.com/chat/sendMsg/

# 代付额度
payAgentLimit: 30000
# 宾利代付额度
payAgentLimitBinLi: 50000
# 联付宝代付额度
payAgentLimitLianFuBao: 10000
# 顺为代付额度
payAgentLimitShunWei: 10000
# 众家代付额度
payAgentLimitZhongJiaPay: 50000
# 老乡代付额度
payAgentLimitLaoXiangPay: 50000
# GoPay代付额度
payAgentLimitGoPayPay: 100000
# 酷币代付额度
payAgentKuBiPay: 20000
