spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://pc-j6c1ah19tg2g51r3u.rwlb.rds.aliyuncs.com:3306/7703_main?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: 77tv_web
      password: 77tvweb_oradba
    secondary:
      jdbc-url: jdbc:mysql://pc-j6cj935598h4lz6r5.rwlb.rds.aliyuncs.com:3306/db_data?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: 77tv_web
      password: 77tvweb_oradba
  redis:
    host: r-j6cu2dxo1k4ry81lzr.redis.rds.aliyuncs.com
    port: 6379
    password: c#E80MCbasOd#f1j

mybatis:
  configuration:
    variables:
      dbMain: 7703_main
      dbLive: 7703_live
      dbLottery: 7703_lottery

# 代付额度
payAgentLimit: 30000
# 宾利代付额度
payAgentLimitBinLi: 50000
# 联付宝代付额度
payAgentLimitLianFuBao: 30000
# 代理号
agentCode: 7703