spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://qweqweta123dd.rwlb.rds.aliyuncs.com:3306/7705_main?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: tv77admin
      password: 8h6NDC2#OWSyyC%Lfhnjwiejew
    secondary:
      jdbc-url: ENC(4DxCzpibIaqtORggExqisSoKMAeyoQVwMQnYVSozasWnn0l8EIlhua+GjuQqCHGMGziDUS9vANt5kZd1kX+rE1CsHBLmX4nMznkADUhRFEhm/xU0gRbkSZnFQs8Giyqb3XeHs/J7iWL9JUw8N4qXFVvVlgkeIXh8Vkl9vqHloU1H2fPJuJKKFaBsAoujiCLFLpt3xv28zhjLDRf0PoQuhQ==)
      username: ENC(jDRgsd9cVTXiNMHjD5IlkNjOebg/PbW+u9SBMuv2utvAmrM3jM8zco+dGyiSj6jJ)
      password: ENC(mS1O1/dDbcXbHD55+vlRGTtCniz2O0cexBeX+s7PovpIxGA4Zsadbkk9odJMLeDM)
  redis:
    host: ENC(xwgkdrtnGh5Jlke5dcfcZNCsgRBfUlI8LaTWfE7XDcZPfCBI+OfqkUE7uU9cmjf3VPxNC+6gu6A3WKv7F32eCrbBtiZdeMjdW/TSg1Oig+I=)
    port: 6379
    password: ENC(FGT6eClTJ/WC0bXvVCUwDAqKTsfOc36b+0bB2DsiZN+A8JhTBtO3IINWuBDRdIfDpmbN9ggLb5WP3w5Fb/0uoA==)

mybatis:
  configuration:
    variables:
      dbMain: 7705_main
      dbLive: 7705_live
      dbLottery: 7705_lottery

liveCenter: 7704

# 代付额度
payAgentLimit: 50000
# 顺为代付额度
payAgentLimitShunWei: 50000
# 宾利代付额度
payAgentLimitBinLi: 50000
# 特仑苏代付额度
payAgentLimitTels: 50000
# 联付宝代付额度
payAgentLimitLianFuBao: 50000
# 马云代付额度
payAgentLimitMaYun: 50000
# 合众代付额度
payAgentLimitHeZhong: 50000
# 滴滴代付额度
payAgentLimitDiDi: 50000
# newMax代付额度
payAgentLimitNewMaxPay: 50000
# 阳光代付额度
payAgentLimitYangGuangPay: 50000
# 大风车代付额度
payAgentLimitDaFengChePay: 50000
# 魯班代付额度
payAgentLimitLuBanPay: 50000
# 宏博代付额度
payAgentLimitHongBoPay: 50000
# 小月代付额度
payAgentLimitXiaoYuePay: 50000
# 爱农代付额度
payAgentLimitAiNongPay: 50000
# 众家代付额度
payAgentLimitZhongJiaPay: 50000
# 老乡代付额度
payAgentLimitLaoXiangPay: 50000
# 弗良代付额度
payAgentLimitFuLiangPay: 50000
# 东东汇潮代付额度
payAgentLimitHuiYuanPay: 30000
# 银联代付额度
payAgentLimitYinLianPay: 50000
# GoPay代付额度
payAgentLimitGoPayPay: 50000
# 酷币代付额度
payAgentKuBiPay: 20000