spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://43.199.95.227:3306/7700_main?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: root
      password: f:e=h>EVUH,!N7zS&J`9
    secondary:
      jdbc-url: jdbc:mysql://moli-dandu.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/general?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: general
      password: 5P3Aq3P6n&VB$BNK
  redis:
    host: 43.199.95.227
    port: 6379
    password: EvYsN39ViArDumx4pWyH

mybatis:
  configuration:
    variables:
      dbMain: 7700_main
      dbLive: 7700_live
      dbLottery: 7700_lottery
    # spring boot集成mybatis的方式打印sql
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

liveCenter: 7700

im:
  # 群聊
  sendGroupMsg: http://54.178.74.47/chat/sendGroupMsg/
  # 单聊
  sendMsg: http://54.178.74.47/chat/sendMsg/
