spring:
  datasource:
    primary:
      jdbc-url: ENC(bf/+icANZeTFcb4s6DMhY/IFilAdrniiA/us9Xe93/eZKWBJ1TG7yOtGLnGn8kTlpUnxfk4PLDGjHUWxuHX7IIFheYf8nZB847YSpu8jyxFq2gs07jpkcbi+Er1UmLDM6xEzEN1sna3+30awQrkt5THxdWAxxsnQR6/ohsGqV+mpWWdhw+YaaUZb30gVUMUF8+VqSGXAxbeS3doCnAvAThfX+GiBggMu2C/Xb8idP0K3SpVD4slVvM1u+aKwIUH2iGpzDggoMifgM9+dmDKksA==)
      username: ENC(ntsELfEvY1lBOmFyTcgga5DF5OyuB9qA5FrxnMQdlwe14iRRN7BZPddMBZ9oDB+W)
      password: ENC(FNO20k6i7eNncA5GwwfAkYUhkNXMPlh/VGkMNBoADnG6lPbL6ebkqsR4xJdfM6kHM/0P8R1dZs2+LpMaUWj4Cw==)
    secondary:
      jdbc-url: ENC(WlfQDA9idMqhLlWQanW8T7NrSpYER5S/EV0eSdeeXlX2f9T31leOXX69piCBaun+JQvxj1uXvYGQB1RLkMA+gmzwg7DWa2+LYNjURswFWI28GimHK7Soe0yLpt7VBiG5RzDmT5bsEUTaxwvWQW2AKq7Rdkl8gzpJ7Cg7uUfwH0VxrmiiBHDj17h3qyzfEiPYm31OVDV8ExN9zgx0ADuOhw==)
      username: ENC(5mwKH5QTPd1k80o6dLDPTZrCnk/7CDG/vtm7TjBRTpDR0wXRKXmolfitvX9CMBCm)
      password: ENC(3CQQEKOPYc8qm0DS4EIO+8MWoa6rfLFHJAqdyNvYmVHyp4aSK3Uj/GSs7IzilfXt)
  redis:
    host: ENC(46Caz6CNamrg1U/LsvO4wnGo40U5mar3sgZiIrQr+lrl3N8P+riBp2ZaLOyqMQMflX5xuuY+tKnKxCymQx/bCl7WxPQCzj8xNKzYpNP+hgs=)
    port: 6379
    password: ENC(jTdX7av9+6T6OSj6Uzijxc4gKm3AgoyysmQsscXqVgUTxRXYT4hrQXN0YRcDrwzg6MUp0dagLUDGGnZ4k0OvLQ==)

mybatis:
  configuration:
    variables:
      dbMain: 77mm_main
      dbLive: 77mm_live
      dbLottery: 77mm_lottery

liveCenter: 77mm

# 代付额度
payAgentLimit: 30000
# 顺为代付额度
payAgentLimitShunWei: 50000
# 宾利代付额度
payAgentLimitBinLi: 50000
# 特仑苏代付额度
payAgentLimitTels: 50000
# 联付宝代付额度
payAgentLimitLianFuBao: 50000
# 马云代付额度
payAgentLimitMaYun: 50000
# 合众代付额度
payAgentLimitHeZhong: 50000
# 滴滴代付额度
payAgentLimitDiDi: 50000
# newMax代付额度
payAgentLimitNewMaxPay: 50000
# 阳光代付额度
payAgentLimitYangGuangPay: 50000
# 大风车代付额度
payAgentLimitDaFengChePay: 50000
# 魯班代付额度
payAgentLimitLuBanPay: 50000
# 鼎丰代付额度
payAgentLimitDingFengPay: 50000
# 宏博代付额度
payAgentLimitHongBoPay: 50000
# 小月代付额度
payAgentLimitXiaoYuePay: 50000
# 银联代付额度
payAgentLimitYinLianPay: 50000
# 爱农代付额度
payAgentLimitAiNongPay: 50000
# 众家代付额度
payAgentLimitZhongJiaPay: 50000
# 老乡代付额度
payAgentLimitLaoXiangPay: 50000
# 弗良代付额度
payAgentLimitFuLiangPay: 50000
# 东东汇潮代付额度
payAgentLimitHuiYuanPay: 50000
# 杉德代付额度
payAgentLimitShanDePay: 30000
# GoPay代付额度
payAgentLimitGoPayPay: 10000