spring:
  datasource:
    primary:
      jdbc-url: ENC(gFqkxW//h2dh7ubvkm7hV/iIbnNiD0Rk81rQXmuhxWZtOZ3x2Nqm3vC9GDSagJ7wLIBjLgBBmspjieB1TDW6kPqDck57KPFKUvdulm+zF5cRBpX9vLNKx+C5SU46ktsNTYFCoAxP8X6e1TPEVNV1gnNo9WWknMC/zEmd9f6/VOfsnOQaXmWAFJ3OGuYDjBVHECI+0RKjKU8AGWiwJuGIUW98ofDwAqHwUokZ9a7YBW1CYKQKDcKBlHo16r/YG3tAiIh1RKdV2mKaQHCM7Ny27g==)
      username: ENC(ntsELfEvY1lBOmFyTcgga5DF5OyuB9qA5FrxnMQdlwe14iRRN7BZPddMBZ9oDB+W)
      password: ENC(FNO20k6i7eNncA5GwwfAkYUhkNXMPlh/VGkMNBoADnG6lPbL6ebkqsR4xJdfM6kHM/0P8R1dZs2+LpMaUWj4Cw==)
    secondary:
      jdbc-url: ENC(WlfQDA9idMqhLlWQanW8T7NrSpYER5S/EV0eSdeeXlX2f9T31leOXX69piCBaun+JQvxj1uXvYGQB1RLkMA+gmzwg7DWa2+LYNjURswFWI28GimHK7Soe0yLpt7VBiG5RzDmT5bsEUTaxwvWQW2AKq7Rdkl8gzpJ7Cg7uUfwH0VxrmiiBHDj17h3qyzfEiPYm31OVDV8ExN9zgx0ADuOhw==)
      username: ENC(5mwKH5QTPd1k80o6dLDPTZrCnk/7CDG/vtm7TjBRTpDR0wXRKXmolfitvX9CMBCm)
      password: ENC(3CQQEKOPYc8qm0DS4EIO+8MWoa6rfLFHJAqdyNvYmVHyp4aSK3Uj/GSs7IzilfXt)
  redis:
    host: ENC(HaWmKXl+VsM5BO6Jomkknznhmx7qO2ZOix2jFD4CxjjcFv8Rc2dysz0V4Ko4mm2B1b/TjKqx4omzndQMCqZLIGEb9VxtfwI53qK8Q4LLQms=)
    port: 6379
    password: ENC(Hf9BLC78g054vvPbsQIYJ/h6OazPPdcP8MyOc49/obWDsyIviyDjlnnHyt1ipEYAniMR0PnMcLLfvGDKp4h5pw==)

mybatis:
  configuration:
    variables:
      dbMain: 77yutu_main
      dbLive: 77yutu_live
      dbLottery: 77yutu_lottery

liveCenter: 7701

# 代付额度
payAgentLimit: 50000
# 顺为代付额度
payAgentLimitShunWei: 50000
# 宾利代付额度
payAgentLimitBinLi: 50000
# 特仑苏代付额度
payAgentLimitTels: 50000
# 联付宝代付额度
payAgentLimitLianFuBao: 50000
# 马云代付额度
payAgentLimitMaYun: 50000
# 合众代付额度
payAgentLimitHeZhong: 50000
# newMax代付额度
payAgentLimitNewMaxPay: 50000
# 鲁班代付额度
payAgentLimitLuBanPay: 50000
# 银联代付额度
payAgentLimitYinLianPay: 50000
# 弗良代付额度
payAgentLimitFuLiangPay: 50000
# GoPay代付额度
payAgentLimitGoPayPay: 50000
# 爱农代付额度
payAgentLimitAiNongPay: 50000
# 酷币代付额度
payAgentKuBiPay: 20000
# VIPPAY代付额度
payAgentVipPay: 200000
