spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://rdsdb-7709.c6uwqqgyc6gv.ap-northeast-1.rds.amazonaws.com:3306/7709_main?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: 77tv_web
      password: 77tvweb_oradba
    secondary:
      jdbc-url: jdbc:mysql://datacenters.rwlb.rds.aliyuncs.com:3306/db_data?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: 77tv_web
      password: 77tvweb_oradba
  redis:
    host: redis-7709.kn1a4p.ng.0001.apne1.cache.amazonaws.com
    port: 6379

mybatis:
  configuration:
    variables:
      dbMain: 7709_main
      dbLive: 7709_live
      dbLottery: 7709_lottery

downLoadLimit: 100000

# 代付额度
payAgentLimit: 5000
# 顺为代付额度
payAgentLimitShunWei: 30000
# 宾利代付额度
payAgentLimitBinLi: 30000
# 特仑苏代付额度
payAgentLimitTels: 30000
# 联付宝代付额度
payAgentLimitLianFuBao: 30000
# 马云代付额度
payAgentLimitMaYun: 30000
# 合众代付额度
payAgentLimitHeZhong: 30000
# 滴滴代付额度
payAgentLimitDiDi: 30000
# newMax代付额度
payAgentLimitNewMaxPay: 30000
# 阳光代付额度
payAgentLimitYangGuangPay: 30000
# 大风车代付额度
payAgentLimitDaFengChePay: 30000
# 魯班代付额度
payAgentLimitLuBanPay: 30000
# 鼎丰代付额度
payAgentLimitDingFengPay: 30000
# 宏博代付额度
payAgentLimitHongBoPay: 30000
# 小月代付额度
payAgentLimitXiaoYuePay: 30000
# 银联代付额度
payAgentLimitYinLianPay: 30000
# 爱农代付额度
payAgentLimitAiNongPay: 30000
# 众家代付额度
payAgentLimitZhongJiaPay: 30000
# 老乡代付额度
payAgentLimitLaoXiangPay: 30000
# 弗良代付额度
payAgentLimitFuLiangPay: 30000
# 东东汇潮代付额度
payAgentLimitHuiYuanPay: 30000
# 杉德代付额度
payAgentLimitShanDePay: 30000
# 新汇代付额度
payAgentXinHuiPay: 100000
# GoPay代付额度
payAgentLimitGoPayPay: 100000