spring:
  datasource:
    primary:
      jdbc-url: ENC(bsf79LecUfJu19qReg9M+6iT3KNHEdOkuZc0hgMHFTntSG09FIPEBWcjP2oV+VDMtTlpGKZT8XBRcoelMJGwuV1dCKkBxZ+ardRZUvTf9tD1WppmTwTq4CCNNCCrCHhvS2ySkHIh1M1yfRucT1xMm6XzrLapEGbwonDWKhuqM9neXweXnXxVphBM/zgK47nfoeOt+IDkToM9ND6Rj+4K4oaTB/mB4sff4L8qpVirHAASUGvupVuk4MPJvY2K8SM0DENw0wg+Aj1IDET6IcOgd7Vg3uUC74mjX0ub1nBvwuA=)
      username: admin
      password: djkteCbsupY3RCDkPDPS
    secondary:
      jdbc-url: jdbc:mysql://moli-dandu.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/general?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: admin
      password: dRmBstReqberz!14Xm#
  redis:
    host: ENC(JMBOEMM5OezH2C9GYSdRzHqqJ3macyJK1fRLL0kx9chozwtunc8UKuo69pD6NiWC9uwAvTA2uyHkQrM7D4XcflrqTz8YhDyv5h7lhrzkbMFv363u0042qQTXzKRDL28k)
    port: 6379

mybatis:
  configuration:
    variables:
      dbMain: 77yutu_main
      dbLive: 77yutu_live
      dbLottery: 77yutu_lottery

liveCenter: 7701

# 代付额度
payAgentLimit: 50000
# 顺为代付额度
payAgentLimitShunWei: 50000
# 宾利代付额度
payAgentLimitBinLi: 50000
# 特仑苏代付额度
payAgentLimitTels: 50000
# 联付宝代付额度
payAgentLimitLianFuBao: 50000
# 马云代付额度
payAgentLimitMaYun: 50000
# 合众代付额度
payAgentLimitHeZhong: 50000
# newMax代付额度
payAgentLimitNewMaxPay: 50000
# 鲁班代付额度
payAgentLimitLuBanPay: 50000
# 银联代付额度
payAgentLimitYinLianPay: 50000
# 弗良代付额度
payAgentLimitFuLiangPay: 50000
# GoPay代付额度
payAgentLimitGoPayPay: 50000
# 爱农代付额度
payAgentLimitAiNongPay: 50000
# 酷币代付额度
payAgentKuBiPay: 20000
# VIPPAY代付额度
payAgentVipPay: 200000
# 百达付代付额度
payAgentBaiDaFuPay: 50000
