spring:
  datasource:
    primary:
      jdbc-url: ENC(+uGthM/AHtprERMz/O0sqhYk9vo/udqlAiWor3/5vLhKbFrOINMQHUQJfAfbfVsVbtQssqgeVKYALVMwwXTRZBsq3WnfD9ceeTJjt66Q2TxaQ7HAVgw6MKVlox/+Q33yNf9DtuZCT4/GnUYdpOS2dzmOZCHDYnGid2T9JiMxigPTtbl9OR0PCXENyw/nZAsTj95jlMKOqojLJcA+ZxMp11xkkFuUVr3uZXWJAQopC7aB164wdQHXbYbZUOEYc4zKFodeNm6Lj5ZPWIC2MBHkjg==)
      username: ENC(v1g9jT15U5Rj/Y+/o4zJNuXtRcEnyuTPHR1gnUvYUYzZltQRmjrpNVQYdch3E4K7A6JKvRNU1FFqmRQ7dEPHfw==)
      password: ENC(BcGcqamgY/2aUcGdrr7PoyPJPWgvHNChl4tQojazzxSlJ0bfbqbTpXIBa0rLMxiu1WfdmGMzT8EHvqX5OpNWHQ==)
    secondary:
      jdbc-url: ENC(1as8RRBZhLmSubn6wpDHJQ/fojlWS8zFTFUTQiHAXa6PgfiepDYa+2tA57KkxKDBmOvysFDgN8DIezUbE8qNzo1xgnPeAHKJcx+8EVZxBfqcQul4NNTdd++a1kb53pCfj3MxeC2HtjK0wRR5a8caTLFjNrTC5M1VsmPhs5W3n5mdfpVUAwu/asH12Cg7200f5U/88m8eYlsYPQ6o7siz7Q==)
      username: ENC(NweOTIFHXJmN2GDkY9kx/du0wCaiuyffLLi90mmZw57PsRMcnQF+ctPChmhGqYdK)
      password: ENC(ekQ2imJG92Uk9ch+IgceOeH3xA8cR3ouY8e1zL4VS6T0rngXO+YlCdk+0Mpo5cKH)
  redis:
    host: ENC(PIJEsx2eG3ruXvv5gSKBcxstYOnlsJi9CzrAyOJgyfzWKk74XdqECKpBpmErrczUlTznGQqD1b6pbDrC6bgQGqPsFCcgMKB3Q/uzrgwLXGo=)
    port: 6379
    password: ENC(uPJFxgjBH4319Jv9gOHIhyHmu1gg21ACb2FeqtgF1TI2F7vf52pFzMeOmXBMdEfmbmsmPDpFFbHwSgf2ixVb9A==)

mybatis:
  configuration:
    variables:
      dbMain: 7703_main
      dbLive: 7703_live
      dbLottery: 7703_lottery

# 代付额度
payAgentLimit: 30000
# 宾利代付额度
payAgentLimitBinLi: 50000
# 联付宝代付额度
payAgentLimitLianFuBao: 30000
# 众家代付额度
payAgentLimitZhongJiaPay: 50000
# 老乡代付额度
payAgentLimitLaoXiangPay: 50000
# GoPay代付额度
payAgentLimitGoPayPay: 50000