spring:
  datasource:
    url: jdbc:mysql://pc-j6c1ah19tg2g51r3u.rwlb.rds.aliyuncs.com:3306/db_cx001?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: 77tv_web
    password: 77tvweb_oradba
  redis:
    host: r-j6cjbpr49a0sffxuzv.redis.rds.aliyuncs.com
    port: 6379
    password: tv77_redis:^&*B2(vBvfi#h

mybatis:
  configuration:
    variables:
      dbMain: db_cx001
      dbLive: cx_live
      dbLottery: 7701_lottery
