spring:
  datasource:
    url: jdbc:mysql://47.254.238.161:3306/db_cx001?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 77lm@20210107
  redis:
    host: 47.254.238.161
    port: 6379
    password: 75a2-4e0e-9897-0347cc

payAgentNotifyUrl: http://47.254.238.161:41001/v1.0/payAgentCallBack/
domainTxtUploadUrl: http://47.254.238.161:41006/upload/oss?path=77ym
domainTxtUrl: https://77live.jiayiss.com/77ym/77.txt