spring:
  datasource:
    primary:
      jdbc-url: ENC(A5Xbwc86dTFN5X30o1T3gHsm5tgKpMAy4A9k+erYe7Q4Bd4VO4vHhRq4G2EgAfxw10fKRMkV+/TptR38pxU3q+WmjzisjX+nUIrw3GW9G1rqKaBOL+5u2K6brwxYEBrLE+L+n/JQOJh2gT9lMD9EAYcKBfWFGgphRorcz2ylQVmc8PZ0OK7FsQgJXNWj1KyZp+jHWpcoszldgIfQuDIoF+f5NownnPUiMpS46FCnM6VLS7ouFV3RLd6N8no3cavoshODJ9+5TwgonhizzrIeIGnCnjSwsb4/V0y3aGSpplk=)
      username: admin
      password: djkteCbsupY3RCDkPDPS
    secondary:
      jdbc-url: jdbc:mysql://livedata-instance-1.c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/general?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: admin
      password: dRmBstReqberz!14Xm#
  redis:
    host: ENC(K/0sM1w3WqkTds/3zB0WRUzXUsJDB/KXAV4+xMQ4ixAWuNQeD1KMw8dZwA+n5T7AFEiTxA5xlSHT5h+9pXFG1eU/bfxaOe4pWMms0u/AtzZWUHS15P6Pq9H12z9eQgb1)
    port: 6379

mybatis:
  configuration:
    variables:
      dbMain: 7705_main
      dbLive: 7705_live
      dbLottery: 7705_lottery

liveCenter: 7701

# 代付额度
payAgentLimit: 50000
# 顺为代付额度
payAgentLimitShunWei: 50000
# 宾利代付额度
payAgentLimitBinLi: 50000
# 特仑苏代付额度
payAgentLimitTels: 50000
# 联付宝代付额度
payAgentLimitLianFuBao: 50000
# 马云代付额度
payAgentLimitMaYun: 50000
# 合众代付额度
payAgentLimitHeZhong: 50000
# 滴滴代付额度
payAgentLimitDiDi: 50000
# newMax代付额度
payAgentLimitNewMaxPay: 50000
# 阳光代付额度
payAgentLimitYangGuangPay: 50000
# 大风车代付额度
payAgentLimitDaFengChePay: 50000
# 魯班代付额度
payAgentLimitLuBanPay: 50000
# 宏博代付额度
payAgentLimitHongBoPay: 50000
# 小月代付额度
payAgentLimitXiaoYuePay: 50000
# 爱农代付额度
payAgentLimitAiNongPay: 50000
# 众家代付额度
payAgentLimitZhongJiaPay: 50000
# 老乡代付额度
payAgentLimitLaoXiangPay: 50000
# 弗良代付额度
payAgentLimitFuLiangPay: 50000
# 东东汇潮代付额度
payAgentLimitHuiYuanPay: 30000
# 银联代付额度
payAgentLimitYinLianPay: 50000
# GoPay代付额度
payAgentLimitGoPayPay: 50000
# 酷币代付额度
payAgentKuBiPay: 20000
# VIPPAY代付额度
payAgentVipPay: 50000