spring:
  datasource:
    primary:
      jdbc-url: ENC(6rDd6DG59esK4w7l7gXnnsSr6ARLR6v3Mi+sG5Jq16QiuuO5M7ts0fjQBdDruqyzJaRNGjEqNgQS3TWW9HYA6S3iG/beLr4ObtUICwfmQhn7GlxyLYd9eSn/jul1kL36urnigNx4T2m7yYru6toDC1EPzto77PvVdiM+b63ETQ3sNuPGtyuHz/JrSEqmWqh6PkqpqdYFbvKiAdUBarIq6rombPveCxbmrVbxKRGcuXO0mVAUH17g2ePAZKBRK+oV+34XyE+thWsYYqyoms4pwQ==)
      username: ENC(v1g9jT15U5Rj/Y+/o4zJNuXtRcEnyuTPHR1gnUvYUYzZltQRmjrpNVQYdch3E4K7A6JKvRNU1FFqmRQ7dEPHfw==)
      password: ENC(BcGcqamgY/2aUcGdrr7PoyPJPWgvHNChl4tQojazzxSlJ0bfbqbTpXIBa0rLMxiu1WfdmGMzT8EHvqX5OpNWHQ==)
    secondary:
      jdbc-url: ENC(rQSm78M8lGPyB7F8JHr6ZDTtVYv4diNGJwz8PfKv2nZs4c4uFKFrLYNhoRqihhG07ieXgibrX0zyiT5JolgpOEzB1s7ub5lMyeX1revCZ1A6EzHk+dBUoHFfb2KTprxE6dbhwTN5R+Lw17vahYP3AN7/PaGiacPEvM0aFkTY/CAEPzBWENSzqp/eXISprAEfuOZFEpKp1w3hCPzaKkSL2VlSBLSx2SvutDUbGmOhrJw=)
      username: ENC(NweOTIFHXJmN2GDkY9kx/du0wCaiuyffLLi90mmZw57PsRMcnQF+ctPChmhGqYdK)
      password: ENC(ekQ2imJG92Uk9ch+IgceOeH3xA8cR3ouY8e1zL4VS6T0rngXO+YlCdk+0Mpo5cKH)
  redis:
    host: ENC(pDPNL4um6XboBUOrhx1oEUcXk1KAHuOPW6Opcu0mUD9Jx2EBASdvDmoTP49e9ssRLfoVJ3v/79QN2WFFqeAwb6Q57Xc4tmJTp+jZeDh57I8=)
    port: 6379
    password: ENC(SeWVUtEqVZ/hovYP7l9p+ZrQPyYq/zl6J5kqHSA9BBiVSh/fYwH23hyqklgQDkoBQGSca4w4MuOpzYBWj4z3XQ==)

mybatis:
  configuration:
    variables:
      dbMain: 7711_main
      dbLive: 7711_live
      dbLottery: 7711_lottery

liveCenter: 7701

im:
  # 群聊
  sendGroupMsg: http://47.243.143.163:43000/chat/sendGroupMsg/
  # 单聊
  sendMsg: http://47.243.143.163:43000/chat/sendMsg/

# 代付额度
payAgentLimit: 5000
# 顺为代付额度
payAgentLimitShunWei: 30000
# 宾利代付额度
payAgentLimitBinLi: 30000
# 特仑苏代付额度
payAgentLimitTels: 30000
# 联付宝代付额度
payAgentLimitLianFuBao: 30000
# 马云代付额度
payAgentLimitMaYun: 30000
# 合众代付额度
payAgentLimitHeZhong: 30000
# 滴滴代付额度
payAgentLimitDiDi: 30000
# newMax代付额度
payAgentLimitNewMaxPay: 30000
# 阳光代付额度
payAgentLimitYangGuangPay: 30000
# 大风车代付额度
payAgentLimitDaFengChePay: 30000
# 魯班代付额度
payAgentLimitLuBanPay: 30000
# 鼎丰代付额度
payAgentLimitDingFengPay: 30000
# 宏博代付额度
payAgentLimitHongBoPay: 30000
# 小月代付额度
payAgentLimitXiaoYuePay: 30000
# 银联代付额度
payAgentLimitYinLianPay: 30000
# 爱农代付额度
payAgentLimitAiNongPay: 30000
# 众家代付额度
payAgentLimitZhongJiaPay: 30000
# 老乡代付额度
payAgentLimitLaoXiangPay: 30000
# 弗良代付额度
payAgentLimitFuLiangPay: 30000
# 东东汇潮代付额度
payAgentLimitHuiYuanPay: 30000
# 杉德代付额度
payAgentLimitShanDePay: 30000
# GoPay代付额度
payAgentLimitGoPayPay: 100000
# OkPay代付额度
payAgentLimitOkPayPay: 100000
# 大牛代付额度
payAgentDaNiuPay: 50000
# 酷币代付额度
payAgentKuBiPay: 20000
# VIPPAY代付额度
payAgentVipPay: 200000