spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://pc-j6c1ah19tg2g51r3u.rwlb.rds.aliyuncs.com:3306/db_cx001?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: 77tv_web
      password: 77tvweb_oradba
    secondary:
      jdbc-url: jdbc:mysql://pc-j6cj935598h4lz6r5.rwlb.rds.aliyuncs.com:3306/db_data?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: 77tv_web
      password: 77tvweb_oradba
  redis:
    host: r-j6cjbpr49a0sffxuzv.redis.rds.aliyuncs.com
    port: 6379
    password: tv77_redis:^&*B2(vBvfi#h

mybatis:
  configuration:
    variables:
      dbMain: db_cx001
      dbLive: cx_live
      dbLottery: 7701_lottery

# 代付额度
payAgentLimit: 5000
# 顺为代付额度
payAgentLimitShunWei: 50000
# 宾利代付额度
payAgentLimitBinLi: 50000
# 特仑苏代付额度
payAgentLimitTels: 50000
# 联付宝代付额度
payAgentLimitLianFuBao: 2000
# 马云代付额度
payAgentLimitMaYun: 50000
# 合众代付额度
payAgentLimitHeZhong: 50000
# 滴滴代付额度
payAgentLimitDiDi: 50000
# 代理号
agentCode: 7701