spring:
  datasource:
    primary:
      jdbc-url: ENC(wQraWq5W97oSsGGN4wNOT86EjP9i+aoMgO9qwQb2OAMfejt4/w1R9mFbS/WOk7HmQ8IXsB2ChhOJKfxdV5Tp+NJKYbNdOcqEUgXixODgtITEAPOYE4er6+1OEVKUaIsM8hXgpMKh/skAYA0JByb/JHesiH1yPm56sXAEaj8fv8eAgE4AqARZWt33BrUjCqzKwpmWVudHk7l1RFGe57H2LWjaQLCop7UiYLdm1VyKC1UbdD0Zity6uoW0HbNfS/7ErwMkBr9MDXPjW4FE1xEzkr1+7pVpWZFWsP+oTnnOmAU=)
      #jdbc-url: jdbc:mysql://dataolda.cluster-custom-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7707_main?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: admin
      password: djkteCbsupY3RCDkPDPS
    secondary:
      jdbc-url: jdbc:mysql://livedata-instance-1.c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/general?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: admin
      password: dRmBstReqberz!14Xm#
  redis:
    host: ENC(PxKJ3cR8Jf2ybk/XxCodFtJSekDTzVKUfdBLyPHI4B3QvzVvqApEtqDyGJhf6PM0gZj4xNw//CMOfSFaQJjIcmZJPHuW0GL0twLQCXaLsTfsHA1RpAirs1j3KU0Xcy26)
    port: 6379

mybatis:
  configuration:
    variables:
      dbMain: 7707_main
      dbLive: 7707_live
      dbLottery: 7707_lottery

liveCenter: 7707

payAgentLimit: 30000
payAgentLimitBinLi: 50000
payAgentLimitLianFuBao: 30000
# 酷币代付额度
payAgentKuBiPay: 20000
# MY代付额度
payAgentMyPay: 50000
# 天奇代付额度
payAgentTianQiPay: 50000
# GoPay代付额度
payAgentLimitGoPayPay: 50000
# OkPay代付额度
payAgentLimitOkPayPay: 50000
# VIPPAY代付额度
payAgentVipPay: 50000
# 8k代付额度
payAgent8kPay: 50000
# 乐途代付额度
payAgentLeTuPay: 50000