spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://moli-dandu.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7708_main?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: admin
      password: ENC(eNEs8Zeo1ZxWlxk7DA8+KKdlWOyq4udWhsa9oqw9RfzxSqbbd7qqNppi8ROSNDYziS5U2jlyX4KlF9gAOzJYCg==)
    secondary:
      jdbc-url: jdbc:mysql://livedata-instance-1.c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/general?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: admin
      password: dRmBstReqberz!14Xm#
  redis:
    host: serven08.zczoyz.ng.0001.ape1.cache.amazonaws.com
    port: 6379

mybatis:
  configuration:
    variables:
      dbMain: 7708_main
      dbLive: 7708_live
      dbLottery: 7708_lottery

liveCenter: 7701

payAgentLimit: 30000
payAgentLimitBinLi: 50000
payAgentLimitLianFuBao: 30000
# 杉德代付额度
payAgentLimitShanDePay: 30000
# GoPay代付额度
payAgentLimitGoPayPay: 10000
# 酷币代付额度
payAgentKuBiPay: 20000
# VIPPAY代付额度
payAgentVipPay: 200000
# 波币代付额度
payAgentBoBiPay: 50000