spring:
  datasource:
    primary:
      jdbc-url: ENC(C/awxGgOX34XXezueNhPwSiMBXUaocgrFl671Whs4ZzFSgDM8Ki26FgTbDDP2p5ESFU+mzeM+m5aMKqexefOOzxkzL3ZOrGfoDtuK2LQOtNgpaDLpkrNxS2H8Us7Nnx/NPKi9TRUHzjugkfXXcOAv7lxgLSD8G+Weuv/1NSxO8YUDDKP1mkhGzhP9J5EKaBSEcVH3jBjRgoCc2SSmVossfi8bOBE4EgJZEfvxhy9sy8yzzsVlQEL7m2bQYHPyTpMEd7ot7FqvOVXZhc3Ty436A==)
      username: ENC(v1g9jT15U5Rj/Y+/o4zJNuXtRcEnyuTPHR1gnUvYUYzZltQRmjrpNVQYdch3E4K7A6JKvRNU1FFqmRQ7dEPHfw==)
      password: ENC(BcGcqamgY/2aUcGdrr7PoyPJPWgvHNChl4tQojazzxSlJ0bfbqbTpXIBa0rLMxiu1WfdmGMzT8EHvqX5OpNWHQ==)
    secondary:
      jdbc-url: ENC(rQSm78M8lGPyB7F8JHr6ZDTtVYv4diNGJwz8PfKv2nZs4c4uFKFrLYNhoRqihhG07ieXgibrX0zyiT5JolgpOEzB1s7ub5lMyeX1revCZ1A6EzHk+dBUoHFfb2KTprxE6dbhwTN5R+Lw17vahYP3AN7/PaGiacPEvM0aFkTY/CAEPzBWENSzqp/eXISprAEfuOZFEpKp1w3hCPzaKkSL2VlSBLSx2SvutDUbGmOhrJw=)
      username: ENC(NweOTIFHXJmN2GDkY9kx/du0wCaiuyffLLi90mmZw57PsRMcnQF+ctPChmhGqYdK)
      password: ENC(ekQ2imJG92Uk9ch+IgceOeH3xA8cR3ouY8e1zL4VS6T0rngXO+YlCdk+0Mpo5cKH)
  redis:
    host: ENC(c+0y0ym39D2QSG6smZE9juokVBKJMbSRUPPy+KtUQsvAWH9Cd1tbIj5xrqRqE+gI/MFqN0o2yGg1joSAkPikJxE53c2XImHaO+Cjfg+R8aQ=)
    port: 6379
    password: ENC(irn+YaOWBz5vZbqnF7mLacw5a+h/jfiOV6jWMZ1A2YRv3uf7Wjs1EbjKwuhr/gbv6myxx/ZyAk5IxFl+m7vhTA==)

mybatis:
  configuration:
    variables:
      dbMain: 7707_main
      dbLive: 7707_live
      dbLottery: 7707_lottery

payAgentLimit: 30000
payAgentLimitBinLi: 50000
payAgentLimitLianFuBao: 30000