spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://back01.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7702_main?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: admin
      password: djkteCbsupY3RCDkPDPS
    secondary:
      jdbc-url: jdbc:mysql://moli-dandu.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/general?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: admin
      password: dRmBstReqberz!14Xm#
  redis:
    host: ENC(xDr0eC47VErY81aSCanu2Ud6OmhQpJ8/Ic8MkJdfarL1N+SQWtlAg46ir0i//He/AL3sk/nRRInIX3sTNfBtorOwqwD1TjiX7A2ngLtI11gi1vdeZEAAAxJ9tdz1SRLE)
    port: 6379

mybatis:
  configuration:
    variables:
      dbMain: 7702_main
      dbLive: 7702_live
      dbLottery: 7702_lottery
    # spring boot集成mybatis的方式打印sql
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

liveCenter: 7701

# 代付额度
payAgentLimit: 30000
# 宾利代付额度
payAgentLimitBinLi: 50000
# 特仑苏代付额度
payAgentLimitTels: 100000
# 联付宝代付额度
payAgentLimitLianFuBao: 30000
# 酷币代付额度
payAgentKuBiPay: 20000
# VIPPAY代付额度
payAgentVipPay: 200000
# 8k代付额度
payAgent8kPay: 20000
# 波币代付额度
payAgentBoBiPay: 20000
