spring:
  datasource:
    primary:
      jdbc-url: ENC(0him8oHg5cszPDXdEsbnszqjn3xHkRaKj5mbKjoHnuU+KVVyRHdSLM4KroMCWcnqcPd6IVJpyZ668PNlK4cORFjClRZRmtPzmDsXRCETDuJ0alnZYNAKzG/0SpYoGSLvwl4VGK4wOxoFhrADC3J2/oHJzSAuhGo7Lw/PqHZevwY6tQQEgca4MjtF3hg9/UCq4/7/sclwm3/AUY+QvY1otMlDWZ7/B4QcP4lgEx/WPvdew9/H9q1/VM1tK8hMx+2fp8Xhtm1BPmrzJ16LqD/K4A==)
      username: ENC(v1g9jT15U5Rj/Y+/o4zJNuXtRcEnyuTPHR1gnUvYUYzZltQRmjrpNVQYdch3E4K7A6JKvRNU1FFqmRQ7dEPHfw==)
      password: ENC(BcGcqamgY/2aUcGdrr7PoyPJPWgvHNChl4tQojazzxSlJ0bfbqbTpXIBa0rLMxiu1WfdmGMzT8EHvqX5OpNWHQ==)
    secondary:
      jdbc-url: ENC(rQSm78M8lGPyB7F8JHr6ZDTtVYv4diNGJwz8PfKv2nZs4c4uFKFrLYNhoRqihhG07ieXgibrX0zyiT5JolgpOEzB1s7ub5lMyeX1revCZ1A6EzHk+dBUoHFfb2KTprxE6dbhwTN5R+Lw17vahYP3AN7/PaGiacPEvM0aFkTY/CAEPzBWENSzqp/eXISprAEfuOZFEpKp1w3hCPzaKkSL2VlSBLSx2SvutDUbGmOhrJw=)
      username: ENC(NweOTIFHXJmN2GDkY9kx/du0wCaiuyffLLi90mmZw57PsRMcnQF+ctPChmhGqYdK)
      password: ENC(ekQ2imJG92Uk9ch+IgceOeH3xA8cR3ouY8e1zL4VS6T0rngXO+YlCdk+0Mpo5cKH)
  redis:
    host: ENC(wPYT/GrMDrA3QluJGi1uVGaGa0yY2g931k4jLm8gQp/S7HwHHzdwkAorDvpVv74VfMZ2m5MfjPgFYllBxGb/oWp0arjd8hO9Al+99g9Zwr4=)
    port: 6379
    password: ENC(OqsTllTcYdJPYGStNmuT5RhqPBSYhR/BkIZYfk22oDWLbVbCR3WKxvtkTv46vyGVc0Ub3l6eeu9M61+Pd/5tTg==)

mybatis:
  configuration:
    variables:
      dbMain: 77jp_main
      dbLive: 77jp_live
      dbLottery: 77jp_lottery

liveCenter: 7701

im:
  # 群聊
  sendGroupMsg: http://alb-c8bpqf3la2md9yeih2.cn-hongkong.alb.aliyuncs.com/chat/sendGroupMsg/
  # 单聊
  sendMsg: http://alb-c8bpqf3la2md9yeih2.cn-hongkong.alb.aliyuncs.com/chat/sendMsg/

# 代付额度
payAgentLimit: 5000
# 顺为代付额度
payAgentLimitShunWei: 30000
# 宾利代付额度
payAgentLimitBinLi: 30000
# 特仑苏代付额度
payAgentLimitTels: 30000
# 联付宝代付额度
payAgentLimitLianFuBao: 30000
# 马云代付额度
payAgentLimitMaYun: 30000
# 合众代付额度
payAgentLimitHeZhong: 30000
# 滴滴代付额度
payAgentLimitDiDi: 30000
# newMax代付额度
payAgentLimitNewMaxPay: 30000
# 阳光代付额度
payAgentLimitYangGuangPay: 30000
# 大风车代付额度
payAgentLimitDaFengChePay: 30000
# 魯班代付额度
payAgentLimitLuBanPay: 30000
# 鼎丰代付额度
payAgentLimitDingFengPay: 30000
# 宏博代付额度
payAgentLimitHongBoPay: 30000
# 小月代付额度
payAgentLimitXiaoYuePay: 30000
# 银联代付额度
payAgentLimitYinLianPay: 30000
# 爱农代付额度
payAgentLimitAiNongPay: 30000
# 众家代付额度
payAgentLimitZhongJiaPay: 30000
# 老乡代付额度
payAgentLimitLaoXiangPay: 30000
# 弗良代付额度
payAgentLimitFuLiangPay: 30000
# 东东汇潮代付额度
payAgentLimitHuiYuanPay: 30000
# 杉德代付额度
payAgentLimitShanDePay: 30000
# GoPay代付额度
payAgentLimitGoPayPay: 100000
# 大牛代付额度
payAgentDaNiuPay: 50000
# 酷币代付额度
payAgentKuBiPay: 20000