package com.qiqilm.server.admin.enums;

import lombok.Getter;

import java.util.Arrays;
import java.util.List;

@Getter
public enum BankCodeTianXiaHuiType {
    //
    AHHYRCB( Arrays.asList( "安徽怀远农商行" ) ),
    AHRCU( Arrays.asList( "安徽农村信用社" ) ),
    AXABANK( Arrays.asList( "安徽新安银行" ) ),
    AQBANK( Arrays.asList( "安庆银行" ) ),
    ASBN( Arrays.asList( "安顺银行" ) ),
    ATCZB( Arrays.asList( "安图农商村镇银行" ) ),
    AYBANK( Arrays.asList( "安阳银行" ) ),
    ASBANK( Arrays.asList( "鞍山银行" ) ),
    BOAS( Arrays.asList( "鞍山银行有限公司" ) ),
    AMBANK( Arrays.asList( "澳门银行" ) ),
    GYBYDX( Arrays.asList( "白云德信村镇银行" ) ),
    BSB( Arrays.asList( "包商银行" ) ),
    ALSZQFDVTB( Arrays.asList( "宝丰豫丰村镇银行" ) ),
    BZSFVTB( Arrays.asList( "保德慧融村镇银行" ) ),
    BOB( Arrays.asList( "保定银行" ) ),
    BJRCB( Arrays.asList( "北京农村商业银行" ) ),
    BCCB( Arrays.asList( "北京商业银行" ) ),
    BJSYCZ( Arrays.asList( "北京顺义银座村镇银行" ) ),
    BJBANK( Arrays.asList( "北京银行" ) ),
    BJZG( Arrays.asList( "北京中关村银行股份有限公司" ) ),
    BOBZ( Arrays.asList( "本溪银行" ) ),
    CBHB( Arrays.asList( "渤海银行" ) ),
    BOCZ( Arrays.asList( "沧州银行" ) ),
    BYDXVTB( Arrays.asList( "昌乐乐安村镇银行" ) ),
    BFYFVTB( Arrays.asList( "昌黎家银村镇银行" ) ),
    CSRCB( Arrays.asList( "常熟农商银行" ) ),
    CZBA( Arrays.asList( "常州银行" ) ),
    BDHRVTB( Arrays.asList( "朝阳柳城村镇银行" ) ),
    CYCB( Arrays.asList( "朝阳银行" ) ),
    GRCBANK( Arrays.asList( "潮州农商银行" ) ),
    CDRCB( Arrays.asList( "成都农商银行" ) ),
    BOCD( Arrays.asList( "成都商业银行" ) ),
    CDCB( Arrays.asList( "成都银行" ) ),
    CDBANK( Arrays.asList( "承德银行" ) ),
    CLLAVTB( Arrays.asList( "赤城家银村镇银行" ) ),
    CXBANK( Arrays.asList( "创兴银行" ) ),
    BODZ( Arrays.asList( "达州银行" ) ),
    CYLCVTB( Arrays.asList( "大城舜丰村镇银行" ) ),
    DFBANK( Arrays.asList( "大丰银行" ) ),
    UOB( Arrays.asList( "大华银行有限公司" ) ),
    CZSYVTB( Arrays.asList( "大连开发区鑫汇村镇银行" ) ),
    DLRCB( Arrays.asList( "大连农商银行" ) ),
    DLB( Arrays.asList( "大连银行" ) ),
    DCSFVTB( Arrays.asList( "大同市南郊区东都村镇银行有限责任公司" ) ),
    DTB( Arrays.asList( "大同银行股份有限公司" ) ),
    DLKFQXHVTB( Arrays.asList( "大洼恒丰村镇银行股份有限公司" ) ),
    DTNJDDVTB( Arrays.asList( "代县泓都村镇银行有限责任公司" ) ),
    BODD( Arrays.asList( "丹东银行" ) ),
    DWHFVTB( Arrays.asList( "德惠敦银村镇银行" ) ),
    CNAPS( Arrays.asList( "德阳商业银行" ) ),
    DB( Arrays.asList( "德意志银行" ) ),
    DZBCHINA( Arrays.asList( "德州银行" ) ),
    DXHDVTB( Arrays.asList( "东方惠丰村镇银行" ) ),
    DRCBANK( Arrays.asList( "东莞农村商业银行" ) ),
    DGNB( Arrays.asList( "东莞商行" ) ),
    BOD( Arrays.asList( "东莞银行" ) ),
    DPHY( Arrays.asList( "东平沪农商村镇银行" ) ),
    DHDYVTB( Arrays.asList( "东山润鑫村镇银行" ) ),
    HKBEA( Arrays.asList( "东亚银行" ) ),
    ZJDYB( Arrays.asList( "东阳农商银行" ) ),
    DYLSBANK( Arrays.asList( "东营莱商村镇银行" ) ),
    DYCCB( Arrays.asList( "东营银行" ) ),
    ORDOSB( Arrays.asList( "鄂尔多斯银行" ) ),
    DSCZB( Arrays.asList( "范县德商村镇银行" ) ),
    FJHXBC( Arrays.asList( "福建海峡银行" ) ),
    FJNX( Arrays.asList( "福建农村信用社" ) ),
    FJNXS( Arrays.asList( "福建省农村信用社联合社" ) ),
    FJSSNX( Arrays.asList( "福建石狮农商银行" ) ),
    FQFMBANK( Arrays.asList( "福泉富民村镇银行" ) ),
    FZRCB( Arrays.asList( "福州农商银行" ) ),
    FSCB( Arrays.asList( "抚顺银行" ) ),
    BOFX( Arrays.asList( "阜新市银行" ) ),
    FUBON( Arrays.asList( "富邦华一银行" ) ),
    FDB( Arrays.asList( "富滇银行" ) ),
    GSRCU( Arrays.asList( "甘肃农村信用社" ) ),
    GSBANK( Arrays.asList( "甘肃银行" ) ),
    GZB( Arrays.asList( "赣州银行有限公司" ) ),
    ICBC( Arrays.asList( "工商银行" ) ),
    CEB( Arrays.asList( "光大银行" ) ),
    CGB( Arrays.asList( "广东发展银行" ) ),
    GDHX( Arrays.asList( "广东华兴银行有限公司" ) ),
    GDNY( Arrays.asList( "广东南粤银行" ) ),
    GZRCB( Arrays.asList( "广东农商银行" ) ),
    GDPHCB( Arrays.asList( "广东普宁汇成村镇银行" ) ),
    GDRCC( Arrays.asList( "广东省农村信用社" ) ),
    BGB( Arrays.asList( "广西北部湾银行" ) ),
    GXRCU( Arrays.asList( "广西农信银行" ) ),
    BYMTRB( Arrays.asList( "广州白云民泰村镇银行" ) ),
    GZHDCZCZBK( Arrays.asList( "广州花都稠州村镇银行" ) ),
    GRCB( Arrays.asList( "广州农商银行" ) ),
    JPTX( Arrays.asList( "广州农信社" ) ),
    GCB( Arrays.asList( "广州银行" ) ),
    ZCCJB( Arrays.asList( "广州增城长江村镇银行" ) ),
    GYNSH( Arrays.asList( "贵阳农商银行" ) ),
    GYCB( Arrays.asList( "贵阳银行" ) ),
    GZNX( Arrays.asList( "贵州省农村信用社" ) ),
    ZYCBANK( Arrays.asList( "贵州银行" ) ),
    GLGM( Arrays.asList( "桂林国民银行" ) ),
    GLB( Arrays.asList( "桂林银行" ) ),
    HRBANK( Arrays.asList( "哈尔滨银行" ) ),
    HMBANK( Arrays.asList( "哈密银行" ) ),
    HFRCB( Arrays.asList( "海丰农商银行" ) ),
    UNITEDB( Arrays.asList( "海口联合农商银行" ) ),
    BOHN( Arrays.asList( "海南省农村信用社" ) ),
    HNTCYH( Arrays.asList( "海南屯昌长江村镇银行" ) ),
    HNBANK( Arrays.asList( "海南银行" ) ),
    FJHXBANK( Arrays.asList( "海峡银行" ) ),
    HDCB( Arrays.asList( "邯郸市商业银行" ) ),
    HDBANK( Arrays.asList( "邯郸银行" ) ),
    HKB( Arrays.asList( "汉口银行" ) ),
    HZCB( Arrays.asList( "杭州银行" ) ),
    HBNCSYYH( Arrays.asList( "河北农村商业银行" ) ),
    HBRCB( Arrays.asList( "河北农村信用联合社" ) ),
    BHB( Arrays.asList( "河北银行" ) ),
    HNNX( Arrays.asList( "河南农商银行" ) ),
    HNRCU( Arrays.asList( "河南省农村信用社" ) ),
    HBBAN( Arrays.asList( "鹤壁银行" ) ),
    HLJRCU( Arrays.asList( "黑龙江农信" ) ),
    EGBANK( Arrays.asList( "恒丰银行" ) ),
    HSBK( Arrays.asList( "恒生银行" ) ),
    HSB( Arrays.asList( "衡水银行" ) ),
    HLDBANK( Arrays.asList( "葫芦岛银行" ) ),
    HBRCC( Arrays.asList( "湖北农村信用社有限公司" ) ),
    HBC( Arrays.asList( "湖北银行" ) ),
    HNGYRCB( Arrays.asList( "湖南桂阳农村商业银行" ) ),
    HNNC( Arrays.asList( "湖南农村信用社" ) ),
    CSXBANK( Arrays.asList( "湖南三湘银行" ) ),
    HUNB( Arrays.asList( "湖南银行" ) ),
    hzccb( Arrays.asList( "湖州银行" ) ),
    CITIBANK( Arrays.asList( "花旗银行" ) ),
    HUARUIBANK( Arrays.asList( "华瑞银行" ) ),
    HXB( Arrays.asList( "华夏银行" ) ),
    HDHMB( Arrays.asList( "桦甸惠民村镇银行" ) ),
    HARCB( Arrays.asList( "淮安农商银行" ) ),
    HABANK( Arrays.asList( "淮安银行" ) ),
    HBBANK( Arrays.asList( "淮北银行" ) ),
    HHNX( Arrays.asList( "黄河农信银行" ) ),
    HMRCB( Arrays.asList( "黄梅农村商业银行" ) ),
    HSBANK( Arrays.asList( "徽商银行" ) ),
    HSBC( Arrays.asList( "汇丰银行" ) ),
    HSHSB( Arrays.asList( "惠水恒升村镇银行" ) ),
    JLRCU( Arrays.asList( "吉林省农村信用社" ) ),
    JLZBCB( Arrays.asList( "吉林洮北惠民村镇银行" ) ),
    JLBANK( Arrays.asList( "吉林银行" ) ),
    JYBANK( Arrays.asList( "集友银行" ) ),
    JNHY( Arrays.asList( "济南槐荫沪农商村镇银行" ) ),
    ZNBANK( Arrays.asList( "济南银行" ) ),
    JNCZB( Arrays.asList( "济宁儒商村镇银行" ) ),
    BOJN( Arrays.asList( "济宁银行" ) ),
    JXCCB( Arrays.asList( "嘉兴银行" ) ),
    CCB( Arrays.asList( "建设银行" ) ),
    JMRCB( Arrays.asList( "江门农商银行" ) ),
    JRCCB( Arrays.asList( "江南村镇银行" ) ),
    JNRCB( Arrays.asList( "江南农村商业银行" ) ),
    JSCSNSB( Arrays.asList( "江苏常熟农村商业银行" ) ),
    JRCB( Arrays.asList( "江苏农商银行" ) ),
    JSSYRCB( Arrays.asList( "江苏射阳农村商业银行" ) ),
    JSRCU( Arrays.asList( "江苏省农村信用社联合社" ) ),
    JSBC( Arrays.asList( "江苏银行" ) ),
    JSCJBANK( Arrays.asList( "江苏长江商业银行" ) ),
    GZYZCZBK( Arrays.asList( "江西赣州银座村镇银行" ) ),
    JXNXS( Arrays.asList( "江西农商银行" ) ),
    JXRCU( Arrays.asList( "江西省农村信用社" ) ),
    NCB( Arrays.asList( "江西银行" ) ),
    JYRCB( Arrays.asList( "江阴农商银行" ) ),
    BCM( Arrays.asList( "交通银行" ) ),
    JZB( Arrays.asList( "焦作银行" ) ),
    JHBANK( Arrays.asList( "金华银行" ) ),
    JXSHDVTB( Arrays.asList( "金寨徽银村镇银行有限公司" ) ),
    BOJZ( Arrays.asList( "锦州银行有限公司" ) ),
    JINCHB( Arrays.asList( "晋城银行" ) ),
    JSHB( Arrays.asList( "晋商银行" ) ),
    JZBA( Arrays.asList( "晋中银行" ) ),
    JYCZBANK( Arrays.asList( "缙云联合村镇银行" ) ),
    JDZBANK( Arrays.asList( "景德镇银行" ) ),
    JJCCB( Arrays.asList( "九江银行" ) ),
    JYCBANK( Arrays.asList( "九银村镇银行" ) ),
    KLM( Arrays.asList( "开鲁蒙银行" ) ),
    KJCZBK( Arrays.asList( "客家村镇银行" ) ),
    KBSVTB( Arrays.asList( "垦利乐安村镇银行股份有限公司" ) ),
    KELBANK( Arrays.asList( "库尔勒银行" ) ),
    KLB( Arrays.asList( "昆仑银行" ) ),
    KMNLSBANK( Arrays.asList( "昆明市农村信用合作社联合社" ) ),
    KSRB( Arrays.asList( "昆山农商银行" ) ),
    KRCB( Arrays.asList( "昆山农信社" ) ),
    LSBANK( Arrays.asList( "莱商银行" ) ),
    LZYH( Arrays.asList( "兰州银行" ) ),
    LANGFB( Arrays.asList( "廊坊银行" ) ),
    LSCCB( Arrays.asList( "乐山商业银行" ) ),
    LJHXCZYH( Arrays.asList( "连江恒欣村镇银行" ) ),
    LSZBANLK( Arrays.asList( "凉山州银行" ) ),
    LSRCB( Arrays.asList( "梁山农商银行" ) ),
    DSQLFB( Arrays.asList( "辽宁大石桥隆丰村镇银行" ) ),
    LNRCC( Arrays.asList( "辽宁农村信用社" ) ),
    LSBK( Arrays.asList( "辽沈银行" ) ),
    LYCB( Arrays.asList( "辽阳银行" ) ),
    LSBC( Arrays.asList( "临商银行" ) ),
    LXBANK( Arrays.asList( "临沂银行" ) ),
    LZCCB( Arrays.asList( "柳州银行" ) ),
    LPSNB( Arrays.asList( "六盘水商行" ) ),
    LJBANK( Arrays.asList( "龙江银行" ) ),
    LZBANK( Arrays.asList( "泸州银行" ) ),
    XFCZB( Arrays.asList( "罗平兴福村镇银行" ) ),
    LYBANK( Arrays.asList( "洛阳银行" ) ),
    LHNB( Arrays.asList( "漯河商行" ) ),
    MASBANK( Arrays.asList( "马鞍山银行" ) ),
    MZKSBK( Arrays.asList( "梅州客商银行" ) ),
    MGGLMBANK( Arrays.asList( "蒙古郭勒姆特银行" ) ),
    PERB( Arrays.asList( "蒙商银行" ) ),
    MSRCB( Arrays.asList( "密山农商银行" ) ),
    MYCC( Arrays.asList( "绵阳商业银行" ) ),
    CMBC( Arrays.asList( "民生银行" ) ),
    CGNB( Arrays.asList( "南充市商业银行" ) ),
    NRCB( Arrays.asList( "南海农商银行" ) ),
    NRCBANK( Arrays.asList( "南海农信" ) ),
    NJCB( Arrays.asList( "南京银行" ) ),
    NTBANK( Arrays.asList( "南通银行" ) ),
    NYCBANK( Arrays.asList( "南阳村镇银行" ) ),
    NCBK( Arrays.asList( "南洋商业银行" ) ),
    NMGNXS( Arrays.asList( "内蒙古农村信用社" ) ),
    BOIMC( Arrays.asList( "内蒙古银行" ) ),
    NBDHBANK( Arrays.asList( "宁波东海银行" ) ),
    NCBANK( Arrays.asList( "宁波通商银行" ) ),
    NBBANK( Arrays.asList( "宁波银行" ) ),
    NBNCYH( Arrays.asList( "宁波鄞州农村合作银行" ) ),
    NXRCU( Arrays.asList( "宁夏黄河农村商业银行" ) ),
    NXBANK( Arrays.asList( "宁夏银行" ) ),
    ADBC( Arrays.asList( "农业发展银行" ) ),
    ABC( Arrays.asList( "农业银行" ) ),
    PZHBANK( Arrays.asList( "攀枝花银行" ) ),
    PJSCB( Arrays.asList( "盘锦银行" ) ),
    PAB( Arrays.asList( "平安银行" ) ),
    PDSB( Arrays.asList( "平顶山银行" ) ),
    PLBANK( Arrays.asList( "平凉银行" ) ),
    PTRCB( Arrays.asList( "莆田农商银行" ) ),
    PYBANK( Arrays.asList( "濮阳银行" ) ),
    QLBANK( Arrays.asList( "齐鲁银行" ) ),
    QSB( Arrays.asList( "齐商银行" ) ),
    QSBANK( Arrays.asList( "齐商银行有限公司" ) ),
    QXHDB( Arrays.asList( "黔西花都村镇银行" ) ),
    QHDBANK( Arrays.asList( "秦皇岛银行" ) ),
    QRCB( Arrays.asList( "青岛农商银行" ) ),
    QDCCB( Arrays.asList( "青岛银行" ) ),
    QHRC( Arrays.asList( "青海农村信用社" ) ),
    QHBK( Arrays.asList( "青海银行" ) ),
    QTRCB( Arrays.asList( "青田农商银行" ) ),
    QJCCB( Arrays.asList( "曲靖市商业银行" ) ),
    QZNSX( Arrays.asList( "泉州农村商业银行" ) ),
    QZCCB( Arrays.asList( "泉州银行" ) ),
    SRCBCZ( Arrays.asList( "日照沪农商村镇银行" ) ),
    RZB( Arrays.asList( "日照银行" ) ),
    RXVB( Arrays.asList( "融兴村镇银行" ) ),
    BORF( Arrays.asList( "瑞丰银行" ) ),
    SMXBANK( Arrays.asList( "三门峡银行" ) ),
    XMIB( Arrays.asList( "厦门国际银行" ) ),
    JXLHCZYH( Arrays.asList( "山东金乡蓝海村镇银行" ) ),
    SDNCB( Arrays.asList( "山东农商银行" ) ),
    SDRCU( Arrays.asList( "山东省农村信用社联合社" ) ),
    SXRCU( Arrays.asList( "山西省农村信用社" ) ),
    SXXYRCU( Arrays.asList( "山西孝义农村商业银行" ) ),
    SHXIBANK( Arrays.asList( "山西银行" ) ),
    SXNXS( Arrays.asList( "陕西农村信用社" ) ),
    SXCCU( Arrays.asList( "陕西信合银行" ) ),
    SQNB( Arrays.asList( "商丘商行" ) ),
    SHRCB( Arrays.asList( "上海农村商业银行" ) ),
    SPDB( Arrays.asList( "上海浦东发展银行" ) ),
    SHBANK( Arrays.asList( "上海银行" ) ),
    SRBANK( Arrays.asList( "上饶银行" ) ),
    SYCB( Arrays.asList( "上虞农商银行" ) ),
    SXCB( Arrays.asList( "绍兴银行" ) ),
    SZBAGYCZBK( Arrays.asList( "深圳宝安桂银村镇银行" ) ),
    SDB( Arrays.asList( "深圳发展银行" ) ),
    FTYZB( Arrays.asList( "深圳福田银座村镇银行" ) ),
    SRCB( Arrays.asList( "深圳农村商业银行" ) ),
    WEBANK( Arrays.asList( "深圳前海微众银行" ) ),
    SJBANK( Arrays.asList( "盛京银行" ) ),
    SYRCB( Arrays.asList( "十堰农村商业银行" ) ),
    SZSCCB( Arrays.asList( "石嘴山银行" ) ),
    SDEBANK( Arrays.asList( "顺德农村商业银行" ) ),
    SCRCU( Arrays.asList( "四川省农村信用社" ) ),
    PWEB( Arrays.asList( "四川天府银行" ) ),
    SCB( Arrays.asList( "四川银行" ) ),
    SZRCB( Arrays.asList( "苏州农商业银行" ) ),
    BOSZ( Arrays.asList( "苏州银行" ) ),
    SNCCB( Arrays.asList( "遂宁银行" ) ),
    TZCB( Arrays.asList( "台州银行" ) ),
    TCRCB( Arrays.asList( "太仓农商银行" ) ),
    TACCB( Arrays.asList( "泰安银行" ) ),
    TSB( Arrays.asList( "唐山银行" ) ),
    TJDSCZB( Arrays.asList( "天津滨海德商村镇银行" ) ),
    TJBHB( Arrays.asList( "天津滨海农村商业银行" ) ),
    TJJHCZ( Arrays.asList( "天津静海新华村镇银行" ) ),
    NINGHEB( Arrays.asList( "天津宁河村镇银行" ) ),
    TRCB( Arrays.asList( "天津农商银行" ) ),
    TCCB( Arrays.asList( "天津银行" ) ),
    TJNHVTB( Arrays.asList( "调兵山惠民村镇银行" ) ),
    DBSHMVTB( Arrays.asList( "铁岭新星村镇银行" ) ),
    BOTL( Arrays.asList( "铁岭银行股份有限公司" ) ),
    TLXXVTB( Arrays.asList( "图们敦银村镇银行" ) ),
    TMDYVTB( Arrays.asList( "屯留三禾村镇银行" ) ),
    WNSCB( Arrays.asList( "皖南农商银行" ) ),
    TLSHVTB( Arrays.asList( "万全家银村镇银行" ) ),
    WQHRCZB( Arrays.asList( "汪清和润村镇银行" ) ),
    BOWHLH( Arrays.asList( "威海蓝海银行" ) ),
    WHCB( Arrays.asList( "威海市商业银行" ) ),
    WHCCB( Arrays.asList( "威海银行" ) ),
    SBANK( Arrays.asList( "微商银行" ) ),
    BANKWF( Arrays.asList( "潍坊银行" ) ),
    WSHYVTB( Arrays.asList( "尉氏合益村镇银行" ) ),
    YXYTVTB( Arrays.asList( "蔚县银泰村镇银行" ) ),
    WZMSB( Arrays.asList( "温州民商银行股份有限公司" ) ),
    WZCB( Arrays.asList( "温州银行" ) ),
    WCRCB( Arrays.asList( "文昌大众村镇银行" ) ),
    WSRDVTB( Arrays.asList( "文水县润都村镇银行有限公司" ) ),
    WHBANK( Arrays.asList( "乌海银行" ) ),
    URMQCCB( Arrays.asList( "乌鲁木齐商业银行" ) ),
    BOWLMQ( Arrays.asList( "乌鲁木齐银行股份有限公司" ) ),
    WWHYVTB( Arrays.asList( "无为徽银村镇银行" ) ),
    WRCB( Arrays.asList( "无锡农村商业银行" ) ),
    QSYH( Arrays.asList( "芜湖泰寿村镇银行" ) ),
    WHB( Arrays.asList( "芜湖银行" ) ),
    WJNB( Arrays.asList( "吴江农商银行" ) ),
    WCHMB( Arrays.asList( "五常惠民村镇银行" ) ),
    WFJGVTB( Arrays.asList( "五峰金谷村镇银行" ) ),
    WAVTB( Arrays.asList( "武安村镇银行" ) ),
    WCYRVTB( Arrays.asList( "武城圆融村镇银行" ) ),
    WHRCB( Arrays.asList( "武汉农村商业银行" ) ),
    WQJYVTB( Arrays.asList( "武强家银村镇银行" ) ),
    WXXZDVTB( Arrays.asList( "武乡县泽都村镇银行有限责任公司" ) ),
    WYRCB( Arrays.asList( "武义农商银行" ) ),
    XABANK( Arrays.asList( "西安银行" ) ),
    XZB( Arrays.asList( "西藏银行" ) ),
    XCJXVTB( Arrays.asList( "西昌金信村镇银行" ) ),
    QYSXFRX( Arrays.asList( "西峰瑞信村镇银行" ) ),
    ASXHNM( Arrays.asList( "西航南马村镇银行" ) ),
    XJJDVTB( Arrays.asList( "夏津胶东村镇银行" ) ),
    XHYM( Arrays.asList( "香河益民村镇银行股份有限公司" ) ),
    XCHPVTB( Arrays.asList( "襄城汇浦村镇银行" ) ),
    XFXWDVTB( Arrays.asList( "襄汾县万都村镇银行有限责任公司" ) ),
    XYRHVTB( Arrays.asList( "襄垣县融汇村镇银行有限责任公司" ) ),
    ZJXSBANK( Arrays.asList( "萧山农商银行" ) ),
    XYHTCB( Arrays.asList( "孝义汇通村镇银行" ) ),
    XZXFXDVTB( Arrays.asList( "忻州市忻府区秀都村镇银行有限责任公司" ) ),
    XHBANK( Arrays.asList( "新华村镇银行" ) ),
    XJHHYX( Arrays.asList( "新疆汇和银行股份有限公司" ) ),
    XJRCU( Arrays.asList( "新疆农村信用社" ) ),
    XJBANK( Arrays.asList( "新疆银行" ) ),
    XJXTVTB( Arrays.asList( "新绛新田村镇银行" ) ),
    SDXTQF( Arrays.asList( "新泰齐丰村镇银行" ) ),
    HNXXXX( Arrays.asList( "新乡新兴村镇银行" ) ),
    XXBANK( Arrays.asList( "新乡银行" ) ),
    XYPQZYVTB( Arrays.asList( "信阳平桥中原村镇银行" ) ),
    XYBANK( Arrays.asList( "信阳银行" ) ),
    XTB( Arrays.asList( "邢台银行" ) ),
    XXHZVTB( Arrays.asList( "兴县汇泽村镇银行" ) ),
    CIB( Arrays.asList( "兴业银行" ) ),
    LNZYJY( Arrays.asList( "岫岩金玉村镇银行" ) ),
    XZBANK( Arrays.asList( "徐州银行" ) ),
    XCXPVTB( Arrays.asList( "许昌新浦村镇银行" ) ),
    XCBANK( Arrays.asList( "许昌银行" ) ),
    XHJYVTB( Arrays.asList( "宣化家银村镇银行" ) ),
    YACCB( Arrays.asList( "雅安市商业银行" ) ),
    YTBANK( Arrays.asList( "烟台银行" ) ),
    YJHRVTB( Arrays.asList( "延吉和润村镇银行" ) ),
    YCB( Arrays.asList( "盐城银行" ) ),
    YZB( Arrays.asList( "扬州银行" ) ),
    YCSHVTB( Arrays.asList( "阳城三禾村镇银行" ) ),
    YGCZYH( Arrays.asList( "阳光村镇银行" ) ),
    YQCCB( Arrays.asList( "阳泉商业银行" ) ),
    YBCCBK( Arrays.asList( "宜宾市商业银行" ) ),
    YCBANK( Arrays.asList( "宜昌银行" ) ),
    KMYLRF( Arrays.asList( "宜良融丰村镇银行" ) ),
    ZJYURB( Arrays.asList( "义乌联合村镇银行" ) ),
    YRCBANK( Arrays.asList( "义乌农商银行" ) ),
    YZBANK( Arrays.asList( "银座村镇银行" ) ),
    BEEB( Arrays.asList( "鄞州银行" ) ),
    YTYH( Arrays.asList( "鹰潭月湖恒通村镇银行" ) ),
    XYLFVTB( Arrays.asList( "荥阳利丰村镇银行股份有限公司" ) ),
    YKCB( Arrays.asList( "营口沿海银行" ) ),
    BOYK( Arrays.asList( "营口银行" ) ),
    JQCZBK( Arrays.asList( "永吉吉庆村镇银行" ) ),
    YLB( Arrays.asList( "永隆银行" ) ),
    YSRB( Arrays.asList( "永兴沪农商村镇银行" ) ),
    HNNXS( Arrays.asList( "永州农村商业银行" ) ),
    YLBANK( Arrays.asList( "友利银行" ) ),
    YHNSBANK( Arrays.asList( "余杭农村商业银行" ) ),
    YCJDVTB( Arrays.asList( "禹城胶东村镇银行" ) ),
    YZXMSVTB( Arrays.asList( "禹州新民生村镇银行" ) ),
    HHHTSYQMY( Arrays.asList( "玉泉蒙银村镇银行" ) ),
    YXBANK( Arrays.asList( "玉溪银行" ) ),
    YSXRVTB( Arrays.asList( "元氏信融村镇银行" ) ),
    YAJGVTB( Arrays.asList( "远安金谷村镇银行" ) ),
    yhurb( Arrays.asList( "云和联合村镇银行" ) ),
    YNHTBANK( Arrays.asList( "云南红塔银行" ) ),
    YNRCC( Arrays.asList( "云南农村信用社" ) ),
    YXRFVTB( Arrays.asList( "云霄润发村镇银行" ) ),
    ZZB( Arrays.asList( "枣庄银行" ) ),
    SCHK( Arrays.asList( "渣打银行" ) ),
    ZHQYVTB( Arrays.asList( "沾化青云村镇银行" ) ),
    ZJNRCB( Arrays.asList( "湛江农村商业银行" ) ),
    RCBOZ( Arrays.asList( "张家港农商银行" ) ),
    ZJKCCB( Arrays.asList( "张家口银行" ) ),
    CCAB( Arrays.asList( "长安银行" ) ),
    DYCCBB( Arrays.asList( "长城华西银行" ) ),
    CCCYHRVTB( Arrays.asList( "长春朝阳和润村镇银行" ) ),
    CCEDCB( Arrays.asList( "长春二道农商村镇银行" ) ),
    CCRFCB( Arrays.asList( "长春经开融丰村镇银行" ) ),
    CCLYRT( Arrays.asList( "长春绿园融泰村镇银行股份有限公司" ) ),
    CCNGHMVTB( Arrays.asList( "长春南关惠民村镇银行有限责任公司" ) ),
    CGXYVTB( Arrays.asList( "长葛轩辕村镇银行" ) ),
    JSCCB( Arrays.asList( "长江商业银行" ) ),
    CRCB( Arrays.asList( "长沙农商银行" ) ),
    CSCB( Arrays.asList( "长沙银行" ) ),
    ZJCURB( Arrays.asList( "长兴联合村镇银行" ) ),
    SHXIB( Arrays.asList( "长治银行" ) ),
    ZZRHVTB( Arrays.asList( "长子融汇村镇银行" ) ),
    CMB( Arrays.asList( "招商银行" ) ),
    ZCHHVTB( Arrays.asList( "柘城黄淮村镇银行" ) ),
    CZCB( Arrays.asList( "浙江稠州商业银行" ) ),
    MTBANK( Arrays.asList( "浙江民泰商业银行" ) ),
    ZJNX( Arrays.asList( "浙江农村信用合作社" ) ),
    SMYZB( Arrays.asList( "浙江三门银座村镇银行" ) ),
    ZJTLCB( Arrays.asList( "浙江泰隆商业银行" ) ),
    ZTMRB( Arrays.asList( "浙江天台民生村镇银行" ) ),
    MYBANK( Arrays.asList( "浙江网商银行" ) ),
    ZJXSHS( Arrays.asList( "浙江萧山湖商村镇银行股份有限公司" ) ),
    ZJCX( Arrays.asList( "浙江长兴联合村镇银行股份有限公司" ) ),
    ZJURB( Arrays.asList( "浙江诸暨联合村镇银行" ) ),
    CZBANK( Arrays.asList( "浙商银行" ) ),
    ZJBANK( Arrays.asList( "镇江银行" ) ),
    ZZBANK( Arrays.asList( "郑州银行" ) ),
    SDZZQF( Arrays.asList( "芝罘齐丰村镇银行" ) ),
    BOC( Arrays.asList( "中国银行" ) ),
    YSB( Arrays.asList( "中国银盛" ) ),
    PSBC( Arrays.asList( "中国邮政储蓄银行" ) ),
    ZSXLVTB( Arrays.asList( "中山小榄村镇银行" ) ),
    AIBANK( Arrays.asList( "中信百信银行股份有限公司" ) ),
    CITIC( Arrays.asList( "中信银行股份有限公司" ) ),
    BOCFTB( Arrays.asList( "中银富登村镇银行" ) ),
    ZYBANK( Arrays.asList( "中原银行" ) ),
    LPSZSLD( Arrays.asList( "钟山凉都村镇银行" ) ),
    CQFMB( Arrays.asList( "重庆富民银行股份有限公司" ) ),
    JLPMTRB( Arrays.asList( "重庆九龙坡民泰村镇银行" ) ),
    CRCBANK( Arrays.asList( "重庆农村商业银行" ) ),
    CQRCB( Arrays.asList( "重庆农商" ) ),
    CCQTGB( Arrays.asList( "重庆三峡银行" ) ),
    CQBANK( Arrays.asList( "重庆银行" ) ),
    ZKBANK( Arrays.asList( "周口银行" ) ),
    CRBANK( Arrays.asList( "珠海华润银行" ) ),
    ZHNS( Arrays.asList( "珠海市农商银行" ) ),
    ZBMBANK( Arrays.asList( "驻马店银行" ) ),
    ZHHTVTB( Arrays.asList( "庄河汇通村镇银行" ) ),
    ZJRCBANK( Arrays.asList( "紫金农商银行" ) ),
    ZGCCB( Arrays.asList( "自贡银行" ) ),
    ZYBA( Arrays.asList( "遵义银行" ) ),
    ZYCZVTB( Arrays.asList( "遵义长征村镇银行" ) ),
    XMBANK( Arrays.asList( "厦门银行" ) ),
    YNHTB( Arrays.asList( "云南红塔银行股份有限公司" ) ),
    ZHHRYX( Arrays.asList( "珠海华润银行股份有限公司" ) ),
    ZJMTCB( Arrays.asList( "浙江民泰商业银行股份有限公司" ) ),
    ZJNXX( Arrays.asList( "浙江农信" ) ),
    ZJRCB( Arrays.asList( "浙江农商银行" ) ),
    ZQSXYX( Arrays.asList( "重庆三峡银行股份有限公司" ) ),
    ZYB( Arrays.asList( "中原银行股份有限公司" ) ),
    ZYFDVTB( Arrays.asList( "中银富登村镇银行股份有限公司" ) ),
    XFVB( Arrays.asList( "兴福村镇银行" ) ),
    RQVB( Arrays.asList( "任丘村镇银行" ) ),
    QYVB( Arrays.asList( "祁阳村镇银行" ) ),
    XXSVB( Arrays.asList( "湘乡市村镇银行" ) ),
    ZYFMVB( Arrays.asList( "紫云富民村镇银行" ) ),
    ZYMSVTB( Arrays.asList( "资阳民生村镇银行" ) ),
    ZXPFVB( Arrays.asList( "资兴浦发村镇银行" ) ),
    ZXJYVB( Arrays.asList( "资溪九银村镇银行" ) ),
    ZZMYVB( Arrays.asList( "卓资蒙银村镇银行" ) ),
    ZZZCVB( Arrays.asList( "涿州中成村镇银行" ) ),
    ZXMSVB( Arrays.asList( "钟祥民生村镇银行" ) ),
    ZWXSVB( Arrays.asList( "中卫香山村镇银行" ) ),
    ZZZJVB( Arrays.asList( "郑州珠江村镇银行" ) ),
    ZYYCVB( Arrays.asList( "正阳玉川村镇银行" ) ),
    ZYMSVB( Arrays.asList( "长垣民生村镇银行" ) ),
    ZYXFVB( Arrays.asList( "长阳兴福村镇银行" ) ),
    ZSFMVB( Arrays.asList( "长顺富民村镇银行" ) ),
    ZSSYVB( Arrays.asList( "樟树顺银村镇银行" ) ),
    ZQQLVB( Arrays.asList( "章丘齐鲁村镇银行" ) ),
    ZZPFVB( Arrays.asList( "泽州浦发村镇银行" ) ),
    YMXFVB( Arrays.asList( "元谋兴福村镇银行" ) ),
    YSRXVTB( Arrays.asList( "榆树融兴村镇银行" ) ),
    YCQLVB( Arrays.asList( "永城齐鲁村镇银行" ) ),
    YMXFVTB( Arrays.asList( "易门兴福村镇银行" ) ),
    YCQLVTB( Arrays.asList( "伊川齐鲁村镇银行" ) ),
    YSRXVB( Arrays.asList( "偃师融兴村镇银行" ) ),
    YSRXVBANK( Arrays.asList( "延寿融兴村镇银行" ) ),
    WDZCVTB( Arrays.asList( "无棣中成村镇银行" ) ),
    WXQLVB( Arrays.asList( "温县齐鲁村镇银行" ) ),
    WXQLVTB( Arrays.asList( "魏县齐鲁村镇银行" ) ),
    WHFMVB( Arrays.asList( "卫辉富民村镇银行" ) ),
    WHFMVTB( Arrays.asList( "威海富民村镇银行" ) ),
    WDZCVB( Arrays.asList( "望都中成村镇银行" ) ),
    TCMSVB( Arrays.asList( "腾冲民生村镇银行" ) ),
    TCMSVTB( Arrays.asList( "太仓民生村镇银行" ) ),
    SLJYVTB( Arrays.asList( "双辽吉银村镇银行" ) ),
    SCHMVB( Arrays.asList( "双城惠民村镇银行" ) ),
    SLJYVB( Arrays.asList( "舒兰吉银村镇银行" ) ),
    SCHMVTB( Arrays.asList( "上蔡惠民村镇银行" ) ),
    NHXFVB( Arrays.asList( "内黄兴福村镇银行" ) ),
    NHRXVTB( Arrays.asList( "讷河融兴村镇银行" ) ),
    NHXFVTB( Arrays.asList( "南华兴福村镇银行" ) ),
    NHRXVB( Arrays.asList( "南和融信村镇银行" ) ),
    HDHMVTB( Arrays.asList( "惠东惠民村镇银行" ) ),
    ZYTYVB( Arrays.asList( "枞阳泰业村镇银行" ) ),
    ZQFYVB( Arrays.asList( "枣强丰源村镇银行" ) ),
    ZPPFVB( Arrays.asList( "邹平浦发村镇银行" ) ),
    ZPMSVB( Arrays.asList( "漳浦民生村镇银行" ) ),
    ZNZCVB( Arrays.asList( "长宁中成村镇银行" ) ),
    ZNHSVB( Arrays.asList( "镇宁汇商村镇银行" ) ),
    ZMZYVB( Arrays.asList( "中牟郑银村镇银行" ) ),
    ZLLFVB( Arrays.asList( "涿鹿利丰村镇银行" ) ),
    ZLJYVB( Arrays.asList( "长岭蛟银村镇银行" ) ),
    ZJRXVB( Arrays.asList( "中江融兴村镇银行" ) ),
    ZJHYVB( Arrays.asList( "枝江汉银村镇银行" ) ),
    ZJHMVB( Arrays.asList( "织金惠民村镇银行" ) ),
    ZHRHVB( Arrays.asList( "遵化融和村镇银行" ) ),
    ZHNPVB( Arrays.asList( "珠海南屏村镇银行" ) ),
    ZHLXVB( Arrays.asList( "赞皇隆兴村镇银行" ) ),
    ZHHQVB( Arrays.asList( "珠海横琴村镇银行" ) ),
    ZGZCVB( Arrays.asList( "自贡中成村镇银行" ) ),
    ZGXFVB( Arrays.asList( "秭归兴福村镇银行" ) ),
    ZFXZVB( Arrays.asList( "贞丰兴贞村镇银行" ) ),
    ZDMSVB( Arrays.asList( "志丹民生村镇银行" ) ),
    ZDHSVB( Arrays.asList( "正定恒升村镇银行" ) ),
    ZBYYVB( Arrays.asList( "长白榆银村镇银行" ) ),
    ZBXDVB( Arrays.asList( "张北信达村镇银行" ) ),
    YZZXVB( Arrays.asList( "宜章长行村镇银行" ) ),
    YZZCVB( Arrays.asList( "兖州中成村镇银行" ) ),
    YZSTVB( Arrays.asList( "宜州深通村镇银行" ) ),
    YZPFVB( Arrays.asList( "榆中浦发村镇银行" ) ),
    YZHFVB( Arrays.asList( "扬中恒丰村镇银行" ) ),
    YYXFVB( Arrays.asList( "宜阳兴福村镇银行" ) ),
    YYTJVB( Arrays.asList( "余姚通济村镇银行" ) ),
    YYLHVB( Arrays.asList( "弋阳蓝海村镇银行" ) ),
    YYBSVB( Arrays.asList( "沂源博商村镇银行" ) ),
    YXYXVB( Arrays.asList( "宜兴阳羡村镇银行" ) ),
    YXXYVB( Arrays.asList( "永修浔银村镇银行" ) ),
    YXLLVB( Arrays.asList( "永新庐陵村镇银行" ) ),
    YXJDVB( Arrays.asList( "应县金都村镇银行" ) ),
    YXHYVB( Arrays.asList( "阳新汉银村镇银行" ) ),
    YXHTVB( Arrays.asList( "玉溪红塔村镇银行" ) ),
    YXHMVB( Arrays.asList( "盂县汇民村镇银行" ) ),
    YXHHVB( Arrays.asList( "阳信河海村镇银行" ) ),
    YTYYVB( Arrays.asList( "伊通榆银村镇银行" ) ),
    YTQLVB( Arrays.asList( "鱼台青隆村镇银行" ) ),
    YTDSVB( Arrays.asList( "玉田大商村镇银行" ) ),
    YQJYVB( Arrays.asList( "永清吉银村镇银行" ) ),
    YPZZVB( Arrays.asList( "玉屏长征村镇银行" ) ),
    YLZYVB( Arrays.asList( "鄢陵郑银村镇银行" ) ),
    YLZCVB( Arrays.asList( "筠连中成村镇银行" ) ),
    YLHXVB( Arrays.asList( "依兰惠鑫村镇银行" ) ),
    YLGMVB( Arrays.asList( "伊犁国民村镇银行" ) ),
    YKHCVB( Arrays.asList( "营口宏诚村镇银行" ) ),
    YJZZVB( Arrays.asList( "印江长征村镇银行" ) ),
    YJPFVB( Arrays.asList( "沅江浦发村镇银行" ) ),
    YHZZVB( Arrays.asList( "沿河长征村镇银行" ) ),
    YHFSVB( Arrays.asList( "宜黄抚商村镇银行" ) ),
    YGHTVB( Arrays.asList( "余干恒通村镇银行" ) ),
    YFHDVB( Arrays.asList( "永丰洪都村镇银行" ) ),
    YDMSVB( Arrays.asList( "宜都民生村镇银行" ) ),
    YCTSVB( Arrays.asList( "虞城通商村镇银行" ) ),
    YCRXVB( Arrays.asList( "应城融兴村镇银行" ) ),
    YCBHVB( Arrays.asList( "郓城北海村镇银行" ) ),
    YBXYVB( Arrays.asList( "宜宾兴宜村镇银行" ) ),
    YARSVB( Arrays.asList( "依安润生村镇银行" ) ),
    YAHMVB( Arrays.asList( "云安惠民村镇银行" ) ),
    XZZYVB( Arrays.asList( "新郑郑银村镇银行" ) ),
    XYZJVB( Arrays.asList( "信阳珠江村镇银行" ) ),
    XYWFVB( Arrays.asList( "兴义万丰村镇银行" ) ),
    XXZYVB( Arrays.asList( "新乡中原村镇银行" ) ),
    XXZXVB( Arrays.asList( "湘西长行村镇银行" ) ),
    XXXTVB( Arrays.asList( "隰县新田村镇银行" ) ),
    XXRHVB( Arrays.asList( "献县融和村镇银行" ) ),
    XXQLVB( Arrays.asList( "莘县青隆村镇银行" ) ),
    XXHDVB( Arrays.asList( "夏县河东村镇银行" ) ),
    XXFYVB( Arrays.asList( "雄县丰源村镇银行" ) ),
    XWJHVB( Arrays.asList( "修文江海村镇银行" ) ),
    XTLFVB( Arrays.asList( "行唐利丰村镇银行" ) ),
    XSJYVB( Arrays.asList( "修水九银村镇银行" ) ),
    XSGMVB( Arrays.asList( "象山国民村镇银行" ) ),
    XSBFVB( Arrays.asList( "兴山本富村镇银行" ) ),
    XRZXVB( Arrays.asList( "兴仁振兴村镇银行" ) ),
    XPZYVB( Arrays.asList( "西平中原村镇银行" ) ),
    XNZJVB( Arrays.asList( "兴宁珠江村镇银行" ) ),
    XMZYVB( Arrays.asList( "新密郑银村镇银行" ) ),
    XJZJVB( Arrays.asList( "新津珠江村镇银行" ) ),
    XJQLVB( Arrays.asList( "辛集齐鲁村镇银行" ) ),
    XJHDVB( Arrays.asList( "峡江洪都村镇银行" ) ),
    XHZCVB( Arrays.asList( "宣化中成村镇银行" ) ),
    XHSNVB( Arrays.asList( "兴化苏南村镇银行" ) ),
    XHMSVB( Arrays.asList( "兴和蒙商村镇银行" ) ),
    XHCMVB( Arrays.asList( "宣汉诚民村镇银行" ) ),
    XFLCVB( Arrays.asList( "西丰鹿城村镇银行" ) ),
    XFFZVB( Arrays.asList( "息烽发展村镇银行" ) ),
    XDGCVB( Arrays.asList( "新都桂城村镇银行" ) ),
    XCZXVB( Arrays.asList( "兴城长兴村镇银行" ) ),
    XCBFVB( Arrays.asList( "孝昌本富村镇银行" ) ),
    XARXVB( Arrays.asList( "新安融兴村镇银行" ) ),
    WZSYVB( Arrays.asList( "武陟射阳村镇银行" ) ),
    WYYCVB( Arrays.asList( "舞阳玉川村镇银行" ) ),
    WYMYVB( Arrays.asList( "五原蒙银村镇银行" ) ),
    WTLSVB( Arrays.asList( "五台莱商村镇银行" ) ),
    WSMFVB( Arrays.asList( "文山民丰村镇银行" ) ),
    WSLFVB( Arrays.asList( "乌苏利丰村镇银行" ) ),
    WSBHVB( Arrays.asList( "微山北海村镇银行" ) ),
    WQRXVB( Arrays.asList( "吴桥融信村镇银行" ) ),
    WNJGVB( Arrays.asList( "万宁金谷村镇银行" ) ),
    WNHTVB( Arrays.asList( "武宁恒通村镇银行" ) ),
    WNDYVB( Arrays.asList( "万年稻源村镇银行" ) ),
    WMFMVB( Arrays.asList( "望谟富民村镇银行" ) ),
    WJXHVB( Arrays.asList( "望江新华村镇银行" ) ),
    WHYRVB( Arrays.asList( "芜湖圆融村镇银行" ) ),
    WHHMVB( Arrays.asList( "五华惠民村镇银行" ) ),
    WGFZVB( Arrays.asList( "武冈发展村镇银行" ) ),
    WDXFVB( Arrays.asList( "武定兴福村镇银行" ) ),
    WCLNVB( Arrays.asList( "武川立农村镇银行" ) ),
    WAHDVB( Arrays.asList( "万安洪都村镇银行" ) ),
    WAFMVB( Arrays.asList( "瓮安富民村镇银行" ) ),
    TZMSVB( Arrays.asList( "天长民生村镇银行" ) ),
    TYXYVB( Arrays.asList( "田阳兴阳村镇银行" ) ),
    TYXFVB( Arrays.asList( "汤阴兴福村镇银行" ) ),
    TYVB( Arrays.asList( "通榆农商村镇银行" ) ),
    TXRXVB( Arrays.asList( "通许融信村镇银行" ) ),
    TXHZVB( Arrays.asList( "唐县汇泽村镇银行" ) ),
    TRFYVB( Arrays.asList( "铜仁丰源村镇银行" ) ),
    TQMYVB( Arrays.asList( "突泉蒙银村镇银行" ) ),
    TQDSVB( Arrays.asList( "台前德商村镇银行" ) ),
    TNMSVB( Arrays.asList( "潼南民生村镇银行" ) ),
    TNHMVB( Arrays.asList( "洮南惠民村镇银行" ) ),
    TLVB( Arrays.asList( "铁岭农商村镇银行" ) ),
    TLJGVB( Arrays.asList( "通辽金谷村镇银行" ) ),
    TJWQVB( Arrays.asList( "天津武清村镇银行" ) ),
    TJJNVB( Arrays.asList( "天津津南村镇银行" ) ),
    TJHXVB( Arrays.asList( "同江汇鑫村镇银行" ) ),
    TJHMVB( Arrays.asList( "天津华明村镇银行" ) ),
    TJFMVB( Arrays.asList( "台江富民村镇银行" ) ),
    THRDVB( Arrays.asList( "通化融达村镇银行" ) ),
    TGJYVB( Arrays.asList( "铜鼓九银村镇银行" ) ),
    TCKLVB( Arrays.asList( "塔城昆仑村镇银行" ) ),
    TCJHVB( Arrays.asList( "塔城津汇村镇银行" ) ),
    TCHMVB( Arrays.asList( "通城惠民村镇银行" ) ),
    SZZFVB( Arrays.asList( "绥中长丰村镇银行" ) ),
    SZXFVB( Arrays.asList( "师宗兴福村镇银行" ) ),
    SZLFVB( Arrays.asList( "深泽利丰村镇银行" ) ),
    SZHXVB( Arrays.asList( "尚志惠鑫村镇银行" ) ),
    SZFYVB( Arrays.asList( "深州丰源村镇银行" ) ),
    SYQBVB( Arrays.asList( "绥阳黔北村镇银行" ) ),
    SYHMVB( Arrays.asList( "三亚惠民村镇银行" ) ),
    SXXFVB( Arrays.asList( "嵩县兴福村镇银行" ) ),
    SXQLVB( Arrays.asList( "涉县齐鲁村镇银行" ) ),
    SXDZVB( Arrays.asList( "始兴大众村镇银行" ) ),
    SXDSVB( Arrays.asList( "睢县德商村镇银行" ) ),
    STZZVB( Arrays.asList( "松桃长征村镇银行" ) ),
    SSZJVB( Arrays.asList( "三水珠江村镇银行" ) ),
    SSZCVB( Arrays.asList( "鄯善中成村镇银行" ) ),
    SSGDVB( Arrays.asList( "韶山光大村镇银行" ) ),
    SQZZVB( Arrays.asList( "石阡长征村镇银行" ) ),
    SPZYVB( Arrays.asList( "遂平中原村镇银行" ) ),
    SNZZVB( Arrays.asList( "思南长征村镇银行" ) ),
    SHZCVB( Arrays.asList( "上杭中成村镇银行" ) ),
    SHXTVB( Arrays.asList( "沙河襄通村镇银行" ) ),
    SHMYVB( Arrays.asList( "三河蒙银村镇银行" ) ),
    SFSYVB( Arrays.asList( "什邡思源村镇银行" ) ),
    SDLLVB( Arrays.asList( "山东兰陵村镇银行" ) ),
    SDJNVB( Arrays.asList( "山东莒南村镇银行" ) ),
    SDFMVB( Arrays.asList( "三都富民村镇银行" ) ),
    SCMYVB( Arrays.asList( "水城蒙银村镇银行" ) ),
    SCHDVB( Arrays.asList( "遂川洪都村镇银行" ) ),
    SBJDVB( Arrays.asList( "施秉金鼎村镇银行" ) ),
    RZYCVB( Arrays.asList( "汝州玉川村镇银行" ) ),
    RZLHVB( Arrays.asList( "日照蓝海村镇银行" ) ),
    RZJYVB( Arrays.asList( "日照九银村镇银行" ) ),
    RYXFVB( Arrays.asList( "汝阳兴福村镇银行" ) ),
    RYMSVB( Arrays.asList( "饶阳民商村镇银行" ) ),
    RSTJVB( Arrays.asList( "乳山天骄村镇银行" ) ),
    RSMFVB( Arrays.asList( "仁寿民富村镇银行" ) ),
    RPRHVB( Arrays.asList( "饶平融和村镇银行" ) ),
    RHMYVB( Arrays.asList( "仁怀蒙银村镇银行" ) ),
    RCJYVB( Arrays.asList( "瑞昌九银村镇银行" ) ),
    QZXBVB( Arrays.asList( "清镇兴邦村镇银行" ) ),
    QZHSVB( Arrays.asList( "曲周恒升村镇银行" ) ),
    QYZCVB( Arrays.asList( "曲阳中成村镇银行" ) ),
    QYLLVB( Arrays.asList( "青原庐陵村镇银行" ) ),
    QYLAVB( Arrays.asList( "庆云乐安村镇银行" ) ),
    QXZYVB( Arrays.asList( "淇县中原村镇银行" ) ),
    QXQLVB( Arrays.asList( "青县青隆村镇银行" ) ),
    QXJSVB( Arrays.asList( "清徐晋商村镇银行" ) ),
    QXJRVB( Arrays.asList( "祁县晋融村镇银行" ) ),
    QXHMVB( Arrays.asList( "清徐惠民村镇银行" ) ),
    QTLFVB( Arrays.asList( "奇台利丰村镇银行" ) ),
    QSZYVB( Arrays.asList( "确山郑银村镇银行" ) ),
    QLXAVB( Arrays.asList( "晴隆兴安村镇银行" ) ),
    QLRXVB( Arrays.asList( "青龙融兴村镇银行" ) ),
    QLGMVB( Arrays.asList( "邛崃国民村镇银行" ) ),
    QJMSVB( Arrays.asList( "綦江民生村镇银行" ) ),
    QJHMVB( Arrays.asList( "曲靖惠民村镇银行" ) ),
    QHJNVB( Arrays.asList( "清河金农村镇银行" ) ),
    QHJDVB( Arrays.asList( "齐河胶东村镇银行" ) ),
    QHDZVB( Arrays.asList( "琼海大众村镇银行" ) ),
    QDHFVB( Arrays.asList( "祁东惠丰村镇银行" ) ),
    QAXLVB( Arrays.asList( "迁安襄隆村镇银行" ) ),
    QAHMVB( Arrays.asList( "乾安惠民村镇银行" ) ),
    PZWHVB( Arrays.asList( "盘州万和村镇银行" ) ),
    PZMSVB( Arrays.asList( "彭州民生村镇银行" ) ),
    PZJYVB( Arrays.asList( "彭泽九银村镇银行" ) ),
    PYZYVB( Arrays.asList( "濮阳中原村镇银行" ) ),
    PYYRVB( Arrays.asList( "平原圆融村镇银行" ) ),
    PYYCVB( Arrays.asList( "平舆玉川村镇银行" ) ),
    PYLHVB( Arrays.asList( "平阴蓝海村镇银行" ) ),
    PYHTVB( Arrays.asList( "鄱阳恒通村镇银行" ) ),
    PTFMVB( Arrays.asList( "平塘富民村镇银行" ) ),
    PSZJVB( Arrays.asList( "彭山珠江村镇银行" ) ),
    PSJYVB( Arrays.asList( "磐石吉银村镇银行" ) ),
    PSATVB( Arrays.asList( "盘山安泰村镇银行" ) ),
    PQHSVB( Arrays.asList( "平泉恒升村镇银行" ) ),
    PLSHVB( Arrays.asList( "平罗沙湖村镇银行" ) ),
    PLMSVB( Arrays.asList( "蓬莱民生村镇银行" ) ),
    PHRFVB( Arrays.asList( "平和润丰村镇银行" ) ),
    PGGMVB( Arrays.asList( "平果国民村镇银行" ) ),
    PEMSVB( Arrays.asList( "普洱民生村镇银行" ) ),
    PDFMVB( Arrays.asList( "普定富民村镇银行" ) ),
    PCZCVB( Arrays.asList( "浦城中成村镇银行" ) ),
    PCNKVB( Arrays.asList( "平昌农科村镇银行" ) ),
    PBDLVB( Arrays.asList( "平坝鼎立村镇银行" ) ),
    PAPHVB( Arrays.asList( "普安普惠村镇银行" ) ),
    NYFMVB( Arrays.asList( "纳雍富民村镇银行" ) ),
    NPRXVB( Arrays.asList( "南皮融信村镇银行" ) ),
    NLTPVB( Arrays.asList( "南陵太平村镇银行" ) ),
    NLDSVB( Arrays.asList( "宁陵德商村镇银行" ) ),
    NKGSVB( Arrays.asList( "南康赣商村镇银行" ) ),
    NJZCVB( Arrays.asList( "南靖中成村镇银行" ) ),
    NJXLVB( Arrays.asList( "内江兴隆村镇银行" ) ),
    NJXFVB( Arrays.asList( "嫩江幸福村镇银行" ) ),
    NJNKVB( Arrays.asList( "南江农科村镇银行" ) ),
    NJMSVB( Arrays.asList( "宁晋民生村镇银行" ) ),
    NJJDVB( Arrays.asList( "宁津胶东村镇银行" ) ),
    NGMSVB( Arrays.asList( "宁国民生村镇银行" ) ),
    NFJDVB( Arrays.asList( "南丰桔都村镇银行" ) ),
    NCMSVB( Arrays.asList( "宁城蒙商村镇银行" ) ),
    NCFMVB( Arrays.asList( "南城富民村镇银行" ) ),
    NCDFVB( Arrays.asList( "南昌大丰村镇银行" ) ),
    NARXVB( Arrays.asList( "宁安融兴村镇银行" ) ),
    NABYVB( Arrays.asList( "农安北银村镇银行" ) ),
    MZSYVB( Arrays.asList( "孟州射阳村镇银行" ) ),
    MZPFVB( Arrays.asList( "绵竹浦发村镇银行" ) ),
    MYYCVB( Arrays.asList( "泌阳玉川村镇银行" ) ),
    MSMYVB( Arrays.asList( "密山民意村镇银行" ) ),
    MQRXVB( Arrays.asList( "民勤融信村镇银行" ) ),
    MQDSVB( Arrays.asList( "民权德商村镇银行" ) ),
    MPJDVB( Arrays.asList( "牟平胶东村镇银行" ) ),
    MLYDVB( Arrays.asList( "穆棱远东村镇银行" ) ),
    MJMFVB( Arrays.asList( "孟津民丰村镇银行" ) ),
    MCQLVB( Arrays.asList( "渑池齐鲁村镇银行" ) ),
    LZZYVB( Arrays.asList( "林州中原村镇银行" ) ),
    LZZJVB( Arrays.asList( "莱州珠江村镇银行" ) ),
    LZZCVB( Arrays.asList( "滦州中成村镇银行" ) ),
    LZRXVB( Arrays.asList( "阆中融兴村镇银行" ) ),
    LZMSVB( Arrays.asList( "林芝民生村镇银行" ) ),
    LZHMVB( Arrays.asList( "雷州惠民村镇银行" ) ),
    LYTYVB( Arrays.asList( "凌源天元村镇银行" ) ),
    LYRXVB( Arrays.asList( "耒阳融兴村镇银行" ) ),
    LYPFVB( Arrays.asList( "溧阳浦发村镇银行" ) ),
    LYJDVB( Arrays.asList( "莱阳胶东村镇银行" ) ),
    LXYTVB( Arrays.asList( "泸县元通村镇银行" ) ),
    LXVB( Arrays.asList( "兰西农商村镇银行" ) ),
    LXSZVB( Arrays.asList( "陇西神舟村镇银行" ) ),
    LXQDVB( Arrays.asList( "临县泉都村镇银行" ) ),
    LXHRVB( Arrays.asList( "岚县慧融村镇银行" ) ),
    LWZJVB( Arrays.asList( "莱芜珠江村镇银行" ) ),
    LWZCVB( Arrays.asList( "莱芜中成村镇银行" ) ),
    LWPFVB( Arrays.asList( "临武浦发村镇银行" ) ),
    LTSFVB( Arrays.asList( "乐亭舜丰村镇银行" ) ),
    LSZYVB( Arrays.asList( "卢氏中原村镇银行" ) ),
    LSZCVB( Arrays.asList( "泸水中成村镇银行" ) ),
    LSYTVB( Arrays.asList( "梨树源泰村镇银行" ) ),
    LSTYVB( Arrays.asList( "灵山泰业村镇银行" ) ),
    LSMFVB( Arrays.asList( "临沭民丰村镇银行" ) ),
    LSLFVB( Arrays.asList( "涞水利丰村镇银行" ) ),
    LSKLVB( Arrays.asList( "乐山昆仑村镇银行" ) ),
    LSHMVB( Arrays.asList( "陵水惠民村镇银行" ) ),
    LQHSVB( Arrays.asList( "鹿泉恒升村镇银行" ) ),
    LPSYVB( Arrays.asList( "滦平盛阳村镇银行" ) ),
    LPRXVB( Arrays.asList( "乐平融兴村镇银行" ) ),
    LNZCVB( Arrays.asList( "滦南中成村镇银行" ) ),
    LNXFVB( Arrays.asList( "洛宁兴福村镇银行" ) ),
    LNSSVB( Arrays.asList( "辽宁首山村镇银行" ) ),
    LNSDVB( Arrays.asList( "辽宁沈东村镇银行" ) ),
    LNDTVB( Arrays.asList( "辽宁灯塔村镇银行" ) ),
    LLYRVB( Arrays.asList( "乐陵圆融村镇银行" ) ),
    LLXFVB( Arrays.asList( "陆良兴福村镇银行" ) ),
    LLJYVB( Arrays.asList( "卢龙家银村镇银行" ) ),
    LLHZVB( Arrays.asList( "柳林汇泽村镇银行" ) ),
    LLGFVB( Arrays.asList( "龙里国丰村镇银行" ) ),
    LKQLVB( Arrays.asList( "兰考齐鲁村镇银行" ) ),
    LJYYVB( Arrays.asList( "龙井榆银村镇银行" ) ),
    LJJYVB( Arrays.asList( "临江蛟银村镇银行" ) ),
    LJHMVB( Arrays.asList( "庐江惠民村镇银行" ) ),
    LHMYVB( Arrays.asList( "柳河蒙银村镇银行" ) ),
    LGHFVB( Arrays.asList( "临高惠丰村镇银行" ) ),
    LDHFVB( Arrays.asList( "乐东惠丰村镇银行" ) ),
    LDFZVB( Arrays.asList( "罗甸发展村镇银行" ) ),
    LCSTVB( Arrays.asList( "灵川深通村镇银行" ) ),
    LCRHVB( Arrays.asList( "龙川融和村镇银行" ) ),
    LCPFVB( Arrays.asList( "临川浦发村镇银行" ) ),
    LCFSVB( Arrays.asList( "黎川抚商村镇银行" ) ),
    LBRFVB( Arrays.asList( "灵宝融丰村镇银行" ) ),
    LBFMVB( Arrays.asList( "荔波富民村镇银行" ) ),
    LAHDVB( Arrays.asList( "乐安洪都村镇银行" ) ),
    KYFMVB( Arrays.asList( "开阳富民村镇银行" ) ),
    KTGMVB( Arrays.asList( "奎屯国民村镇银行" ) ),
    KSRSVB( Arrays.asList( "克山润生村镇银行" ) ),
    KSLCVB( Arrays.asList( "昆山鹿城村镇银行" ) ),
    KLMYVB( Arrays.asList( "开鲁蒙银村镇银行" ) ),
    KLDNVB( Arrays.asList( "凯里东南村镇银行" ) ),
    KDBFVB( Arrays.asList( "宽甸百丰村镇银行" ) ),
    KCRXVB( Arrays.asList( "宽城融兴村镇银行" ) ),
    KCGMVB( Arrays.asList( "库车国民村镇银行" ) ),
    KBYFVB( Arrays.asList( "康保银丰村镇银行" ) ),
    JZZJVB( Arrays.asList( "吉州珠江村镇银行" ) ),
    JZHSVB( Arrays.asList( "晋州恒升村镇银行" ) ),
    JYQLVB( Arrays.asList( "济源齐鲁村镇银行" ) ),
    JYQFVB( Arrays.asList( "靖宇乾丰村镇银行" ) ),
    JYPFVB( Arrays.asList( "江阴浦发村镇银行" ) ),
    JYBHVB( Arrays.asList( "济阳北海村镇银行" ) ),
    JXZYVB( Arrays.asList( "浚县郑银村镇银行" ) ),
    JXXTVB( Arrays.asList( "吉县新田村镇银行" ) ),
    JXRSVB( Arrays.asList( "集贤润生村镇银行" ) ),
    JXRFVB( Arrays.asList( "进贤瑞丰村镇银行" ) ),
    JXNYVB( Arrays.asList( "绩溪农银村镇银行" ) ),
    JXJGVB( Arrays.asList( "莒县金谷村镇银行" ) ),
    JXGTVB( Arrays.asList( "郏县广天村镇银行" ) ),
    JXFYVB( Arrays.asList( "景县丰源村镇银行" ) ),
    JXFSVB( Arrays.asList( "金溪抚商村镇银行" ) ),
    JWZCVB( Arrays.asList( "犍为中成村镇银行" ) ),
    JTLJVB( Arrays.asList( "九台龙嘉村镇银行" ) ),
    JTHJVB( Arrays.asList( "金堂汇金村镇银行" ) ),
    JSLLVB( Arrays.asList( "吉水庐陵村镇银行" ) ),
    JSFMVB( Arrays.asList( "金沙富民村镇银行" ) ),
    JRSNVB( Arrays.asList( "句容苏南村镇银行" ) ),
    JPHSVB( Arrays.asList( "建平红山村镇银行" ) ),
    JNLHVB( Arrays.asList( "济宁蓝海村镇银行" ) ),
    JNGXVB( Arrays.asList( "济宁高新村镇银行" ) ),
    JLRXVB( Arrays.asList( "巨鹿融信村镇银行" ) ),
    JKZZVB( Arrays.asList( "江口长征村镇银行" ) ),
    JJHTVB( Arrays.asList( "九江恒通村镇银行" ) ),
    JJGQVB( Arrays.asList( "九江共青村镇银行" ) ),
    JHZCVB( Arrays.asList( "建湖中成村镇银行" ) ),
    JHMSVB( Arrays.asList( "景洪民生村镇银行" ) ),
    JHJYVB( Arrays.asList( "蛟河吉银村镇银行" ) ),
    JHFMVB( Arrays.asList( "剑河富民村镇银行" ) ),
    JDMSVB( Arrays.asList( "旌德民商村镇银行" ) ),
    JCXFVB( Arrays.asList( "江川兴福村镇银行" ) ),
    JCMDVB( Arrays.asList( "鄄城牡丹村镇银行" ) ),
    JCHCVB( Arrays.asList( "建昌恒昌村镇银行" ) ),
    JAJYVB( Arrays.asList( "靖安九银村镇银行" ) ),
    JAHXVB( Arrays.asList( "集安惠鑫村镇银行" ) ),
    JACZVB( Arrays.asList( "吉安稠州村镇银行" ) ),
    HZSZVB( Arrays.asList( "和政神舟村镇银行" ) ),
    HZFMVB( Arrays.asList( "赫章富民村镇银行" ) ),
    HYZJVB( Arrays.asList( "海阳珠江村镇银行" ) ),
    HYHMVB( Arrays.asList( "合阳惠民村镇银行" ) ),
    HXZJVB( Arrays.asList( "辉县珠江村镇银行" ) ),
    HTQLVB( Arrays.asList( "桓台青隆村镇银行" ) ),
    HSZJVB( Arrays.asList( "鹤山珠江村镇银行" ) ),
    HSHMVB( Arrays.asList( "含山惠民村镇银行" ) ),
    HPZXVB( Arrays.asList( "黄平振兴村镇银行" ) ),
    HPGMVB( Arrays.asList( "合浦国民村镇银行" ) ),
    HNYYVB( Arrays.asList( "辉南榆银村镇银行" ) ),
    HNRXVB( Arrays.asList( "桦南融兴村镇银行" ) ),
    HNPFVB( Arrays.asList( "衡南浦发村镇银行" ) ),
    HNHSVB( Arrays.asList( "会宁会师村镇银行" ) ),
    HMTSVB( Arrays.asList( "哈密天山村镇银行" ) ),
    HLYDVB( Arrays.asList( "海林远东村镇银行" ) ),
    HLLFVB( Arrays.asList( "怀来利丰村镇银行" ) ),
    HLHFVB( Arrays.asList( "海伦惠丰村镇银行" ) ),
    HLDYVB( Arrays.asList( "和龙敦银村镇银行" ) ),
    HKSNVB( Arrays.asList( "海口苏南村镇银行" ) ),
    HKJYVB( Arrays.asList( "湖口九银村镇银行" ) ),
    HJRHVB( Arrays.asList( "河间融惠村镇银行" ) ),
    HJDZVB( Arrays.asList( "杭锦大众村镇银行" ) ),
    HHRXVB( Arrays.asList( "洪湖融兴村镇银行" ) ),
    HHQLVB( Arrays.asList( "黄骅青隆村镇银行" ) ),
    HFHTVB( Arrays.asList( "横峰恒通村镇银行" ) ),
    HDMSVB( Arrays.asList( "化德蒙商村镇银行" ) ),
    HCRXVB( Arrays.asList( "桦川融兴村镇银行" ) ),
    HCPFVB( Arrays.asList( "韩城浦发村镇银行" ) ),
    HCJYVB( Arrays.asList( "珲春吉银村镇银行" ) ),
    HAZCVB( Arrays.asList( "惠安中成村镇银行" ) ),
    GYPFVB( Arrays.asList( "巩义浦发村镇银行" ) ),
    GYMSVB( Arrays.asList( "固阳蒙商村镇银行" ) ),
    GXJYVB( Arrays.asList( "贵溪九银村镇银行" ) ),
    GTQLVB( Arrays.asList( "高唐青隆村镇银行" ) ),
    GSTJVB( Arrays.asList( "固始天骄村镇银行" ) ),
    GRLZVB( Arrays.asList( "广饶梁邹村镇银行" ) ),
    GMHMVB( Arrays.asList( "高密惠民村镇银行" ) ),
    GLHSVB( Arrays.asList( "关岭恒升村镇银行" ) ),
    GLGMVB( Arrays.asList( "桂林国民村镇银行" ) ),
    GHZJVB( Arrays.asList( "广汉珠江村镇银行" ) ),
    GFGXVB( Arrays.asList( "广丰广信村镇银行" ) ),
    GDHSVB( Arrays.asList( "贵定恒升村镇银行" ) ),
    GCNYVB( Arrays.asList( "广昌南银村镇银行" ) ),
    GCJYVB( Arrays.asList( "故城家银村镇银行" ) ),
    GCHSVB( Arrays.asList( "藁城恒升村镇银行" ) ),
    GAHSVB( Arrays.asList( "固安恒升村镇银行" ) ),
    GAHFVB( Arrays.asList( "广安恒丰村镇银行" ) ),
    FYZCVB( Arrays.asList( "富蕴中成村镇银行" ) ),
    FYJYVB( Arrays.asList( "分宜九银村镇银行" ) ),
    FYHMVB( Arrays.asList( "扶余惠民村镇银行" ) ),
    FXVB( Arrays.asList( "阜新农商村镇银行" ) ),
    FXLZVB( Arrays.asList( "费县梁邹村镇银行" ) ),
    FXJYVB( Arrays.asList( "奉新九银村镇银行" ) ),
    FSYYVB( Arrays.asList( "抚松榆银村镇银行" ) ),
    FSSTVB( Arrays.asList( "扶绥深通村镇银行" ) ),
    FPDSVB( Arrays.asList( "阜平大商村镇银行" ) ),
    FNMSVB( Arrays.asList( "阜宁民生村镇银行" ) ),
    FMPFVB( Arrays.asList( "富民浦发村镇银行" ) ),
    FLVB( Arrays.asList( "浮梁农商村镇银行" ) ),
    FKJHVB( Arrays.asList( "阜康津汇村镇银行" ) ),
    FJXFVB( Arrays.asList( "富锦幸福村镇银行" ) ),
    FGZYVB( Arrays.asList( "扶沟郑银村镇银行" ) ),
    FFPFVB( Arrays.asList( "扶风浦发村镇银行" ) ),
    FCSYVB( Arrays.asList( "丰城顺银村镇银行" ) ),
    FCJYVB( Arrays.asList( "阜城家银村镇银行" ) ),
    FCFYVB( Arrays.asList( "凤城丰益村镇银行" ) ),
    ESXFVB( Arrays.asList( "恩施兴福村镇银行" ) ),
    DZZCVB( Arrays.asList( "定州中成村镇银行" ) ),
    DZFMVB( Arrays.asList( "丹寨富民村镇银行" ) ),
    DYXFVB( Arrays.asList( "当阳兴福村镇银行" ) ),
    DYTYVB( Arrays.asList( "东源泰业村镇银行" ) ),
    DYRTVB( Arrays.asList( "都匀融通村镇银行" ) ),
    DYRHVB( Arrays.asList( "东营融和村镇银行" ) ),
    DXLHVB( Arrays.asList( "德兴蓝海村镇银行" ) ),
    DXGMVB( Arrays.asList( "东兴国民村镇银行" ) ),
    DXFYVB( Arrays.asList( "定兴丰源村镇银行" ) ),
    DTHHVB( Arrays.asList( "定陶河海村镇银行" ) ),
    DSFMVB( Arrays.asList( "独山富民村镇银行" ) ),
    DQHRVB( Arrays.asList( "德庆华润村镇银行" ) ),
    DNRSVB( Arrays.asList( "东宁润生村镇银行" ) ),
    DMHSVB( Arrays.asList( "大名恒升村镇银行" ) ),
    DLVB( Arrays.asList( "东辽农商村镇银行" ) ),
    DKMYVB( Arrays.asList( "磴口蒙银村镇银行" ) ),
    DJZZVB( Arrays.asList( "德江长征村镇银行" ) ),
    DHJNVB( Arrays.asList( "敦化江南村镇银行" ) ),
    DGZAVB( Arrays.asList( "东莞长安村镇银行" ) ),
    DGTHVB( Arrays.asList( "东港同合村镇银行" ) ),
    DGQLVB( Arrays.asList( "东光青隆村镇银行" ) ),
    DFQLVB( Arrays.asList( "登封齐鲁村镇银行" ) ),
    DFJYVB( Arrays.asList( "东丰吉银村镇银行" ) ),
    DFFMVB( Arrays.asList( "大方富民村镇银行" ) ),
    DDFHVB( Arrays.asList( "丹东福汇村镇银行" ) ),
    DDDYVB( Arrays.asList( "丹东鼎元村镇银行" ) ),
    DDDAVB( Arrays.asList( "丹东鼎安村镇银行" ) ),
    DCJYVB( Arrays.asList( "都昌九银村镇银行" ) ),
    DAQLVB( Arrays.asList( "东阿青隆村镇银行" ) ),
    DAHMVB( Arrays.asList( "大安惠民村镇银行" ) ),
    DAHFVB( Arrays.asList( "定安合丰村镇银行" ) ),
    CZSYVB( Arrays.asList( "崇州上银村镇银行" ) ),
    CYBHVB( Arrays.asList( "昌邑北海村镇银行" ) ),
    CXQLVB( Arrays.asList( "磁县齐鲁村镇银行" ) ),
    CXMSVB( Arrays.asList( "慈溪民生村镇银行" ) ),
    CXJYVB( Arrays.asList( "沧县吉银村镇银行" ) ),
    CXHTVB( Arrays.asList( "楚雄红塔村镇银行" ) ),
    CWSTVB( Arrays.asList( "苍梧深通村镇银行" ) ),
    CTMXVB( Arrays.asList( "昌图民祥村镇银行" ) ),
    CRJYVB( Arrays.asList( "崇仁九银村镇银行" ) ),
    CNZJVB( Arrays.asList( "常宁珠江村镇银行" ) ),
    CLPFVB( Arrays.asList( "茶陵浦发村镇银行" ) ),
    CJYMVB( Arrays.asList( "从江月明村镇银行" ) ),
    CJGMVB( Arrays.asList( "昌吉国民村镇银行" ) ),
    CHFMVB( Arrays.asList( "册亨富民村镇银行" ) ),
    CAQLVB( Arrays.asList( "成安齐鲁村镇银行" ) ),
    BZSFVB( Arrays.asList( "霸州舜丰村镇银行" ) ),
    BZHHVB( Arrays.asList( "滨州河海村镇银行" ) ),
    BYRXVB( Arrays.asList( "巴彦融兴村镇银行" ) ),
    BXTSVB( Arrays.asList( "本溪同盛村镇银行" ) ),
    BXRXVB( Arrays.asList( "柏乡融信村镇银行" ) ),
    BXHFVB( Arrays.asList( "本溪禾丰村镇银行" ) ),
    BXFYVB( Arrays.asList( "本溪丰业村镇银行" ) ),
    BXFTVB( Arrays.asList( "本溪丰泰村镇银行" ) ),
    BTGMVB( Arrays.asList( "北屯国民村镇银行" ) ),
    BQRXVB( Arrays.asList( "拜泉融兴村镇银行" ) ),
    BQGYVB( Arrays.asList( "宝清广益村镇银行" ) ),
    BPSDVB( Arrays.asList( "北票盛都村镇银行" ) ),
    BLGMVB( Arrays.asList( "博乐国民村镇银行" ) ),
    BJYQVB( Arrays.asList( "北京延庆村镇银行" ) ),
    BJFZVB( Arrays.asList( "毕节发展村镇银行" ) ),
    AYZJVB( Arrays.asList( "安阳珠江村镇银行" ) ),
    AYRXVB( Arrays.asList( "安义融兴村镇银行" ) ),
    AXMSVB( Arrays.asList( "安溪民生村镇银行" ) ),
    AXDSVB( Arrays.asList( "安新大商村镇银行" ) ),
    ASNYVB( Arrays.asList( "安塞农银村镇银行" ) ),
    AQBHVB( Arrays.asList( "安丘北海村镇银行" ) ),
    APHMVB( Arrays.asList( "安平惠民村镇银行" ) ),
    ALXLVB( Arrays.asList( "安龙兴龙村镇银行" ) ),
    AHHNVB( Arrays.asList( "敖汉惠农村镇银行" ) ),
    AGZCVB( Arrays.asList( "安国中成村镇银行" ) ),
    ADXFVB( Arrays.asList( "安达幸福村镇银行" ) ),
    ZYXZQVB( Arrays.asList( "左云县长青村镇银行" ) ),
    ZXCVB( Arrays.asList( "竹溪楚农商村镇银行" ) ),
    ZSCVB( Arrays.asList( "竹山楚农商村镇银行" ) ),
    ZZXRXVB( Arrays.asList( "株洲县融兴村镇银行" ) ),
    ZYXTXVB( Arrays.asList( "中阳县太行村镇银行" ) ),
    ZRCTHVB( Arrays.asList( "柘荣刺桐红村镇银行" ) ),
    ZTTZHVB( Arrays.asList( "长汀汀州红村镇银行" ) ),
    ZLTMYVB( Arrays.asList( "扎兰屯蒙银村镇银行" ) ),
    ZLTMYVTB( Arrays.asList( "扎赉特蒙银村镇银行" ) ),
    YXCVTB( Arrays.asList( "郧县楚农商村镇银行" ) ),
    YXCVB( Arrays.asList( "郧西楚农商村镇银行" ) ),
    SMHVB( Arrays.asList( "嵩明沪农商村镇银行" ) ),
    SMHVTB( Arrays.asList( "石门沪农商村镇银行" ) ),
    LLHVTB( Arrays.asList( "临澧沪农商村镇银行" ) ),
    LLHVB( Arrays.asList( "醴陵沪农商村镇银行" ) ),
    ZNCTHVB( Arrays.asList( "周宁刺桐红村镇银行" ) ),
    ZLQHZVB( Arrays.asList( "正蓝旗汇泽村镇银行" ) ),
    YYXZQVB( Arrays.asList( "右玉县长青村镇银行" ) ),
    YSSQSVB( Arrays.asList( "玉山三清山村镇银行" ) ),
    YQXHMVB( Arrays.asList( "阳曲县汇民村镇银行" ) ),
    YQXHDVB( Arrays.asList( "垣曲县河东村镇银行" ) ),
    YPSHMVB( Arrays.asList( "原平市汇民村镇银行" ) ),
    YMCVB( Arrays.asList( "云梦楚农商村镇银行" ) ),
    YJXJCVB( Arrays.asList( "永靖县金城村镇银行" ) ),
    YJSSHVB( Arrays.asList( "永济市三禾村镇银行" ) ),
    YGXXDVB( Arrays.asList( "阳高县兴都村镇银行" ) ),
    YGHVB( Arrays.asList( "阳谷沪农商村镇银行" ) ),
    XTCVB( Arrays.asList( "仙桃楚农商村镇银行" ) ),
    XSCVB( Arrays.asList( "浠水楚农商村镇银行" ) ),
    XPCTHVB( Arrays.asList( "霞浦刺桐红村镇银行" ) ),
    XJXXTVB( Arrays.asList( "新绛县新田村镇银行" ) ),
    WZSBHVB( Arrays.asList( "吴忠市滨河村镇银行" ) ),
    WYXVB( Arrays.asList( "武邑邢农商村镇银行" ) ),
    WYSBFVB( Arrays.asList( "武夷山本富村镇银行" ) ),
    WXXVB( Arrays.asList( "威县邢农商村镇银行" ) ),
    WXXJRVB( Arrays.asList( "闻喜县晋融村镇银行" ) ),
    WSQMSVB( Arrays.asList( "乌审旗蒙商村镇银行" ) ),
    WRXHMVB( Arrays.asList( "万荣县汇民村镇银行" ) ),
    WNTLNVB( Arrays.asList( "翁牛特立农村镇银行" ) ),
    WJQGMVB( Arrays.asList( "五家渠国民村镇银行" ) ),
    WFDZXVB( Arrays.asList( "瓦房店长兴村镇银行" ) ),
    WAXHMVB( Arrays.asList( "文安县惠民村镇银行" ) ),
    TZXHDVB( Arrays.asList( "天镇县河东村镇银行" ) ),
    TSCVB( Arrays.asList( "通山楚农商村镇银行" ) ),
    TMGJHVB( Arrays.asList( "铁门关津汇村镇银行" ) ),
    TJSJZVB( Arrays.asList( "天津市蓟州村镇银行" ) ),
    TJSBCVB( Arrays.asList( "天津市北辰村镇银行" ) ),
    TFCVB( Arrays.asList( "团风楚农商村镇银行" ) ),
    TDBBWVB( Arrays.asList( "田东北部湾村镇银行" ) ),
    TAHVB( Arrays.asList( "泰安沪农商村镇银行" ) ),
    SZWMYVB( Arrays.asList( "四子王蒙银村镇银行" ) ),
    SYXTXVB( Arrays.asList( "山阴县太行村镇银行" ) ),
    SYXHDVB( Arrays.asList( "寿阳县汇都村镇银行" ) ),
    SXCVB( Arrays.asList( "随县楚农商村镇银行" ) ),
    SWCTHVB( Arrays.asList( "邵武刺桐红村镇银行" ) ),
    SSCVB( Arrays.asList( "石首楚农商村镇银行" ) ),
    SNCTHVB( Arrays.asList( "寿宁刺桐红村镇银行" ) ),
    SHZGMVB( Arrays.asList( "石河子国民村镇银行" ) ),
    SGZVB( Arrays.asList( "寿光张农商村镇银行" ) ),
    SFHVB( Arrays.asList( "双峰沪农商村镇银行" ) ),
    SCXHDVB( Arrays.asList( "神池县河东村镇银行" ) ),
    RLHVB( Arrays.asList( "瑞丽沪农商村镇银行" ) ),
    RCXVB( Arrays.asList( "容城邢农商村镇银行" ) ),
    QYXZQVB( Arrays.asList( "沁源县长青村镇银行" ) ),
    QWXXTVB( Arrays.asList( "曲沃县新田村镇银行" ) ),
    QGXYGVB( Arrays.asList( "前郭县阳光村镇银行" ) ),
    QCXJCVB( Arrays.asList( "庆城县金城村镇银行" ) ),
    PYXJRVB( Arrays.asList( "平遥县晋融村镇银行" ) ),
    PNCTHVB( Arrays.asList( "屏南刺桐红村镇银行" ) ),
    PLXHDVB( Arrays.asList( "平陆县河东村镇银行" ) ),
    PDXCDVB( Arrays.asList( "平定县昌都村镇银行" ) ),
    NYHVB( Arrays.asList( "宁阳沪农商村镇银行" ) ),
    NXHVB( Arrays.asList( "宁乡沪农商村镇银行" ) ),
    NWXRDVB( Arrays.asList( "宁武县瑞都村镇银行" ) ),
    NBXZCVB( Arrays.asList( "南部县中成村镇银行" ) ),
    MZHVB( Arrays.asList( "蒙自沪农商村镇银行" ) ),
    MLHVB( Arrays.asList( "弥勒沪农商村镇银行" ) ),
    MHKMSVB( Arrays.asList( "梅河口民生村镇银行" ) ),
    LYXXTVB( Arrays.asList( "临猗县新田村镇银行" ) ),
    LYXVB( Arrays.asList( "隆尧邢农商村镇银行" ) ),
    LYHVB( Arrays.asList( "涟源沪农商村镇银行" ) ),
    LXHVB( Arrays.asList( "澧县沪农商村镇银行" ) ),
    LTXJCVB( Arrays.asList( "临洮县金城村镇银行" ) ),
    LTCVB( Arrays.asList( "罗田楚农商村镇银行" ) ),
    LSXHMVB( Arrays.asList( "灵石县汇民村镇银行" ) ),
    LQXZQVB( Arrays.asList( "灵丘县长青村镇银行" ) ),
    LQHVB( Arrays.asList( "临清沪农商村镇银行" ) ),
    LNTZHVB( Arrays.asList( "辽宁太子河村镇银行" ) ),
    LFXSHVB( Arrays.asList( "娄烦县三禾村镇银行" ) ),
    LDLPSVB( Arrays.asList( "隆德六盘山村镇银行" ) ),
    LCXTXVB( Arrays.asList( "陵川县太行村镇银行" ) ),
    LCHVB( Arrays.asList( "聊城沪农商村镇银行" ) ),
    KYXYSVB( Arrays.asList( "开原象牙山村镇银行" ) ),
    KYHVB( Arrays.asList( "开远沪农商村镇银行" ) ),
    KLQYLVB( Arrays.asList( "喀喇沁玉龙村镇银行" ) ),
    KFXDFVB( Arrays.asList( "开封新东方村镇银行" ) ),
    JXSHDVB( Arrays.asList( "介休市华都村镇银行" ) ),
    JSXHDVB( Arrays.asList( "稷山县河东村镇银行" ) ),
    JSHVB( Arrays.asList( "建水沪农商村镇银行" ) ),
    JSHJHVB( Arrays.asList( "江苏邗江合村镇银行" ) ),
    JNCTHVB( Arrays.asList( "建宁刺桐红村镇银行" ) ),
    JLCVB( Arrays.asList( "江陵楚农商村镇银行" ) ),
    JKXRDVB( Arrays.asList( "交口县融都村镇银行" ) ),
    JGSJYVB( Arrays.asList( "井冈山九银村镇银行" ) ),
    JCXTXVB( Arrays.asList( "交城县太行村镇银行" ) ),
    HYXHRVB( Arrays.asList( "浑源县慧融村镇银行" ) ),
    HTBJHVB( Arrays.asList( "呼图壁津汇村镇银行" ) ),
    HSXJCVB( Arrays.asList( "合水县金城村镇银行" ) ),
    HSXGDVB( Arrays.asList( "和顺县贵都村镇银行" ) ),
    HMSTXVB( Arrays.asList( "侯马市太行村镇银行" ) ),
    HLDGXVB( Arrays.asList( "葫芦岛国信村镇银行" ) ),
    HJSLDVB( Arrays.asList( "河津市龙都村镇银行" ) ),
    HGXJRVB( Arrays.asList( "壶关县晋融村镇银行" ) ),
    HEBXFVB( Arrays.asList( "哈尔滨幸福村镇银行" ) ),
    HEBNXVB( Arrays.asList( "哈尔滨农信村镇银行" ) ),
    HEBBZVB( Arrays.asList( "哈尔滨宾洲村镇银行" ) ),
    HDXHDVB( Arrays.asList( "洪洞县洪都村镇银行" ) ),
    GZLPFVB( Arrays.asList( "公主岭浦发村镇银行" ) ),
    GZLHXVB( Arrays.asList( "公主岭华兴村镇银行" ) ),
    GZCTHVB( Arrays.asList( "光泽刺桐红村镇银行" ) ),
    GYSGSVB( Arrays.asList( "广元市贵商村镇银行" ) ),
    GYSFZVB( Arrays.asList( "广元市发展村镇银行" ) ),
    GYHVB( Arrays.asList( "桂阳沪农商村镇银行" ) ),
    GTCTHVB( Arrays.asList( "古田刺桐红村镇银行" ) ),
    GSCVB( Arrays.asList( "广水楚农商村镇银行" ) ),
    GPSTXVB( Arrays.asList( "高平市太行村镇银行" ) ),
    GJSHZVB( Arrays.asList( "古交市汇泽村镇银行" ) ),
    GJSFMVB( Arrays.asList( "古交市阜民村镇银行" ) ),
    GJHVB( Arrays.asList( "个旧沪农商村镇银行" ) ),
    GBDZCVB( Arrays.asList( "高碑店中成村镇银行" ) ),
    FZXXTVB( Arrays.asList( "繁峙县新田村镇银行" ) ),
    FYSJDVB( Arrays.asList( "汾阳市九都村镇银行" ) ),
    FXXYTVB( Arrays.asList( "汾西县亿通村镇银行" ) ),
    FXXTXVB( Arrays.asList( "汾西县太行村镇银行" ) ),
    FXCVB( Arrays.asList( "房县楚农商村镇银行" ) ),
    FSSQYVB( Arrays.asList( "抚顺市清原村镇银行" ) ),
    EWKMSVB( Arrays.asList( "鄂温克蒙商村镇银行" ) ),
    EMSZCVB( Arrays.asList( "峨眉山中成村镇银行" ) ),
    DWCVB( Arrays.asList( "大悟楚农商村镇银行" ) ),
    DLJZFVB( Arrays.asList( "大连金州丰村镇银行" ) ),
    DJYJDVB( Arrays.asList( "都江堰金都村镇银行" ) ),
    DHSJSVB( Arrays.asList( "敦煌市金盛村镇银行" ) ),
    CYCVB( Arrays.asList( "崇阳楚农商村镇银行" ) ),
    CPHVB( Arrays.asList( "茌平沪农商村镇银行" ) ),
    CLHVB( Arrays.asList( "慈利沪农商村镇银行" ) ),
    CDXHSVB( Arrays.asList( "承德县恒升村镇银行" ) ),
    BYBBWVB( Arrays.asList( "宾阳北部湾村镇银行" ) ),
    BKCVB( Arrays.asList( "保康楚农商村镇银行" ) ),
    ALEJHVB( Arrays.asList( "阿拉尔津汇村镇银行" ) ),
    ALCVB( Arrays.asList( "安陆楚农商村镇银行" ) ),
    AHSXHVB( Arrays.asList( "安徽寿县合村镇银行" ) ),
    AHHSHVB( Arrays.asList( "安徽霍山合村镇银行" ) ),
    AHHQHVB( Arrays.asList( "安徽霍邱合村镇银行" ) ),
    ZYXPZZVB( Arrays.asList( "遵义新蒲长征村镇银行" ) ),
    ZYHCQXVB( Arrays.asList( "遵义汇川黔兴村镇银行" ) ),
    ZYBZHLVB( Arrays.asList( "遵义播州汇隆村镇银行" ) ),
    ZQZXCZVB( Arrays.asList( "重庆忠县稠州村镇银行" ) ),
    ZQYYHFVB( Arrays.asList( "重庆云阳恒丰村镇银行" ) ),
    ZQYBYZVB( Arrays.asList( "重庆渝北银座村镇银行" ) ),
    ZQYCBYVB( Arrays.asList( "重庆永川北银村镇银行" ) ),
    ZQXSBYVB( Arrays.asList( "重庆秀山北银村镇银行" ) ),
    ZQTLPFVB( Arrays.asList( "重庆铜梁浦发村镇银行" ) ),
    ZQRCHFVB( Arrays.asList( "重庆荣昌汇丰村镇银行" ) ),
    ZQQJYZVB( Arrays.asList( "重庆黔江银座村镇银行" ) ),
    ZQPSMTVB( Arrays.asList( "重庆彭水民泰村镇银行" ) ),
    ZQNCSYVB( Arrays.asList( "重庆南川石银村镇银行" ) ),
    ZQLPAXVB( Arrays.asList( "重庆梁平澳新村镇银行" ) ),
    ZQKZTYVB( Arrays.asList( "重庆开州泰业村镇银行" ) ),
    ZQJJSYVB( Arrays.asList( "重庆江津石银村镇银行" ) ),
    ZQJBHFVB( Arrays.asList( "重庆江北恒丰村镇银行" ) ),
    ZSGZNYVB( Arrays.asList( "中山古镇南粤村镇银行" ) ),
    ZSDFZJVB( Arrays.asList( "中山东凤珠江村镇银行" ) ),
    ZTZYFDVB( Arrays.asList( "昭通昭阳富滇村镇银行" ) ),
    ZWZYFDVB( Arrays.asList( "长武中银富登村镇银行" ) ),
    ZYZYFDVB( Arrays.asList( "枣阳中银富登村镇银行" ) ),
    YCZYFDVTB( Arrays.asList( "岳池中银富登村镇银行" ) ),
    YSZYFDVBANK( Arrays.asList( "永寿中银富登村镇银行" ) ),
    YSZYFDVTB( Arrays.asList( "颍上中银富登村镇银行" ) ),
    YCZYFDVB( Arrays.asList( "宜城中银富登村镇银行" ) ),
    YSZYFDVB( Arrays.asList( "沂水中银富登村镇银行" ) ),
    XSZYFDVBANK( Arrays.asList( "象山中银富登村镇银行" ) ),
    XSZYFDVB( Arrays.asList( "响水中银富登村镇银行" ) ),
    XSZYFDVTB( Arrays.asList( "习水中银富登村镇银行" ) ),
    WSZYFDVB( Arrays.asList( "武胜中银富登村镇银行" ) ),
    WSZYFDVTB( Arrays.asList( "汶上中银富登村镇银行" ) ),
    THZYFDVTB( Arrays.asList( "泰和中银富登村镇银行" ) ),
    THZYFDVB( Arrays.asList( "太和中银富登村镇银行" ) ),
    QJZYFDVB( Arrays.asList( "全椒中银富登村镇银行" ) ),
    QFZYFDVB( Arrays.asList( "曲阜中银富登村镇银行" ) ),
    QFZYFDVTB( Arrays.asList( "清丰中银富登村镇银行" ) ),
    QJZYFDVTB( Arrays.asList( "潜江中银富登村镇银行" ) ),
    QXZYFDVBANK( Arrays.asList( "乾县中银富登村镇银行" ) ),
    QXZYFDVB( Arrays.asList( "栖霞中银富登村镇银行" ) ),
    LYZYFDVB( Arrays.asList( "鹿邑中银富登村镇银行" ) ),
    LYZYFDVBANK( Arrays.asList( "临颍中银富登村镇银行" ) ),
    LYZYFDVTB( Arrays.asList( "临邑中银富登村镇银行" ) ),
    JSZYFDVB( Arrays.asList( "京山中银富登村镇银行" ) ),
    JSZYFDVTB( Arrays.asList( "界首中银富登村镇银行" ) ),
    JSSYDWVB( Arrays.asList( "江苏宿豫东吴村镇银行" ) ),
    JSSYDWVBANK( Arrays.asList( "江苏泗阳东吴村镇银行" ) ),
    JSSYDWVTB( Arrays.asList( "江苏沭阳东吴村镇银行" ) ),
    VB( Arrays.asList( "村镇银行神农架直管组" ) ),
    ZQFDHFVB( Arrays.asList( "重庆丰都汇丰村镇银行" ) ),
    ZQDZHFVB( Arrays.asList( "重庆大足汇丰村镇银行" ) ),
    ZQBSGYVB( Arrays.asList( "重庆璧山工银村镇银行" ) ),
    ZQBNPFVB( Arrays.asList( "重庆巴南浦发村镇银行" ) ),
    ZQBBCZVB( Arrays.asList( "重庆北碚稠州村镇银行" ) ),
    ZLZYFDVB( Arrays.asList( "镇赉中银富登村镇银行" ) ),
    ZJYKNYVB( Arrays.asList( "浙江永康农银村镇银行" ) ),
    ZJYJHSVB( Arrays.asList( "浙江永嘉恒升村镇银行" ) ),
    ZJYHYXVB( Arrays.asList( "浙江玉环永兴村镇银行" ) ),
    ZJYHDSVB( Arrays.asList( "浙江余杭德商村镇银行" ) ),
    ZJXZDSVB( Arrays.asList( "浙江秀洲德商村镇银行" ) ),
    ZJXJFMVB( Arrays.asList( "浙江仙居富民村镇银行" ) ),
    ZJXCPFVB( Arrays.asList( "浙江新昌浦发村镇银行" ) ),
    ZJWLHVB( Arrays.asList( "浙江温岭联合村镇银行" ) ),
    ZJWCBYVB( Arrays.asList( "浙江文成北银村镇银行" ) ),
    ZJTXMTVB( Arrays.asList( "浙江桐乡民泰村镇银行" ) ),
    ZJTSWYVB( Arrays.asList( "浙江泰顺温银村镇银行" ) ),
    ZJTLHFVB( Arrays.asList( "浙江桐庐恒丰村镇银行" ) ),
    ZJSZRFVB( Arrays.asList( "浙江嵊州瑞丰村镇银行" ) ),
    ZJSYHTVB( Arrays.asList( "浙江松阳恒通村镇银行" ) ),
    ZJSYFMVB( Arrays.asList( "浙江上虞富民村镇银行" ) ),
    ZJSCFMVB( Arrays.asList( "浙江遂昌富民村镇银行" ) ),
    ZJRZZJVB( Arrays.asList( "镇江润州长江村镇银行" ) ),
    ZJRAHSVB( Arrays.asList( "浙江瑞安湖商村镇银行" ) ),
    ZJQYTLVB( Arrays.asList( "浙江庆元泰隆村镇银行" ) ),
    ZJPYPFVB( Arrays.asList( "浙江平阳浦发村镇银行" ) ),
    ZJPJJYVB( Arrays.asList( "浙江浦江嘉银村镇银行" ) ),
    ZJPHGYVB( Arrays.asList( "浙江平湖工银村镇银行" ) ),
    ZJPAWSVB( Arrays.asList( "浙江磐安婺商村镇银行" ) ),
    ZJLYYSVB( Arrays.asList( "浙江龙游义商村镇银行" ) ),
    ZJLXYSVB( Arrays.asList( "浙江兰溪越商村镇银行" ) ),
    ZJLQMTVB( Arrays.asList( "浙江龙泉民泰村镇银行" ) ),
    ZJLQHVB( Arrays.asList( "浙江乐清联合村镇银行" ) ),
    ZJLJZJVB( Arrays.asList( "湛江廉江长江村镇银行" ) ),
    ZJLHHSVB( Arrays.asList( "浙江临海湖商村镇银行" ) ),
    ZJLAZXVB( Arrays.asList( "浙江临安中信村镇银行" ) ),
    ZJKQHVB( Arrays.asList( "浙江柯桥联合村镇银行" ) ),
    ZJJSHVB( Arrays.asList( "浙江嘉善联合村镇银行" ) ),
    ZJJNYZVB( Arrays.asList( "浙江景宁银座村镇银行" ) ),
    ZJJDHSVB( Arrays.asList( "浙江建德湖商村镇银行" ) ),
    ZJHYHSVB( Arrays.asList( "浙江海盐湖商村镇银行" ) ),
    ZJHNDSVB( Arrays.asList( "浙江海宁德商村镇银行" ) ),
    ZJFYHTVB( Arrays.asList( "浙江富阳恒通村镇银行" ) ),
    ZJDYFMVB( Arrays.asList( "浙江东阳富民村镇银行" ) ),
    ZJDTFMVB( Arrays.asList( "浙江洞头富民村镇银行" ) ),
    ZJDSCZVB( Arrays.asList( "浙江岱山稠州村镇银行" ) ),
    ZJDQHSVB( Arrays.asList( "浙江德清湖商村镇银行" ) ),
    ZJDHDSVB( Arrays.asList( "浙江定海德商村镇银行" ) ),
    ZJCSHVB( Arrays.asList( "浙江常山联合村镇银行" ) ),
    ZJAJJYVB( Arrays.asList( "浙江安吉交银村镇银行" ) ),
    ZGEQMSVB( Arrays.asList( "准格尔旗蒙商村镇银行" ) ),
    ZCSYJYVB( Arrays.asList( "长春双阳吉银村镇银行" ) ),
    ZCKCRHVB( Arrays.asList( "长春宽城融汇村镇银行" ) ),
    ZCJYYYVB( Arrays.asList( "长春净月榆银村镇银行" ) ),
    ZCGXHMVB( Arrays.asList( "长春高新惠民村镇银行" ) ),
    ZBZCBHVB( Arrays.asList( "淄博淄川北海村镇银行" ) ),
    ZBBSBHVB( Arrays.asList( "淄博博山北海村镇银行" ) ),
    ZAZYFDVB( Arrays.asList( "正安中银富登村镇银行" ) ),
    YZYZYFVB( Arrays.asList( "扬州仪征玉丰村镇银行" ) ),
    YZGYXFVB( Arrays.asList( "扬州高邮兴福村镇银行" ) ),
    YZGLZCVB( Arrays.asList( "扬州广陵中成村镇银行" ) ),
    YXCJZCVB( Arrays.asList( "玉溪澄江中成村镇银行" ) ),
    YTFSZJVB( Arrays.asList( "烟台福山珠江村镇银行" ) ),
    YQZYFDVB( Arrays.asList( "余庆中银富登村镇银行" ) ),
    YNYJBYVB( Arrays.asList( "云南元江北银村镇银行" ) ),
    YNXSBYVB( Arrays.asList( "云南西山北银村镇银行" ) ),
    YNXPBYVB( Arrays.asList( "云南新平北银村镇银行" ) ),
    YNSPBYVB( Arrays.asList( "云南石屏北银村镇银行" ) ),
    YNMLBYVB( Arrays.asList( "云南马龙北银村镇银行" ) ),
    YNANCZVB( Arrays.asList( "云南安宁稠州村镇银行" ) ),
    YLYYMSVB( Arrays.asList( "榆林榆阳民生村镇银行" ) ),
    YJYCZJVB( Arrays.asList( "阳江阳春长江村镇银行" ) ),
    YJHLLLVB( Arrays.asList( "伊金霍洛六菱村镇银行" ) ),
    YJHLJGVB( Arrays.asList( "伊金霍洛金谷村镇银行" ) ),
    YFZYFDVB( Arrays.asList( "宜丰中银富登村镇银行" ) ),
    YFXXDYVB( Arrays.asList( "云浮新兴东盈村镇银行" ) ),
    YCZZSYVB( Arrays.asList( "银川掌政石银村镇银行" ) ),
    YCYLXFVB( Arrays.asList( "宜昌夷陵兴福村镇银行" ) ),
    YCBHXFVB( Arrays.asList( "盐城滨海兴福村镇银行" ) ),
    YAYCHMVB( Arrays.asList( "雅安雨城惠民村镇银行" ) ),
    XZDLMTVB( Arrays.asList( "西藏堆龙民泰村镇银行" ) ),
    XYZYFDVB( Arrays.asList( "旬邑中银富登村镇银行" ) ),
    XYYSXHVB( Arrays.asList( "新余渝水湘淮村镇银行" ) ),
    XPZYFDVB( Arrays.asList( "兴平中银富登村镇银行" ) ),
    XJLZGMVB( Arrays.asList( "新疆绿洲国民村镇银行" ) ),
    XJJXCGVB( Arrays.asList( "新疆建新成功村镇银行" ) ),
    XGZYFDVB( Arrays.asList( "新干中银富登村镇银行" ) ),
    XCZYFDVB( Arrays.asList( "项城中银富登村镇银行" ) ),
    XAZAXHVB( Arrays.asList( "西安长安新华村镇银行" ) ),
    XAYTHTVB( Arrays.asList( "西安雁塔恒通村镇银行" ) ),
    XAGLYGVB( Arrays.asList( "西安高陵阳光村镇银行" ) ),
    WXZYFDVB( Arrays.asList( "武穴中银富登村镇银行" ) ),
    WXBHXFVB( Arrays.asList( "无锡滨湖兴福村镇银行" ) ),
    WSYSZJVB( Arrays.asList( "文山砚山长江村镇银行" ) ),
    WSQBZJVB( Arrays.asList( "文山丘北长江村镇银行" ) ),
    WSMGZJVB( Arrays.asList( "文山马关长江村镇银行" ) ),
    WSGNZJVB( Arrays.asList( "文山广南长江村镇银行" ) ),
    WSFNZJVB( Arrays.asList( "文山富宁长江村镇银行" ) ),
    WLZYFDVB( Arrays.asList( "五莲中银富登村镇银行" ) ),
    WLDXJYVB( Arrays.asList( "尉犁达西冀银村镇银行" ) ),
    WHSWLTVB( Arrays.asList( "乌海市乌拉特村镇银行" ) ),
    WHJXMSVB( Arrays.asList( "武汉江夏民生村镇银行" ) ),
    WDLCHFVB( Arrays.asList( "五大连池惠丰村镇银行" ) ),
    WCZYFDVB( Arrays.asList( "务川中银富登村镇银行" ) ),
    TZZYFDVB( Arrays.asList( "桐梓中银富登村镇银行" ) ),
    TZJYXZVB( Arrays.asList( "泰州姜堰锡州村镇银行" ) ),
    TZGGXFVB( Arrays.asList( "泰州高港兴福村镇银行" ) ),
    TSQZZYVB( Arrays.asList( "天水秦州长银村镇银行" ) ),
    TSMJRXVB( Arrays.asList( "天水麦积融兴村镇银行" ) ),
    TRWSZZVB( Arrays.asList( "铜仁万山长征村镇银行" ) ),
    TPSQXYVB( Arrays.asList( "太仆寺旗鑫源村镇银行" ) ),
    TKZYFDVB( Arrays.asList( "太康中银富登村镇银行" ) ),
    TJBHYZVB( Arrays.asList( "天津滨海扬子村镇银行" ) ),
    TJBHJHVB( Arrays.asList( "天津滨海江淮村镇银行" ) ),
    TJBHHMVB( Arrays.asList( "天津滨海惠民村镇银行" ) ),
    TJBCPFVB( Arrays.asList( "天津宝坻浦发村镇银行" ) ),
    THDCYYVB( Arrays.asList( "通化东昌榆银村镇银行" ) ),
    TCYZXHVB( Arrays.asList( "铜川耀州新华村镇银行" ) ),
    TCYTHTVB( Arrays.asList( "铜川印台恒通村镇银行" ) ),
    SZZYFDVB( Arrays.asList( "松滋中银富登村镇银行" ) ),
    SZWZZJVB( Arrays.asList( "苏州吴中珠江村镇银行" ) ),
    SZPSZJVB( Arrays.asList( "深圳坪山珠江村镇银行" ) ),
    SZNSBSVB( Arrays.asList( "深圳南山宝生村镇银行" ) ),
    SZLHXHVB( Arrays.asList( "深圳龙华新华村镇银行" ) ),
    SZLHLHVB( Arrays.asList( "深圳罗湖蓝海村镇银行" ) ),
    SZLGDYVB( Arrays.asList( "深圳龙岗鼎业村镇银行" ) ),
    SZBARXVB( Arrays.asList( "深圳宝安融兴村镇银行" ) ),
    SYZYFDVB( Arrays.asList( "沙洋中银富登村镇银行" ) ),
    SYYHYAVB( Arrays.asList( "沈阳于洪永安村镇银行" ) ),
    SYXMFMVB( Arrays.asList( "沈阳新民富民村镇银行" ) ),
    SYSBFMVB( Arrays.asList( "沈阳沈北富民村镇银行" ) ),
    SYNJHMVB( Arrays.asList( "松原宁江惠民村镇银行" ) ),
    SYLZFMVB( Arrays.asList( "沈阳辽中富民村镇银行" ) ),
    SYKPFYVB( Arrays.asList( "沈阳康平抚银村镇银行" ) ),
    SYFKFMVB( Arrays.asList( "沈阳法库富民村镇银行" ) ),
    SXZZNKVB( Arrays.asList( "陕西周至农科村镇银行" ) ),
    SXZSJLVB( Arrays.asList( "陕西柞水聚利村镇银行" ) ),
    SXXYTLVB( Arrays.asList( "陕西旬阳泰隆村镇银行" ) ),
    SXWQHFVB( Arrays.asList( "陕西吴起汇发村镇银行" ) ),
    SXTBZYVB( Arrays.asList( "陕西太白长银村镇银行" ) ),
    SXSYHSVB( Arrays.asList( "陕西三原海丝村镇银行" ) ),
    SXSNJLVB( Arrays.asList( "陕西商南聚利村镇银行" ) ),
    SXQSZYVB( Arrays.asList( "陕西岐山长银村镇银行" ) ),
    SXMXTLVB( Arrays.asList( "陕西眉县泰隆村镇银行" ) ),
    SXLXZYVB( Arrays.asList( "陕西陇县长银村镇银行" ) ),
    SXLTHSVB( Arrays.asList( "陕西临潼海丝村镇银行" ) ),
    SXLNYGVB( Arrays.asList( "陕西洛南阳光村镇银行" ) ),
    SXJYTLVB( Arrays.asList( "陕西泾阳泰隆村镇银行" ) ),
    SXHXHSVB( Arrays.asList( "陕西户县海丝村镇银行" ) ),
    SXFPHFVB( Arrays.asList( "陕西富平汇发村镇银行" ) ),
    STLHZJVB( Arrays.asList( "汕头龙湖长江村镇银行" ) ),
    STCYRHVB( Arrays.asList( "汕头潮阳融和村镇银行" ) ),
    SRZYFDVB( Arrays.asList( "上饶中银富登村镇银行" ) ),
    SQZYFDVB( Arrays.asList( "沈丘中银富登村镇银行" ) ),
    SQSCXFVB( Arrays.asList( "宿迁宿城兴福村镇银行" ) ),
    SPTXDYVB( Arrays.asList( "四平铁西敦银村镇银行" ) ),
    SPTDDFVB( Arrays.asList( "四平铁东德丰村镇银行" ) ),
    SPLHJYVB( Arrays.asList( "四平辽河蛟银村镇银行" ) ),
    SNZYFDVB( Arrays.asList( "睢宁中银富登村镇银行" ) ),
    SNJCVB( Arrays.asList( "神农架楚农商村镇银行" ) ),
    SNAJRXVB( Arrays.asList( "遂宁安居融兴村镇银行" ) ),
    SMXAMSVB( Arrays.asList( "厦门翔安民生村镇银行" ) ),
    SMTANYVB( Arrays.asList( "厦门同安农银村镇银行" ) ),
    SHSJMSVB( Arrays.asList( "上海松江民生村镇银行" ) ),
    SHSJFMVB( Arrays.asList( "上海松江富明村镇银行" ) ),
    SHQPHJVB( Arrays.asList( "上海青浦惠金村镇银行" ) ),
    SHPDJNVB( Arrays.asList( "上海浦东江南村镇银行" ) ),
    SHPDHTVB( Arrays.asList( "上海浦东恒通村镇银行" ) ),
    SHMXSYVB( Arrays.asList( "上海闵行上银村镇银行" ) ),
    SHJSHMVB( Arrays.asList( "上海金山惠民村镇银行" ) ),
    SHJDMSVB( Arrays.asList( "上海嘉定民生村镇银行" ) ),
    SHJDHDVB( Arrays.asList( "上海嘉定洪都村镇银行" ) ),
    SHFXPFVB( Arrays.asList( "上海奉贤浦发村镇银行" ) ),
    SHBSYZVB( Arrays.asList( "上海宝山扬子村镇银行" ) ),
    SHBSFMVB( Arrays.asList( "上海宝山富民村镇银行" ) ),
    SDZPQLVB( Arrays.asList( "山东邹平青隆村镇银行" ) ),
    SDZCQLVB( Arrays.asList( "山东周村青隆村镇银行" ) ),
    SDYNLHVB( Arrays.asList( "山东沂南蓝海村镇银行" ) ),
    SDTCHYVB( Arrays.asList( "山东郯城汉源村镇银行" ) ),
    SDSSQFVB( Arrays.asList( "山东泗水齐丰村镇银行" ) ),
    SDSHHJVB( Arrays.asList( "山东商河汇金村镇银行" ) ),
    SDRCHFVB( Arrays.asList( "山东荣成汇丰村镇银行" ) ),
    SDPYHYVB( Arrays.asList( "山东平邑汉源村镇银行" ) ),
    SDMYQFVB( Arrays.asList( "山东蒙阴齐丰村镇银行" ) ),
    SDLZHJVB( Arrays.asList( "山东临淄汇金村镇银行" ) ),
    SDLSQFVB( Arrays.asList( "山东莱山齐丰村镇银行" ) ),
    SDLSMFVB( Arrays.asList( "山东梁山民丰村镇银行" ) ),
    SDLQJFVB( Arrays.asList( "山东临朐聚丰村镇银行" ) ),
    SDLJSFVB( Arrays.asList( "山东利津舜丰村镇银行" ) ),
    SDLCYRVB( Arrays.asList( "山东历城圆融村镇银行" ) ),
    SDHMSFVB( Arrays.asList( "山东惠民舜丰村镇银行" ) ),
    SDGXQFVB( Arrays.asList( "山东冠县齐丰村镇银行" ) ),
    SDGQHJVB( Arrays.asList( "山东高青汇金村镇银行" ) ),
    SDFCMFVB( Arrays.asList( "山东肥城民丰村镇银行" ) ),
    SDCWHYVB( Arrays.asList( "山东成武汉源村镇银行" ) ),
    SDBXXHVB( Arrays.asList( "山东博兴新华村镇银行" ) ),
    SCYLHMVB( Arrays.asList( "四川仪陇惠民村镇银行" ) ),
    SCMSJCVB( Arrays.asList( "四川名山锦程村镇银行" ) ),
    SCJYHXVB( Arrays.asList( "四川江油华夏村镇银行" ) ),
    QZZYFDVB( Arrays.asList( "青州中银富登村镇银行" ) ),
    QYQXHMVB( Arrays.asList( "清远清新惠民村镇银行" ) ),
    QJZYXFVB( Arrays.asList( "曲靖沾益兴福村镇银行" ) ),
    QJXWZJVB( Arrays.asList( "曲靖宣威长江村镇银行" ) ),
    QJHZZJVB( Arrays.asList( "曲靖会泽长江村镇银行" ) ),
    QJFYFDVB( Arrays.asList( "曲靖富源富滇村镇银行" ) ),
    QHPADTVB( Arrays.asList( "青海平安大通村镇银行" ) ),
    QHMYDTVB( Arrays.asList( "青海门源大通村镇银行" ) ),
    QHLDSJVB( Arrays.asList( "青海乐都三江村镇银行" ) ),
    QHHZSJVB( Arrays.asList( "青海湟中三江村镇银行" ) ),
    QDPDHMVB( Arrays.asList( "青岛平度惠民村镇银行" ) ),
    QDLXYTVB( Arrays.asList( "青岛莱西元泰村镇银行" ) ),
    QDLSJYVB( Arrays.asList( "青岛崂山交银村镇银行" ) ),
    QDJZZCVB( Arrays.asList( "青岛胶州中成村镇银行" ) ),
    QDJMHMVB( Arrays.asList( "青岛即墨惠民村镇银行" ) ),
    QDHDSFVB( Arrays.asList( "青岛黄岛舜丰村镇银行" ) ),
    QDCYZJVB( Arrays.asList( "青岛城阳珠江村镇银行" ) ),
    QCZYFDVB( Arrays.asList( "蕲春中银富登村镇银行" ) ),
    PXZYFDVB( Arrays.asList( "蓬溪中银富登村镇银行" ) ),
    PXXDHHVB( Arrays.asList( "萍乡湘东黄海村镇银行" ) ),
    PXAYFMVB( Arrays.asList( "萍乡安源富民村镇银行" ) ),
    PLKTRXVB( Arrays.asList( "平凉崆峒融兴村镇银行" ) ),
    PCZYFDVB( Arrays.asList( "蒲城中银富登村镇银行" ) ),
    NZZYFDVB( Arrays.asList( "南漳中银富登村镇银行" ) ),
    NXZNQYVB( Arrays.asList( "宁夏中宁青银村镇银行" ) ),
    NXYZJHVB( Arrays.asList( "宁夏原州津汇村镇银行" ) ),
    NXYNHFVB( Arrays.asList( "宁夏永宁汇发村镇银行" ) ),
    NXYCHFVB( Arrays.asList( "宁夏盐池汇发村镇银行" ) ),
    NXXJHFVB( Arrays.asList( "宁夏西吉汇发村镇银行" ) ),
    NXTXJHVB( Arrays.asList( "宁夏同心津汇村镇银行" ) ),
    NXNDBFVB( Arrays.asList( "宁夏宁东本富村镇银行" ) ),
    NXHLHSVB( Arrays.asList( "宁夏贺兰回商村镇银行" ) ),
    NTRGRZVB( Arrays.asList( "南通如皋润泽村镇银行" ) ),
    NNXNZJVB( Arrays.asList( "南宁兴宁长江村镇银行" ) ),
    NNWMLJVB( Arrays.asList( "南宁武鸣漓江村镇银行" ) ),
    NNMSZJVB( Arrays.asList( "南宁马山长江村镇银行" ) ),
    NNLAZJVB( Arrays.asList( "南宁隆安长江村镇银行" ) ),
    NNJNGMVB( Arrays.asList( "南宁江南国民村镇银行" ) ),
    NJPKJFVB( Arrays.asList( "南京浦口靖发村镇银行" ) ),
    NJLHJYVB( Arrays.asList( "南京六合九银村镇银行" ) ),
    NHZYFDVB( Arrays.asList( "宁海中银富登村镇银行" ) ),
    NCXJHTVB( Arrays.asList( "南昌新建恒通村镇银行" ) ),
    NCJLZCVB( Arrays.asList( "南充嘉陵中成村镇银行" ) ),
    NCCDJYVB( Arrays.asList( "南昌昌东九银村镇银行" ) ),
    NBJBFMVB( Arrays.asList( "宁波江北富民村镇银行" ) ),
    NBHSPFVB( Arrays.asList( "宁波海曙浦发村镇银行" ) ),
    NBFHLMVB( Arrays.asList( "宁波奉化罗蒙村镇银行" ) ),
    MTZYFDVB( Arrays.asList( "湄潭中银富登村镇银行" ) ),
    MMGZZJVB( Arrays.asList( "茂名高州长江村镇银行" ) ),
    MMDBZJVB( Arrays.asList( "茂名电白长江村镇银行" ) ),
    MLZYFDVB( Arrays.asList( "汨罗中银富登村镇银行" ) ),
    MLDWMSVB( Arrays.asList( "莫力达瓦蒙商村镇银行" ) ),
    LZYDXHVB( Arrays.asList( "兰州永登新华村镇银行" ) ),
    LZGLXHVB( Arrays.asList( "兰州皋兰新华村镇银行" ) ),
    LZANSZVB( Arrays.asList( "兰州安宁神舟村镇银行" ) ),
    LYLSYYVB( Arrays.asList( "辽源龙山榆银村镇银行" ) ),
    LYHDQSVB( Arrays.asList( "临沂河东齐商村镇银行" ) ),
    LXZYFDVB( Arrays.asList( "临湘中银富登村镇银行" ) ),
    LTZYFDVB( Arrays.asList( "蓝田中银富登村镇银行" ) ),
    LSZYFDVB( Arrays.asList( "邻水中银富登村镇银行" ) ),
    LSJZMFVB( Arrays.asList( "乐山嘉州民富村镇银行" ) ),
    LSJYYSVB( Arrays.asList( "庐山九银艺术村镇银行" ) ),
    LQZYFDVB( Arrays.asList( "临泉中银富登村镇银行" ) ),
    LNZWJTVB( Arrays.asList( "辽宁彰武金通村镇银行" ) ),
    LNYXJYVB( Arrays.asList( "辽宁义县锦银村镇银行" ) ),
    LNTAJAVB( Arrays.asList( "辽宁台安金安村镇银行" ) ),
    LNQSJQVB( Arrays.asList( "辽宁千山金泉村镇银行" ) ),
    LNLHJYVB( Arrays.asList( "辽宁凌海锦银村镇银行" ) ),
    LNKZJYVB( Arrays.asList( "辽宁喀左锦银村镇银行" ) ),
    LNHSJYVB( Arrays.asList( "辽宁黑山锦银村镇银行" ) ),
    LNHRJYVB( Arrays.asList( "辽宁桓仁锦银村镇银行" ) ),
    LNHCJHVB( Arrays.asList( "辽宁海城金海村镇银行" ) ),
    LNCZHTVB( Arrays.asList( "辽宁辰州汇通村镇银行" ) ),
    LNBZJYVB( Arrays.asList( "辽宁北镇锦银村镇银行" ) ),
    LJYSZJVB( Arrays.asList( "丽江永胜长江村镇银行" ) ),
    LJYLZJVB( Arrays.asList( "丽江玉龙长江村镇银行" ) ),
    LJGCFDVB( Arrays.asList( "丽江古城富滇村镇银行" ) ),
    LFLCFDVB( Arrays.asList( "禄丰龙城富滇村镇银行" ) ),
    LCXWLTVB( Arrays.asList( "凉城县乌拉特村镇银行" ) ),
    LBXZZJVB( Arrays.asList( "来宾象州长江村镇银行" ) ),
    LAZYFDVB( Arrays.asList( "来安中银富登村镇银行" ) ),
    KSKTNYVB( Arrays.asList( "克什克腾农银村镇银行" ) ),
    KMXDZCVB( Arrays.asList( "昆明寻甸中成村镇银行" ) ),
    KMWHZJVB( Arrays.asList( "昆明五华长江村镇银行" ) ),
//    KMSLZCVB( Arrays.asList( "昆明石林中成村镇银行" ) ),
//    KMPLXFVB( Arrays.asList( "昆明盘龙兴福村镇银行" ) ),
//    KMLQZCVB( Arrays.asList( "昆明禄劝中成村镇银行" ) ),
//    KMJNRFVB( Arrays.asList( "昆明晋宁融丰村镇银行" ) ),
//    KMDCZCVB( Arrays.asList( "昆明东川中成村镇银行" ) ),
//    KMCGHXVB( Arrays.asList( "昆明呈贡华夏村镇银行" ) ),
//    JZTHJYVB( Arrays.asList( "锦州太和锦银村镇银行" ) ),
//    JZSSVB( Arrays.asList( "锦州松山农商村镇银行" ) ),
//    JYZYFDVB( Arrays.asList( "巨野中银富登村镇银行" ) ),
//    JXZYFDVB( Arrays.asList( "嘉祥中银富登村镇银行" ) ),
//    JXXZJHVB( Arrays.asList( "江西信州江淮村镇银行" ) ),
//    JXXGXHVB( Arrays.asList( "江西兴国新华村镇银行" ) ),
//    JXWZFMVB( Arrays.asList( "江西万载富民村镇银行" ) ),
//    JXWYJHVB( Arrays.asList( "江西婺源江淮村镇银行" ) ),
//    JXSLFMVB( Arrays.asList( "江西上栗富民村镇银行" ) ),
//    JXSGFMVB( Arrays.asList( "江西上高富民村镇银行" ) ),
//    JXRJGDVB( Arrays.asList( "江西瑞金光大村镇银行" ) ),
//    JXLXFMVB( Arrays.asList( "江西芦溪富民村镇银行" ) ),
//    JXLHFMVB( Arrays.asList( "江西莲花富民村镇银行" ) ),
//    JXGAFMVB( Arrays.asList( "江西高安富民村镇银行" ) ),
//    JSXYZJVB( Arrays.asList( "江苏盱眙珠江村镇银行" ) ),
//    JSXYHYVB( Arrays.asList( "江苏新沂汉源村镇银行" ) ),
//    JSTZHSVB( Arrays.asList( "江苏通州华商村镇银行" ) ),
//    JSTSXZVB( Arrays.asList( "江苏铜山锡州村镇银行" ) ),
//    JSSYTSVB( Arrays.asList( "江苏射阳太商村镇银行" ) ),
//    JSSHDWVB( Arrays.asList( "江苏泗洪东吴村镇银行" ) ),
//    JSRDRXVB( Arrays.asList( "江苏如东融兴村镇银行" ) ),
//    JSQDZJVB( Arrays.asList( "江苏启东珠江村镇银行" ) ),
//    JSPZLHVB( Arrays.asList( "江苏邳州陇海村镇银行" ) ),
//    JSPXHYVB( Arrays.asList( "江苏沛县汉源村镇银行" ) ),
//    JSLSTSVB( Arrays.asList( "江苏涟水太商村镇银行" ) ),
//    JSLSMFVB( Arrays.asList( "江苏溧水民丰村镇银行" ) ),
//    JSJNSYVB( Arrays.asList( "江苏江宁上银村镇银行" ) ),
//    JSJJRFVB( Arrays.asList( "江苏靖江润丰村镇银行" ) ),
//    JSJDJYVB( Arrays.asList( "江苏江都吉银村镇银行" ) ),
//    JSHSMTVB( Arrays.asList( "江苏惠山民泰村镇银行" ) ),
//    JSHJMTVB( Arrays.asList( "江苏邗江民泰村镇银行" ) ),
//    JSHAYHVB( Arrays.asList( "江苏海安盐海村镇银行" ) ),
//    JSHAGDVB( Arrays.asList( "江苏淮安光大村镇银行" ) ),
//    JSGYTSVB( Arrays.asList( "江苏赣榆通商村镇银行" ) ),
//    JSGYMFVB( Arrays.asList( "江苏灌云民丰村镇银行" ) ),
//    JSGNMFVB( Arrays.asList( "江苏灌南民丰村镇银行" ) ),
//    JSFXMFVB( Arrays.asList( "江苏丰县民丰村镇银行" ) ),
//    JSDYSYVB( Arrays.asList( "江苏丹阳苏银村镇银行" ) ),
//    JSDTMYVB( Arrays.asList( "江苏丹徒蒙银村镇银行" ) ),
//    JSDTCZVB( Arrays.asList( "江苏东台稠州村镇银行" ) ),
//    JSDFJNVB( Arrays.asList( "江苏大丰江南村镇银行" ) ),
//    JSBYJCVB( Arrays.asList( "江苏宝应锦程村镇银行" ) ),
//    JNGXBHVB( Arrays.asList( "济南高新北海村镇银行" ) ),
//    JMXHXHVB( Arrays.asList( "江门新会新华村镇银行" ) ),
//    JMKPZJVB( Arrays.asList( "江门开平长江村镇银行" ) ),
//    JMDBHMVB( Arrays.asList( "荆门东宝惠民村镇银行" ) ),
//    JLZYFDVB( Arrays.asList( "监利中银富登村镇银行" ) ),
//    JLLTHYVB( Arrays.asList( "吉林龙潭华益村镇银行" ) ),
//    JLFMHMVB( Arrays.asList( "吉林丰满惠民村镇银行" ) ),
//    JLCYYYVB( Arrays.asList( "吉林昌邑榆银村镇银行" ) ),
//    JLCYHMVB( Arrays.asList( "吉林船营惠民村镇银行" ) ),
//    JJLSXYVB( Arrays.asList( "九江庐山浔银村镇银行" ) ),
//    HZZKDYVB( Arrays.asList( "惠州仲恺东盈村镇银行" ) ),
//    HZMDBHVB( Arrays.asList( "菏泽牡丹北海村镇银行" ) ),
//    HZBLZJVB( Arrays.asList( "惠州博罗长江村镇银行" ) ),
//    HZBBDYVB( Arrays.asList( "贺州八步东盈村镇银行" ) ),
//    HYZYFDVB( Arrays.asList( "淮阳中银富登村镇银行" ) ),
//    HYXHVB( Arrays.asList( "衡阳县沪农商村镇银行" ) ),
//    HXZYFDVB( Arrays.asList( "滑县中银富登村镇银行" ) ),
//    HSJZFYVB( Arrays.asList( "衡水冀州丰源村镇银行" ) ),
//    HNZJXJVB( Arrays.asList( "湖南芷江湘江村镇银行" ) ),
//    HNZFXYVB( Arrays.asList( "湖南中方新阳村镇银行" ) ),
//    HNYYXJVB( Arrays.asList( "湖南岳阳湘江村镇银行" ) ),
//    HNYXTLVB( Arrays.asList( "河南叶县泰隆村镇银行" ) ),
//    HNYLXYVB( Arrays.asList( "湖南沅陵新阳村镇银行" ) ),
//    HNYLXLVB( Arrays.asList( "湖南炎陵星龙村镇银行" ) ),
//    HNXYXLVB( Arrays.asList( "湖南湘阴星龙村镇银行" ) ),
//    HNXTXNVB( Arrays.asList( "湖南新田湘农村镇银行" ) ),
//    HNXTXHVB( Arrays.asList( "湖南湘潭湘淮村镇银行" ) ),
//    HNXSXHVB( Arrays.asList( "湖南新邵湘淮村镇银行" ) ),
//    HNXPXJVB( Arrays.asList( "湖南溆浦湘江村镇银行" ) ),
//    HNXHXLVB( Arrays.asList( "湖南新化星龙村镇银行" ) ),
//    HNTYXHVB( Arrays.asList( "湖南桃源湘淮村镇银行" ) ),
//    HNSZXNVB( Arrays.asList( "湖南桑植湘农村镇银行" ) ),
//    HNSYXJVB( Arrays.asList( "湖南邵阳湘江村镇银行" ) ),
//    HNSPXNVB( Arrays.asList( "湖南双牌湘农村镇银行" ) ),
//    HNSNXNVB( Arrays.asList( "湖南绥宁湘农村镇银行" ) ),
//    HNSDXHVB( Arrays.asList( "湖南邵东湘淮村镇银行" ) ),
//    HNRNTLVB( Arrays.asList( "河南汝南泰隆村镇银行" ) ),
//    HNRCXYVB( Arrays.asList( "湖南汝城新阳村镇银行" ) ),
//    HNQZZJVB( Arrays.asList( "海南琼中长江村镇银行" ) ),
//    HNQYJNVB( Arrays.asList( "河南沁阳江南村镇银行" ) ),
//    HNPJHFVB( Arrays.asList( "湖南平江汇丰村镇银行" ) ),
//    HNNXXJVB( Arrays.asList( "湖南南县湘江村镇银行" ) ),
//    HNLYJHVB( Arrays.asList( "湖南浏阳江淮村镇银行" ) ),
//    HNLSSNVB( Arrays.asList( "湖南蓝山神农村镇银行" ) ),
//    HNLHXJVB( Arrays.asList( "湖南隆回湘江村镇银行" ) ),
//    HNLCMFVB( Arrays.asList( "河南栾川民丰村镇银行" ) ),
//    HNJYXNVB( Arrays.asList( "湖南江永湘农村镇银行" ) ),
//    HNJSXHVB( Arrays.asList( "湖南津市湘淮村镇银行" ) ),
//    HNJHXYVB( Arrays.asList( "湖南江华新阳村镇银行" ) ),
//    HNJHXLVB( Arrays.asList( "湖南嘉禾星龙村镇银行" ) ),
//    HNHSXLVB( Arrays.asList( "湖南汉寿星龙村镇银行" ) ),
//    HNHRXLVB( Arrays.asList( "湖南华容星龙村镇银行" ) ),
//    HNHJXNVB( Arrays.asList( "湖南洪江湘农村镇银行" ) ),
//    HNHDXYVB( Arrays.asList( "湖南衡东新阳村镇银行" ) ),
//    HNGDXLVB( Arrays.asList( "湖南桂东星龙村镇银行" ) ),
//    HNFCFYVB( Arrays.asList( "河南方城凤裕村镇银行" ) ),
//    HNDZLSVB( Arrays.asList( "海南儋州绿色村镇银行" ) ),
//    HNDXSNVB( Arrays.asList( "湖南道县神农村镇银行" ) ),
//    HNDAXLVB( Arrays.asList( "湖南东安星龙村镇银行" ) ),
//    HNCMZJVB( Arrays.asList( "海南澄迈长江村镇银行" ) ),
//    HNCJZJVB( Arrays.asList( "海南昌江长江村镇银行" ) ),
//    HNCBXNVB( Arrays.asList( "湖南城步湘农村镇银行" ) ),
//    HNBTRXVB( Arrays.asList( "海南保亭融兴村镇银行" ) ),
//    HNBSZJVB( Arrays.asList( "海南白沙长江村镇银行" ) ),
//    HNARXYVB( Arrays.asList( "湖南安仁新阳村镇银行" ) ),
//    HNAHXHVB( Arrays.asList( "湖南安化湘淮村镇银行" ) ),
//    HMZYFDVB( Arrays.asList( "黄梅中银富登村镇银行" ) ),
//    HMHXGMVB( Arrays.asList( "哈密红星国民村镇银行" ) ),
//    HLGLMYVB( Arrays.asList( "霍林郭勒蒙银村镇银行" ) ),
//    HJHQHTVB( Arrays.asList( "杭锦后旗河套村镇银行" ) ),
//    HDYNQLVB( Arrays.asList( "邯郸永年齐鲁村镇银行" ) ),
//    HDHSQLVB( Arrays.asList( "邯郸邯山齐鲁村镇银行" ) ),
//    HDFXHSVB( Arrays.asList( "邯郸肥乡恒升村镇银行" ) ),
//    HBYSZJVB( Arrays.asList( "湖北英山长江村镇银行" ) ),
//    HBXAZJVB( Arrays.asList( "湖北咸安长江村镇银行" ) ),
//    HBTMHFVB( Arrays.asList( "湖北天门汇丰村镇银行" ) ),
//    HBMCHFVB( Arrays.asList( "湖北麻城汇丰村镇银行" ) ),
//    HBJYWJVB( Arrays.asList( "湖北嘉鱼吴江村镇银行" ) ),
//    HBHCNYVB( Arrays.asList( "湖北汉川农银村镇银行" ) ),
//    HBHAZJVB( Arrays.asList( "湖北红安长江村镇银行" ) ),
//    HBCBZJVB( Arrays.asList( "湖北赤壁长江村镇银行" ) ),
//    HAQPXFVB( Arrays.asList( "淮安清浦兴福村镇银行" ) ),
//    HAQHXFVB( Arrays.asList( "淮安清河兴福村镇银行" ) ),
//    HAHYXFVB( Arrays.asList( "淮安淮阴兴福村镇银行" ) ),
//    GZHPRHVB( Arrays.asList( "广州黄埔融和村镇银行" ) ),
//    GZHPHMVB( Arrays.asList( "广州黄埔惠民村镇银行" ) ),
//    GZFYXHVB( Arrays.asList( "广州番禺新华村镇银行" ) ),
//    GZCHLYVB( Arrays.asList( "广州从化柳银村镇银行" ) ),
//    GYYYFMVB( Arrays.asList( "贵阳云岩富民村镇银行" ) ),
//    GYXHKJVB( Arrays.asList( "贵阳小河科技村镇银行" ) ),
//    GYWDFMVB( Arrays.asList( "贵阳乌当富民村镇银行" ) ),
//    GYNMFMVB( Arrays.asList( "贵阳南明富民村镇银行" ) ),
//    GYHXJSVB( Arrays.asList( "贵阳花溪建设村镇银行" ) ),
//    GXYFXHVB( Arrays.asList( "广西鱼峰信合村镇银行" ) ),
//    GXXYLYVB( Arrays.asList( "广西兴业柳银村镇银行" ) ),
//    GXXAMXVB( Arrays.asList( "广西兴安民兴村镇银行" ) ),
//    GXTXGYVB( Arrays.asList( "广西藤县桂银村镇银行" ) ),
//    GXSLGMVB( Arrays.asList( "广西上林国民村镇银行" ) ),
//    GXRXGYVB( Arrays.asList( "广西容县桂银村镇银行" ) ),
//    GXRSLYVB( Arrays.asList( "广西融水柳银村镇银行" ) ),
//    GXPNGYVB( Arrays.asList( "广西平南桂银村镇银行" ) ),
//    GXPBGMVB( Arrays.asList( "广西浦北国民村镇银行" ) ),
//    GXLJLYVB( Arrays.asList( "广西柳江柳银村镇银行" ) ),
//    GXLCLYVB( Arrays.asList( "广西陆川柳银村镇银行" ) ),
//    GXHXGSVB( Arrays.asList( "广西横县桂商村镇银行" ) ),
//    GXGPGYVB( Arrays.asList( "广西桂平桂银村镇银行" ) ),
//    GXBLLYVB( Arrays.asList( "广西北流柳银村镇银行" ) ),
//    GXBBLYVB( Arrays.asList( "广西博白柳银村镇银行" ) ),
//    GSXGJCVB( Arrays.asList( "甘肃西固金城村镇银行" ) ),
//    GDYDTLVB( Arrays.asList( "广东英德泰隆村镇银行" ) ),
//    GDSHTLVB( Arrays.asList( "广东四会泰隆村镇银行" ) ),
//    GDEPHFVB( Arrays.asList( "广东恩平汇丰村镇银行" ) ),
//    GDCHCSVB( Arrays.asList( "广东澄海潮商村镇银行" ) ),
//    GCZYFDVB( Arrays.asList( "谷城中银富登村镇银行" ) ),
//    GAZYFDVB( Arrays.asList( "公安中银富登村镇银行" ) ),
//    GAXQFZVB( Arrays.asList( "贵安新区发展村镇银行" ) ),
//    FZDXFMVB( Arrays.asList( "抚州东乡富民村镇银行" ) ),
//    FXZYFDVB( Arrays.asList( "凤翔中银富登村镇银行" ) ),
//    FSXBFYVB( Arrays.asList( "抚顺新宾抚银村镇银行" ) ),
//    FSWHFYVB( Arrays.asList( "抚顺望花抚银村镇银行" ) ),
//    FSSCFYVB( Arrays.asList( "抚顺顺城抚银村镇银行" ) ),
//    FSNHXHVB( Arrays.asList( "佛山南海新华村镇银行" ) ),
//    FSGMSYVB( Arrays.asList( "佛山高明顺银村镇银行" ) ),
//    FSDZFYVB( Arrays.asList( "抚顺东洲抚银村镇银行" ) ),
//    FNZYFDVB( Arrays.asList( "阜南中银富登村镇银行" ) ),
//    FJZPMTVB( Arrays.asList( "福建漳平民泰村镇银行" ) ),
//    FJZLTLVB( Arrays.asList( "福建长乐泰隆村镇银行" ) ),
//    FJZHTLVB( Arrays.asList( "福建政和泰隆村镇银行" ) ),
//    FJZAHTVB( Arrays.asList( "福建诏安汇通村镇银行" ) ),
//    FJYXCGVB( Arrays.asList( "福建尤溪成功村镇银行" ) ),
//    FJYTZXVB( Arrays.asList( "福建永泰长信村镇银行" ) ),
//    FJYDRSVB( Arrays.asList( "福建永定瑞狮村镇银行" ) ),
//    FJYAHFVB( Arrays.asList( "福建永安汇丰村镇银行" ) ),
//    FJXYRSVB( Arrays.asList( "福建仙游瑞狮村镇银行" ) ),
//    FJWPHXVB( Arrays.asList( "福建武平杭兴村镇银行" ) ),
//    FJSXZXVB( Arrays.asList( "福建松溪长信村镇银行" ) ),
//    FJNHCGVB( Arrays.asList( "福建宁化成功村镇银行" ) ),
//    FJNAHTVB( Arrays.asList( "福建南安汇通村镇银行" ) ),
//    FJMQRSVB( Arrays.asList( "福建闽清瑞狮村镇银行" ) ),
//    FJMHMBVB( Arrays.asList( "福建闽侯民本村镇银行" ) ),
//    FJLYHRVB( Arrays.asList( "福建罗源汇融村镇银行" ) ),
//    FJLHTLVB( Arrays.asList( "福建龙海泰隆村镇银行" ) ),
//    FJLCHXVB( Arrays.asList( "福建连城杭兴村镇银行" ) ),
//    FJJYRSVB( Arrays.asList( "福建建阳瑞狮村镇银行" ) ),
//    FJJORSVB( Arrays.asList( "福建建瓯瑞狮村镇银行" ) ),
//    FJJLCGVB( Arrays.asList( "福建将乐成功村镇银行" ) ),
//    FJHAZXVB( Arrays.asList( "福建华安长信村镇银行" ) ),
//    FJFQTLVB( Arrays.asList( "福建福清泰隆村镇银行" ) ),
//    FJFDHXVB( Arrays.asList( "福建福鼎恒兴村镇银行" ) ),
//    FJDHCGVB( Arrays.asList( "福建德化成功村镇银行" ) ),
//    FGZYFDVB( Arrays.asList( "凤冈中银富登村镇银行" ) ),
//    ETKXSYVB( Arrays.asList( "鄂托克兴生源村镇银行" ) ),
//    ETKQHZVB( Arrays.asList( "鄂托克旗汇泽村镇银行" ) ),
//    DZZYFDVB( Arrays.asList( "道真中银富登村镇银行" ) ),
//    DZLCYRVB( Arrays.asList( "德州陵城圆融村镇银行" ) ),
//    DYZYFDVB( Arrays.asList( "大冶中银富登村镇银行" ) ),
//    DYJYXMVB( Arrays.asList( "大邑交银兴民村镇银行" ) ),
//    DYHKZCVB( Arrays.asList( "东营河口中成村镇银行" ) ),
//    DXZYFDVB( Arrays.asList( "单县中银富登村镇银行" ) ),
//    DTZYFDVB( Arrays.asList( "大通中银富登村镇银行" ) ),
//    DMZYFDVB( Arrays.asList( "东明中银富登村镇银行" ) ),
//    DLWSZJVB( Arrays.asList( "大理巍山长江村镇银行" ) ),
//    DLGCZCVB( Arrays.asList( "大理古城中成村镇银行" ) ),
//    DLEYZJVB( Arrays.asList( "大理洱源长江村镇银行" ) ),
//    DLBCZJVB( Arrays.asList( "大理宾川长江村镇银行" ) ),
//    DJKCVB( Arrays.asList( "丹江口楚农商村镇银行" ) ),
//    DHMSZJVB( Arrays.asList( "德宏芒市长江村镇银行" ) ),
//    DGHMZJVB( Arrays.asList( "东莞虎门长江村镇银行" ) ),
//    DGHJZJVB( Arrays.asList( "东莞黄江珠江村镇银行" ) ),
//    DGHJHYVB( Arrays.asList( "东莞厚街华业村镇银行" ) ),
//    DGDLDYVB( Arrays.asList( "东莞大朗东盈村镇银行" ) ),
//    DGCPXHVB( Arrays.asList( "东莞常平新华村镇银行" ) ),
//    DEBTRSVB( Arrays.asList( "杜尔伯特润生村镇银行" ) ),
//    DCZYFDVB( Arrays.asList( "郸城中银富登村镇银行" ) ),
//    CZZLZJVB( Arrays.asList( "常州钟楼长江村镇银行" ) ),
//    CZYSXHVB( Arrays.asList( "沧州盐山新华村镇银行" ) ),
//    CZXBZCVB( Arrays.asList( "常州新北中成村镇银行" ) ),
//    CZJTXFVB( Arrays.asList( "常州金坛兴福村镇银行" ) ),
//    CZHXXHVB( Arrays.asList( "沧州海兴新华村镇银行" ) ),
//    CZGCMSVB( Arrays.asList( "池州贵池民生村镇银行" ) ),
//    CZDXZJVB( Arrays.asList( "崇左大新长江村镇银行" ) ),
//    CZCAZJVB( Arrays.asList( "潮州潮安长江村镇银行" ) ),
//    CXZYFDVB( Arrays.asList( "曹县中银富登村镇银行" ) ),
//    CXSBBWVB( Arrays.asList( "岑溪市北部湾村镇银行" ) ),
//    CSZYFDVB( Arrays.asList( "赤水中银富登村镇银行" ) ),
//    CHZYFDVB( Arrays.asList( "淳化中银富登村镇银行" ) ),
//    CGZYFDVB( Arrays.asList( "城固中银富登村镇银行" ) ),
//    CDSLCMVB( Arrays.asList( "成都双流诚民村镇银行" ) ),
//    BZZYFDVB( Arrays.asList( "巴中中银富登村镇银行" ) ),
//    BTQSHTVB( Arrays.asList( "包头青山河套村镇银行" ) ),
//    BSYJHRVB( Arrays.asList( "百色右江华润村镇银行" ) ),
//    BSSDZJVB( Arrays.asList( "保山施甸长江村镇银行" ) ),
//    BSLLZJVB( Arrays.asList( "保山龙陵长江村镇银行" ) ),
//    BSJYHHVB( Arrays.asList( "白山江源汇恒村镇银行" ) ),
//    BSJXZJVB( Arrays.asList( "百色靖西长江村镇银行" ) ),
//    BSHJHTVB( Arrays.asList( "白山浑江恒泰村镇银行" ) ),
//    BSCNZJVB( Arrays.asList( "保山昌宁长江村镇银行" ) ),
//    BJPGXHVB( Arrays.asList( "北京平谷新华村镇银行" ) ),
//    BJMYHFVB( Arrays.asList( "北京密云汇丰村镇银行" ) ),
//    BJHRRXVB( Arrays.asList( "北京怀柔融兴村镇银行" ) ),
//    BJDXJYVB( Arrays.asList( "北京大兴九银村镇银行" ) ),
//    BJDXHXVB( Arrays.asList( "北京大兴华夏村镇银行" ) ),
//    BJCPFZVB( Arrays.asList( "北京昌平发展村镇银行" ) ),
//    AXZYFDVB( Arrays.asList( "安乡中银富登村镇银行" ) ),
//    ASXXFMVB( Arrays.asList( "安顺西秀富民村镇银行" ) ),
//    AHZFKYVB( Arrays.asList( "安徽长丰科源村镇银行" ) ),
//    AHYXHSVB( Arrays.asList( "安徽岳西湖商村镇银行" ) ),
//    AHYASPVB( Arrays.asList( "安徽裕安盛平村镇银行" ) ),
//    AHXZHSVB( Arrays.asList( "安徽宣州湖商村镇银行" ) ),
//    AHXNDDVB( Arrays.asList( "安徽休宁大地村镇银行" ) ),
//    AHWYHSVB( Arrays.asList( "安徽涡阳湖商村镇银行" ) ),
//    AHWHYTVB( Arrays.asList( "安徽五河永泰村镇银行" ) ),
//    AHTLTYVB( Arrays.asList( "安徽铜陵铜源村镇银行" ) ),
//    AHTHJHVB( Arrays.asList( "安徽太湖江淮村镇银行" ) ),
//    AHTCJHVB( Arrays.asList( "安徽桐城江淮村镇银行" ) ),
//    AHSZHHVB( Arrays.asList( "安徽宿州淮海村镇银行" ) ),
//    AHSXJYVB( Arrays.asList( "安徽歙县嘉银村镇银行" ) ),
//    AHSXHSVB( Arrays.asList( "安徽濉溪湖商村镇银行" ) ),
//    AHSTYZVB( Arrays.asList( "安徽石台扬子村镇银行" ) ),
//    AHSSMFVB( Arrays.asList( "安徽宿松民丰村镇银行" ) ),
//    AHSCZXVB( Arrays.asList( "安徽舒城正兴村镇银行" ) ),
//    AHQYJHVB( Arrays.asList( "安徽青阳九华村镇银行" ) ),
//    AHQSJHVB( Arrays.asList( "安徽潜山江淮村镇银行" ) ),
//    AHQMTYVB( Arrays.asList( "安徽祁门铜源村镇银行" ) ),
//    AHQCHSVB( Arrays.asList( "安徽谯城湖商村镇银行" ) ),
//    AHMGMFVB( Arrays.asList( "安徽明光民丰村镇银行" ) ),
//    AHMCHSVB( Arrays.asList( "安徽蒙城湖商村镇银行" ) ),
//    AHLXXHVB( Arrays.asList( "安徽郎溪新华村镇银行" ) ),
//    AHLXHSVB( Arrays.asList( "安徽利辛湖商村镇银行" ) ),
//    AHLBBFVB( Arrays.asList( "安徽灵璧本富村镇银行" ) ),
//    AHJZJHVB( Arrays.asList( "安徽金寨江淮村镇银行" ) ),
//    AHJXTYVB( Arrays.asList( "安徽泾县铜源村镇银行" ) ),
//    AHHZTYVB( Arrays.asList( "安徽徽州铜源村镇银行" ) ),
//    AHHYBFVB( Arrays.asList( "安徽怀远本富村镇银行" ) ),
//    AHHXXHVB( Arrays.asList( "安徽和县新华村镇银行" ) ),
//    AHHSJQVB( Arrays.asList( "安徽黄山金桥村镇银行" ) ),
//    AHHNJHVB( Arrays.asList( "安徽怀宁江淮村镇银行" ) ),
//    AHGDYZVB( Arrays.asList( "安徽广德扬子村镇银行" ) ),
//    AHFYLMVB( Arrays.asList( "安徽凤阳利民村镇银行" ) ),
//    AHFXSYVB( Arrays.asList( "安徽肥西石银村镇银行" ) ),
//    AHFTTSVB( Arrays.asList( "安徽凤台通商村镇银行" ) ),
//    AHFDHSVB( Arrays.asList( "安徽肥东湖商村镇银行" ) ),
//    AHDZYZVB( Arrays.asList( "安徽东至扬子村镇银行" ) ),
//    AHDYMFVB( Arrays.asList( "安徽定远民丰村镇银行" ) ),
//    AHDTXHVB( Arrays.asList( "安徽当涂新华村镇银行" ) ),
//    AHCHYZVB( Arrays.asList( "安徽巢湖扬子村镇银行" ) ),
//    AFZYFDVB( Arrays.asList( "安福中银富登村镇银行" ) ),
//    ZYHHGFMVB( Arrays.asList( "遵义红花岗富民村镇银行" ) ),
//    ZQSYYRXVB( Arrays.asList( "重庆市酉阳融兴村镇银行" ) ),
//    ZQSWLRXVB( Arrays.asList( "重庆市武隆融兴村镇银行" ) ),
//    ZZJSSVB( Arrays.asList( "郑州金水厦农商村镇银行" ) ),
//    ZSXSHVB( Arrays.asList( "长沙星沙沪农商村镇银行" ) ),
//    YNXYYVB( Arrays.asList( "云南祥云渝农商村镇银行" ) ),
//    YNXSYVB( Arrays.asList( "云南西山渝农商村镇银行" ) ),
//    YNHQYVB( Arrays.asList( "云南鹤庆渝农商村镇银行" ) ),
//    YNDLYVB( Arrays.asList( "云南大理渝农商村镇银行" ) ),
//    XYKMJCGVB( Arrays.asList( "新余孔目江成功村镇银行" ) ),
//    XJSHZJYVB( Arrays.asList( "新疆石河子交银村镇银行" ) ),
//    XJKELFMVB( Arrays.asList( "新疆库尔勒富民村镇银行" ) ),
//    WLTZQMYVB( Arrays.asList( "乌拉特中旗蒙银村镇银行" ) ),
//    WLTQQDZVB( Arrays.asList( "乌拉特前旗大众村镇银行" ) ),
//    WLMQXLFVB( Arrays.asList( "乌鲁木齐县利丰村镇银行" ) ),
//    WHQLSHTVB( Arrays.asList( "乌海千里山河套村镇银行" ) ),
//    WHDXHYZVB( Arrays.asList( "武汉东西湖扬子村镇银行" ) ),
//    TSSQAZXVB( Arrays.asList( "天水市秦安众信村镇银行" ) ),
//    TSSKPHJVB( Arrays.asList( "唐山市开平汇金村镇银行" ) ),
//    TSSFNSFVB( Arrays.asList( "唐山市丰南舜丰村镇银行" ) ),
//    TMTZQJGVB( Arrays.asList( "土默特左旗金谷村镇银行" ) ),
//    TMTYQMYVB( Arrays.asList( "土默特右旗蒙银村镇银行" ) ),
//    THEDJRFVB( Arrays.asList( "通化二道江瑞丰村镇银行" ) ),
//    SZHRSHRVB( Arrays.asList( "朔州怀仁市慧融村镇银行" ) ),
//    SZGMHVB( Arrays.asList( "深圳光明沪农商村镇银行" ) ),
//    SJZXHHSVB( Arrays.asList( "石家庄新华恒升村镇银行" ) ),
//    SJZLCQLVB( Arrays.asList( "石家庄栾城齐鲁村镇银行" ) ),
//    SHCMHVB( Arrays.asList( "上海崇明沪农商村镇银行" ) ),
//    SCDZYVB( Arrays.asList( "四川大竹渝农商村镇银行" ) ),
//    QXNYLPFVB( Arrays.asList( "黔西南义龙浦发村镇银行" ) ),
//    QHDFNJYVB( Arrays.asList( "秦皇岛抚宁家银村镇银行" ) ),
//    QDXHAHHVB( Arrays.asList( "青岛西海岸海汇村镇银行" ) ),
//    PSXBPJYVB( Arrays.asList( "平山西柏坡冀银村镇银行" ) ),
//    PLSJNCJVB( Arrays.asList( "平凉市静宁成纪村镇银行" ) ),
//    NXXXHLSVB( Arrays.asList( "宁夏西夏贺兰山村镇银行" ) ),
//    NXPYHLSVB( Arrays.asList( "宁夏彭阳贺兰山村镇银行" ) ),
//    NXHSBHFVB( Arrays.asList( "宁夏红寺堡汇发村镇银行" ) ),
//    NXHNHLSVB( Arrays.asList( "宁夏惠农贺兰山村镇银行" ) ),
//    NBSHSGMVB( Arrays.asList( "宁波市海曙国民村镇银行" ) ),
//    LZQLHXHVB( Arrays.asList( "兰州七里河新华村镇银行" ) ),
//    LYXAQYYVB( Arrays.asList( "辽源西安区榆银村镇银行" ) ),
//    LNSWDJQVB( Arrays.asList( "陇南市武都金桥村镇银行" ) ),
//    LHSYCFZVB( Arrays.asList( "漯河市郾城发展村镇银行" ) ),
//    LHKZYFDVB( Arrays.asList( "老河口中银富登村镇银行" ) ),
//    LFSGYSFVB( Arrays.asList( "廊坊市广阳舜丰村镇银行" ) ),
//    LCLXHVB( Arrays.asList( "临沧临翔沪农商村镇银行" ) ),
//    KMMJPZCVB( Arrays.asList( "昆明马金铺中成村镇银行" ) ),
//    KMGDHVB( Arrays.asList( "昆明官渡沪农商村镇银行" ) ),
//    JZSZQHFVB( Arrays.asList( "晋中市左权华丰村镇银行" ) ),
//    JZSYCRXVB( Arrays.asList( "晋中市榆次融信村镇银行" ) ),
//    JZSTGXTVB( Arrays.asList( "晋中市太谷兴泰村镇银行" ) ),
//    JSHZJYGVB( Arrays.asList( "江苏洪泽金阳光村镇银行" ) ),
//    JSDHZVB( Arrays.asList( "江苏东海张农商村镇银行" ) ),
//    JNZQHVB( Arrays.asList( "济南长清沪农商村镇银行" ) ),
//    JDZCJJYVB( Arrays.asList( "景德镇昌江九银村镇银行" ) ),
//    HNYXTVB( Arrays.asList( "湖南攸县潭农商村镇银行" ) ),
//    HNXNTVB( Arrays.asList( "湖南新宁潭农商村镇银行" ) ),
//    HNXHSVB( Arrays.asList( "河南西华厦农商村镇银行" ) ),
//    HNWZSZJVB( Arrays.asList( "海南五指山长江村镇银行" ) ),
//    HNSSSVB( Arrays.asList( "河南商水厦农商村镇银行" ) ),
//    HNNYTVB( Arrays.asList( "湖南宁远潭农商村镇银行" ) ),
//    HNLSJXHVB( Arrays.asList( "湖南冷水江湘淮村镇银行" ) ),
//    HNHSTVB( Arrays.asList( "湖南衡山潭农商村镇银行" ) ),
//    HNDKTVB( Arrays.asList( "湖南洞口潭农商村镇银行" ) ),
//    HEBHLPFVB( Arrays.asList( "哈尔滨呼兰浦发村镇银行" ) ),
//    HEBACVB( Arrays.asList( "哈尔滨阿城农商村镇银行" ) ),
//    GYGSHFMVB( Arrays.asList( "贵阳观山湖富民村镇银行" ) ),
//    GXLZYVB( Arrays.asList( "广西鹿寨渝农商村镇银行" ) ),
//    FJYCZVB( Arrays.asList( "福建永春漳农商村镇银行" ) ),
//    FJXLJVB( Arrays.asList( "福建新罗晋农商村镇银行" ) ),
//    FJSXYVB( Arrays.asList( "福建沙县渝农商村镇银行" ) ),
//    FJSSYVB( Arrays.asList( "福建石狮渝农商村镇银行" ) ),
//    FJPTYVB( Arrays.asList( "福建平潭渝农商村镇银行" ) ),
//    FJJCCTHVB( Arrays.asList( "福建蕉城刺桐红村镇银行" ) ),
//    FJFAYVB( Arrays.asList( "福建福安渝农商村镇银行" ) ),
//    FJDTJVB( Arrays.asList( "福建大田晋农商村镇银行" ) ),
//    FCGFCGMVB( Arrays.asList( "防城港防城国民村镇银行" ) ),
//    ETKQQMYVB( Arrays.asList( "鄂托克前旗蒙银村镇银行" ) ),
//    EEDSSHTVB( Arrays.asList( "鄂尔多斯市罕台村镇银行" ) ),
//    DLTZYFDVB( Arrays.asList( "达拉特中银富登村镇银行" ) ),
//    DLPLDHFVB( Arrays.asList( "大连普兰店汇丰村镇银行" ) ),
//    DLLSKMYVB( Arrays.asList( "大连旅顺口蒙银村镇银行" ) ),
//    DLGJZPFVB( Arrays.asList( "大连甘井子浦发村镇银行" ) ),
//    DLBSQZJVB( Arrays.asList( "大连保税区珠江村镇银行" ) ),
//    CZSYHQLVB( Arrays.asList( "沧州市运河青隆村镇银行" ) ),
//    CFSSSLNVB( Arrays.asList( "赤峰市松山立农村镇银行" ) ),
//    CFSHSYLVB( Arrays.asList( "赤峰市红山玉龙村镇银行" ) ),
//    CDQBJRXVB( Arrays.asList( "成都青白江融兴村镇银行" ) ),
//    BTSJYLNVB( Arrays.asList( "包头市九原立农村镇银行" ) ),
//    BTSGXYTVB( Arrays.asList( "包头市高新银通村镇银行" ) ),
//    BTSDHJGVB( Arrays.asList( "包头市东河金谷村镇银行" ) ),
//    BSLYHVB( Arrays.asList( "保山隆阳沪农商村镇银行" ) ),
//    BJMTGZJVB( Arrays.asList( "北京门头沟珠江村镇银行" ) ),
//    BJFSHVB( Arrays.asList( "北京房山沪农商村镇银行" ) ),
//    BDMCQLFVB( Arrays.asList( "保定满城区利丰村镇银行" ) ),
//    ALSZQHHVB( Arrays.asList( "阿拉善左旗黄河村镇银行" ) ),
//    ALSZQFDVB( Arrays.asList( "阿拉善左旗方大村镇银行" ) ),
//    AHYXXHHVB( Arrays.asList( "安徽黟县新淮河村镇银行" ) ),
//    AHGZXHHVB( Arrays.asList( "安徽固镇新淮河村镇银行" ) ),
//    ZQZSZYFDVB( Arrays.asList( "重庆长寿中银富登村镇银行" ) ),
//    ZQWXZYFDVB( Arrays.asList( "重庆巫溪中银富登村镇银行" ) ),
//    ZQWSZYFDVB( Arrays.asList( "重庆巫山中银富登村镇银行" ) ),
//    ZQWZZYFDVB( Arrays.asList( "重庆万州中银富登村镇银行" ) ),
//    ZQSSPBRXVB( Arrays.asList( "重庆市沙坪坝融兴村镇银行" ) ),
//    ZQSDDKRXVB( Arrays.asList( "重庆市大渡口融兴村镇银行" ) ),
//    ZQSZZYFDVB( Arrays.asList( "重庆石柱中银富登村镇银行" ) ),
//    ZQNAZYFDVB( Arrays.asList( "重庆南岸中银富登村镇银行" ) ),
//    ZZSSDQTDVB( Arrays.asList( "长治市上党区泰都村镇银行" ) ),
//    SDZCZYFDVTB( Arrays.asList( "山东邹城中银富登村镇银行" ) ),
//    SDZCZYFDVB( Arrays.asList( "山东诸城中银富登村镇银行" ) ),
//    ZQHCZYFDVB( Arrays.asList( "重庆合川中银富登村镇银行" ) ),
//    ZQFLZYFDVB( Arrays.asList( "重庆涪陵中银富登村镇银行" ) ),
//    ZQFJZYFDVB( Arrays.asList( "重庆奉节中银富登村镇银行" ) ),
//    ZQDJZYFDVB( Arrays.asList( "重庆垫江中银富登村镇银行" ) ),
//    ZQCKZYFDVB( Arrays.asList( "重庆城口中银富登村镇银行" ) ),
//    ZJZSPTCZVB( Arrays.asList( "浙江舟山普陀稠州村镇银行" ) ),
//    ZJWYZYFDVB( Arrays.asList( "浙江武义中银富登村镇银行" ) ),
//    ZJTZLQFMVB( Arrays.asList( "浙江台州路桥富民村镇银行" ) ),
//    ZJTZHYHSVB( Arrays.asList( "浙江台州黄岩恒升村镇银行" ) ),
//    ZJQZQJSYVB( Arrays.asList( "浙江衢州衢江上银村镇银行" ) ),
//    ZJKCLXVB( Arrays.asList( "张家口崇礼邢农商村镇银行" ) ),
//    ZJJSZYFDVB( Arrays.asList( "浙江江山中银富登村镇银行" ) ),
//    ZJCNZYFDVB( Arrays.asList( "浙江苍南中银富登村镇银行" ) ),
//    ZJCAZYFDVB( Arrays.asList( "浙江淳安中银富登村镇银行" ) ),
//    XTRZQXVB( Arrays.asList( "邢台任泽区邢农商村镇银行" ) ),
//    XSBNMLZJVB( Arrays.asList( "西双版纳勐腊长江村镇银行" ) ),
//    XSBNMHZJVB( Arrays.asList( "西双版纳勐海长江村镇银行" ) ),
//    XAMKEQMSVB( Arrays.asList( "兴安盟科尔沁蒙商村镇银行" ) ),
//    WLMQMDPFVB( Arrays.asList( "乌鲁木齐米东浦发村镇银行" ) ),
//    WHSHBWHHVB( Arrays.asList( "乌海市海勃湾黄河村镇银行" ) ),
//    WFSWCQBHVB( Arrays.asList( "潍坊市潍城区北海村镇银行" ) ),
//    WFSKWQZCVB( Arrays.asList( "潍坊市奎文区中成村镇银行" ) ),
//    WFSHTQMYVB( Arrays.asList( "潍坊市寒亭区蒙银村镇银行" ) ),
//    TJXQZYFDVB( Arrays.asList( "天津西青中银富登村镇银行" ) ),
//    SZWJZYFDVB( Arrays.asList( "苏州吴江中银富登村镇银行" ) ),
//    SZSSCQMYVB( Arrays.asList( "朔州市朔城区蒙银村镇银行" ) ),
//    SZLGZYFDVB( Arrays.asList( "深圳龙岗中银富登村镇银行" ) ),
//    SZCSZYFDVB( Arrays.asList( "苏州常熟中银富登村镇银行" ) ),
//    SXYLHSHFVB( Arrays.asList( "陕西榆林横山汇发村镇银行" ) ),
//    SXXYWCHFVB( Arrays.asList( "陕西咸阳渭城汇发村镇银行" ) ),
//    SXHZNZHFVB( Arrays.asList( "陕西汉中南郑汇发村镇银行" ) ),
//    SXASZYFDVB( Arrays.asList( "陕西安塞中银富登村镇银行" ) ),
//    SHPDZYFDVB( Arrays.asList( "上海浦东中银富登村镇银行" ) ),
//    SDZYZYFDVB( Arrays.asList( "山东招远中银富登村镇银行" ) ),
//    SDWDZYFDVB( Arrays.asList( "山东文登中银富登村镇银行" ) ),
//    SDTZZYFDVB( Arrays.asList( "山东滕州中银富登村镇银行" ) ),
//    SCCDPJMFVB( Arrays.asList( "四川成都蒲江民富村镇银行" ) ),
//    NXQTXHLSVB( Arrays.asList( "宁夏青铜峡贺兰山村镇银行" ) ),
//    NBZHZYFDVB( Arrays.asList( "宁波镇海中银富登村镇银行" ) ),
//    NBCXZYFDVB( Arrays.asList( "宁波慈溪中银富登村镇银行" ) ),
//    NBBLZYFDVB( Arrays.asList( "宁波北仑中银富登村镇银行" ) ),
//    LKZYFDNSVB( Arrays.asList( "龙口中银富登南山村镇银行" ) ),
//    LFSYDQHDVB( Arrays.asList( "临汾市尧都区惠都村镇银行" ) ),
//    LFSACQHMVB( Arrays.asList( "廊坊市安次区惠民村镇银行" ) ),
//    KLMYJLGMVB( Arrays.asList( "克拉玛依金龙国民村镇银行" ) ),
//    JSZJGYVB( Arrays.asList( "江苏张家港渝农商村镇银行" ) ),
//    JSXSZYFDVB( Arrays.asList( "江苏锡山中银富登村镇银行" ) ),
//    JSWJZYFDVB( Arrays.asList( "江苏武进中银富登村镇银行" ) ),
//    JSTXZYFDVB( Arrays.asList( "江苏泰兴中银富登村镇银行" ) ),
//    JSHMZYFDVB( Arrays.asList( "江苏海门中银富登村镇银行" ) ),
//    HZHTPZJLVB( Arrays.asList( "汉中汉台铺镇聚利村镇银行" ) ),
//    HNXYZYFDVB( Arrays.asList( "河南新野中银富登村镇银行" ) ),
//    HNTJZYFDVB( Arrays.asList( "湖南桃江中银富登村镇银行" ) ),
//    HHHTJQHTVB( Arrays.asList( "呼和浩特金桥河套村镇银行" ) ),
//    HBSZCDHFVB( Arrays.asList( "湖北随州曾都汇丰村镇银行" ) ),
//    HBJMDDDTVB( Arrays.asList( "湖北荆门掇刀德通村镇银行" ) ),
//    HBFNZYFDVB( Arrays.asList( "河北丰宁中银富登村镇银行" ) ),
//    GSJCZYFDVB( Arrays.asList( "甘肃泾川中银富登村镇银行" ) ),
//    EEDSSKBSVB( Arrays.asList( "鄂尔多斯市康巴什村镇银行" ) ),
//    DZDCZYFDVB( Arrays.asList( "达州达川中银富登村镇银行" ) ),
//    CFSYBSYLVB( Arrays.asList( "赤峰市元宝山玉龙村镇银行" ) ),
//    CDPDZYFDVB( Arrays.asList( "成都郫都中银富登村镇银行" ) ),
//    BYPCZYFDVB( Arrays.asList( "白银平川中银富登村镇银行" ) ),
//    BYNESWLTVB( Arrays.asList( "巴彦淖尔市乌拉特村镇银行" ) ),
//    BTSKDLMYVB( Arrays.asList( "包头市昆都仑蒙银村镇银行" ) ),
//    BJTZZYFDVB( Arrays.asList( "北京通州中银富登村镇银行" ) ),
//    BDQYQXVB( Arrays.asList( "保定清苑区邢农商村镇银行" ) ),
//    AKHBZYFDVB( Arrays.asList( "安康汉滨中银富登村镇银行" ) ),
//    AHFCZYFDVB( Arrays.asList( "安徽繁昌中银富登村镇银行" ) ),
//    YNXGLLYVB( Arrays.asList( "云南香格里拉渝农商村镇银行" ) ),
//    XWZMQMSHFVB( Arrays.asList( "西乌珠穆沁蒙商惠丰村镇银行" ) ),
//    XTSXDQXVB( Arrays.asList( "邢台市信都区邢农商村镇银行" ) ),
//    WLCBSJNMSVB( Arrays.asList( "乌兰察布市集宁蒙商村镇银行" ) ),
//    TYSJCPQXDVB( Arrays.asList( "太原市尖草坪区信都村镇银行" ) ),
//    SZSSDWKSYVB( Arrays.asList( "石嘴山市大武口石银村镇银行" ) ),
//    SCCDLQYCZVB( Arrays.asList( "四川成都龙泉驿稠州村镇银行" ) ),
//    NMGHLGEMSVB( Arrays.asList( "内蒙古和林格尔蒙商村镇银行" ) ),
//    MCHZZZXRXVB( Arrays.asList( "孟村回族自治县融信村镇银行" ) ),
//    HLJZDZYFDVB( Arrays.asList( "黑龙江肇东中银富登村镇银行" ) ),
//    HHHTXCMYVB( Arrays.asList( "呼和浩特市新城蒙银村镇银行" ) ),
//    HHHTSHMYVB( Arrays.asList( "呼和浩特市赛罕蒙银村镇银行" ) ),
//    HHHTSHJGVB( Arrays.asList( "呼和浩特市赛罕金谷村镇银行" ) ),
//    HHHTRYMYVB( Arrays.asList( "呼和浩特市如意蒙银村镇银行" ) ),
//    GXQZSQNGMVB( Arrays.asList( "广西钦州市钦南国民村镇银行" ) ),
//    EEDSSTXMYVB( Arrays.asList( "鄂尔多斯市铁西蒙银村镇银行" ) ),
//    EEDSSTJMYVB( Arrays.asList( "鄂尔多斯市天骄蒙银村镇银行" ) ),
//    EEDSSDSMYVB( Arrays.asList( "鄂尔多斯市东胜蒙银村镇银行" ) ),
//    DWZMQNXKYVB( Arrays.asList( "东乌珠穆沁农信开元村镇银行" ) ),
//    DCHZZZXXHVB( Arrays.asList( "大厂回族自治县新华村镇银行" ) ),
//    CHEYYQQMYVB( Arrays.asList( "察哈尔右翼前旗蒙银村镇银行" ) ),
//    BYNESLHHHVB( Arrays.asList( "巴彦淖尔市临河黄河村镇银行" ) ),
//    ZJQTZYFDHQVB( Arrays.asList( "浙江青田中银富登华侨村镇银行" ) ),
//    ZJLSLDZYFDVB( Arrays.asList( "浙江丽水莲都中银富登村镇银行" ) ),
//    NMGTKTLNVB( Arrays.asList( "内蒙古托克托立农村镇银行股份" ) ),
//    FJTNJNSDJHVB( Arrays.asList( "福建泰宁晋农商大金湖村镇银行" ) ),
//    EEDSSTLHJGVB( Arrays.asList( "鄂尔多斯市塔拉壕金谷村镇银行" ) ),
//    DEHMMAHQMSVB( Arrays.asList( "达尔罕茂明安联合旗蒙商村镇银行" ) ),
//    SCBCQXFMVB( Arrays.asList( "四川北川羌族自治县富民村镇银行" ) ),
//    JSGCWJZZYFDVB( Arrays.asList( "江苏高淳武家嘴中银富登村镇银行" ) ),
//    HSVB( Arrays.asList( "围场满族蒙古族自治县华商村镇银行" ) ),
//    FJQZTSTZQJVB( Arrays.asList( "福建泉州台商投资区晋农商村镇银行" ) ),

    ;

    private final List<String> desc;

    BankCodeTianXiaHuiType( List<String> desc ) {
        this.desc = desc;
    }

    public static BankCodeTianXiaHuiType getCodeByDesc( String desc ) {
        for ( BankCodeTianXiaHuiType enumType : BankCodeTianXiaHuiType.values() ) {
            if ( enumType.getDesc().contains( desc ) ) {
                return enumType;
            }
            for ( String s : enumType.getDesc() ) {
                if ( s.contains( desc ) ) {
                    return enumType;
                }
            }
        }
        return null;
    }
}
