package com.qiqilm.server.admin.enums;

import lombok.Getter;

import java.util.Arrays;
import java.util.List;

@Getter
public enum BankCodeKuBiType {
    //
    ABC( Arrays.asList( " 农业银行" ) ),
    ACCB( Arrays.asList( " 城市商业银行" ) ),
    ARCB( Arrays.asList( "农村商业银行" ) ),
    ARCU( Arrays.asList( "农村信用社" ) ),
    AVTB( Arrays.asList( "村镇银行" ) ),
    BCM( Arrays.asList( "交通银行" ) ),
    BEA( Arrays.asList( "东亚银行" ) ),
    BEEB( Arrays.asList( "鄞州银行" ) ),
    BOAS( Arrays.asList( "鞍山银行" ) ),
    BOAY( Arrays.asList( "安阳银行" ) ),
    BOB( Arrays.asList( "北京银行" ) ),
    BOBBW( Arrays.asList( "北部湾银行" ) ),
    BOBD( Arrays.asList( "保定银行" ) ),
    BOC( Arrays.asList( "中国银行" ) ),
    BOCD( Arrays.asList( "成都银行" ) ),
    BOCS( Arrays.asList( "长沙银行" ) ),
    BOCY( Arrays.asList( "朝阳银行" ) ),
    BOCZ( Arrays.asList( "沧州银行" ) ),
    BODD( Arrays.asList( "丹东银行" ) ),
    BODL( Arrays.asList( "大连银行" ) ),
    BODY( Arrays.asList( "德阳银行" ) ),
    BOFS( Arrays.asList( "抚顺银行" ) ),
    BOFX( Arrays.asList( "阜新银行" ) ),
    BOGL( Arrays.asList( "桂林银行" ) ),
    BOGS( Arrays.asList( "甘肃银行" ) ),
    BOGY( Arrays.asList( "贵阳银行" ) ),
    BOGZ( Arrays.asList( "赣州银行" ) ),
    BOHH( Arrays.asList( "汇和银行" ) ),
    BOHLD( Arrays.asList( "葫芦岛银行" ) ),
    BOHRB( Arrays.asList( "哈尔滨银行" ) ),
    BOHS( Arrays.asList( "衡水银行" ) ),
    BOHX( Arrays.asList( "海峡银行" ) ),
    BOHZ( Arrays.asList( "湖州银行" ) ),
    BOIMC( Arrays.asList( "内蒙古银行" ) ),
    BOJL( Arrays.asList( "吉林银行" ) ),
    BOJN( Arrays.asList( "济宁银行" ) ),
    BOJS( Arrays.asList( "晋商银行" ) ),
    BOJX( Arrays.asList( "嘉兴银行" ) ),
    BOKL( Arrays.asList( "昆仑银行" ) ),
    BOLH( Arrays.asList( "漯河银行" ) ),
    BOLJ( Arrays.asList( "龙江银行" ) ),
    BOLZ( Arrays.asList( "柳州银行" ) ),
    BONC( Arrays.asList( "南昌银行" ) ),
    BONX( Arrays.asList( "宁夏银行" ) ),
    BOPDS( Arrays.asList( "平顶山银行" ) ),
    BOPY( Arrays.asList( "濮阳银行" ) ),
    BOQH( Arrays.asList( "青海银行" ) ),
    BOQHD( Arrays.asList( "秦皇岛银行" ) ),
    BOQZ( Arrays.asList( "泉州银行" ) ),
    BOS( Arrays.asList( "上海银行" ) ),
    BOSJ( Arrays.asList( "盛京银行" ) ),
    BOSJS( Arrays.asList( "石嘴山银行" ) ),
    BOSMX( Arrays.asList( "三门峡银行" ) ),
    BOSR( Arrays.asList( "上饶银行" ) ),
    BOSX( Arrays.asList( "绍兴银行" ) ),
    BOSZ( Arrays.asList( "苏州银行" ) ),
    BOT( Arrays.asList( "西藏银行" ) ),
    BOTL( Arrays.asList( "铁岭银行" ) ),
    BOTZ( Arrays.asList( "台州银行" ) ),
    BOWH( Arrays.asList( "乌海银行" ) ),
    BOXM( Arrays.asList( "厦门银行" ) ),
    BOXX( Arrays.asList( "新乡银行" ) ),
    BOXY( Arrays.asList( "信阳银行" ) ),
    BOYK( Arrays.asList( "营口银行" ) ),
    BOZK( Arrays.asList( "周口银行" ) ),
    BOZMD( Arrays.asList( "驻马店银行" ) ),
    BOZZ( Arrays.asList( "枣庄银行" ) ),
    BSB( Arrays.asList( "包商银行" ) ),
    C101061100( Arrays.asList( "网联mock银行" ) ),
    CBHB( Arrays.asList( "渤海银行" ) ),
    CCAB( Arrays.asList( "长安银行" ) ),
    CCB( Arrays.asList( "建设银行","中国建设银行" ) ),
    CCQTGB( Arrays.asList( "三峡银行" ) ),
    CDB( Arrays.asList( "承德银行" ) ),
    CEB( Arrays.asList( "光大银行" ) ),
    CGB( Arrays.asList( "广东发展银行", "广发银行" ) ),
    CHINABANK( Arrays.asList( "网银支付" ) ),
    CHINAGPAY( Arrays.asList( "爱农支付" ) ),
    CHINAPAY( Arrays.asList( "银联支付" ) ),
    CIB( Arrays.asList( "兴业银行" ) ),
    CITIC( Arrays.asList( "中信银行" ) ),
    CJCCB( Arrays.asList( "长江银行" ) ),
    CMB( Arrays.asList( "招商银行" ) ),
    CMBC( Arrays.asList( "民生银行" ) ),
    CMPAY( Arrays.asList( "中移支付" ) ),
    CNEPAY( Arrays.asList( "中汇支付" ) ),
    CQCB( Arrays.asList( "重庆银行" ) ),
    CRB( Arrays.asList( "华润银行" ) ),
    CZB( Arrays.asList( "浙商银行" ) ),
    CZCCB( Arrays.asList( "长治银行" ) ),
    DBS( Arrays.asList( "星展银行" ) ),
    DGCB( Arrays.asList( "东莞银行" ) ),
    DSB( Arrays.asList( "大新银行" ) ),
    DYCCB( Arrays.asList( "东营银行" ) ),
    DZB( Arrays.asList( "德州银行" ) ),
    EGB( Arrays.asList( "恒丰银行" ) ),
    GDNYB( Arrays.asList( "南粤银行" ) ),
    GHB( Arrays.asList( "华兴银行" ) ),
    GZCB( Arrays.asList( "广州银行" ) ),
    HANAB( Arrays.asList( "韩亚银行" ) ),
    HBB( Arrays.asList( "河北银行" ) ),
    HBCL( Arrays.asList( "湖北银行" ) ),
    HDCB( Arrays.asList( "邯郸银行" ) ),
    HKB( Arrays.asList( "汉口银行" ) ),
    HSB( Arrays.asList( "徽商银行" ) ),
    HXB( Arrays.asList( "华夏银行" ) ),
    HZB( Arrays.asList( "杭州银行" ) ),
    IBK( Arrays.asList( "企业银行" ) ),
    ICBC( Arrays.asList( "工商银行", "中国工商银行", "中国工商" ) ),
    JCCB( Arrays.asList( "晋城银行" ) ),
    JHCCB( Arrays.asList( "金华银行" ) ),
    JJCCB( Arrays.asList( "九江银行" ) ),
    JSB( Arrays.asList( "江苏银行" ) ),
    JZB( Arrays.asList( "锦州银行" ) ),
    JZCB( Arrays.asList( "晋中银行" ) ),
    LCCB( Arrays.asList( "廊坊银行" ) ),
    LLPAY( Arrays.asList( "连连支付" ) ),
    LSB( Arrays.asList( "临商银行" ) ),
    LWB( Arrays.asList( "莱商银行" ) ),
    LYCB( Arrays.asList( "辽阳银行" ) ),
    LZCB( Arrays.asList( "兰州银行" ) ),
    NBCB( Arrays.asList( "宁波银行" ) ),
    NBDH( Arrays.asList( "东海银行" ) ),
    NBTS( Arrays.asList( "通商银行" ) ),
    NCB( Arrays.asList( "南洋商业银行" ) ),
    NJCB( Arrays.asList( "南京银行" ) ),
    OCBC( Arrays.asList( "华侨银行" ) ),
    ORDOS( Arrays.asList( "鄂尔多斯银行" ) ),
    PAB( Arrays.asList( "平安银行" ) ),
    PSBC( Arrays.asList( "邮政储蓄银行", "中国邮政储蓄银行", "中国邮政银行", "中国邮政储蓄", "中国邮政", "邮政银行" ) ),
    QDCCB( Arrays.asList( "青岛银行" ) ),
    QLB( Arrays.asList( "齐鲁银行" ) ),
    QSB( Arrays.asList( "齐商银行" ) ),
    RZB( Arrays.asList( "日照银行" ) ),
    SCB( Arrays.asList( "渣打银行" ) ),
    SHB( Arrays.asList( "新韩银行" ) ),
    SPDB( Arrays.asList( "浦发银行" ) ),
    TJCB( Arrays.asList( "天津银行" ) ),
    UMPAY( Arrays.asList( "联动支付" ) ),
    UNSPAY( Arrays.asList( "银生宝" ) ),
    UOB( Arrays.asList( "大华银行" ) ),
    WFCCB( Arrays.asList( "潍坊银行" ) ),
    WHB( Arrays.asList( "永亨银行" ) ),
    WOORIB( Arrays.asList( "友利银行" ) ),
    WZCB( Arrays.asList( "温州银行" ) ),
    XACB( Arrays.asList( "西安银行" ) ),
    XTB( Arrays.asList( "邢台银行" ) ),
    YEEPAY( Arrays.asList( "易宝支付" ) ),
    ZZB( Arrays.asList( "郑州银行" ) ),
    GXBBWYX( Arrays.asList( "北部湾" ) ),
    ;

    private final List<String> desc;

    BankCodeKuBiType( List<String> desc ) {
        this.desc = desc;
    }

    public static BankCodeKuBiType getCodeByDesc( String desc ) {
        for ( BankCodeKuBiType enumType : BankCodeKuBiType.values() ) {
            if ( enumType.getDesc().contains( desc ) ) {
                return enumType;
            }
        }
        return null;
    }
}
