package com.qiqilm.server.admin.enums;

import lombok.Getter;

import java.util.Arrays;
import java.util.List;

@Getter
public enum BankCodeGTType {

    //
    ICBC( Arrays.asList( "工商银行", "中国工商银行", "中国工商" ) ),
    CCB( Arrays.asList( "中国建设银行", "建设银行", "中国建设" ) ),
    CMB( Arrays.asList( "招商银行", "中国招商银行", "中国招商" ) ),
    BOC( Arrays.asList( "中国银行" ) ),
    ABC( Arrays.asList( "农业银行", "中国农业银行", "中国农业" ) ),
    COMM( Arrays.asList( "交通银行" ) ),
    SPDB( Arrays.asList( "浦发银行" ) ),
    GDB( Arrays.asList( "广发银行" ) ),
    CITIC( Arrays.asList( "中信银行" ) ),
    CEB( Arrays.asList( "中国光大银行" ) ),
    CIB( Arrays.asList( "兴业银行" ) ),
    SPABANK( Arrays.asList( "平安银行" ) ),
    CMBC( Arrays.asList( "中国民生银行" ) ),
    HZCB( Arrays.asList( "杭州银行" ) ),
    SHBANK( Arrays.asList( "上海银行" ) ),
    NBBANK( Arrays.asList( "宁波银行" ) ),
    PSBC( Arrays.asList( "邮政储蓄银行", "中国邮政储蓄银行", "中国邮政银行", "中国邮政储蓄", "中国邮政", "邮政银行" ) ),
    BOYK( Arrays.asList( "营口银行" ) ),
    WOORI( Arrays.asList( "友利银行" ) ),
    WHBANK( Arrays.asList( "乌海银行" ) ),
    JKRFCZYH( Arrays.asList( "长春经开融丰村镇银行" ) ),
    JXRCU( Arrays.asList( "江西省农村信用社" ) ),
    BOHN( Arrays.asList( "海南省农村信用社" ) ),
    CRCBANK( Arrays.asList( "重庆农村商业银行" ) ),
    ASCB( Arrays.asList( "鞍山银行" ) ),
    SDB( Arrays.asList( "深圳发展银行" ) ),
    UBCHN( Arrays.asList( "海口联合农商银行" ) ),
    BSB( Arrays.asList( "蒙商银行" ) ),
    CSRCB( Arrays.asList( "江苏常熟农商银行" ) ),
    JSB( Arrays.asList( "晋商银行" ) ),
    HURCB( Arrays.asList( "湖北省农信社" ) ),
    EGBANK( Arrays.asList( "恒丰银行" ) ),
    LSBANK( Arrays.asList( "莱商银行" ) ),
    JHBANK( Arrays.asList( "金华银行" ) ),
    KEB( Arrays.asList( "外换银行" ) ),
    LSBC( Arrays.asList( "临商银行" ) ),
    YZBANK( Arrays.asList( "银座村镇银行" ) ),
    XMBANK( Arrays.asList( "厦门银行" ) ),
    DRCBCL( Arrays.asList( "东莞农村商业银行" ) ),
    PZHCCB( Arrays.asList( "攀枝花市商业银行" ) ),
    RBOZ( Arrays.asList( "珠海华润银行" ) ),
    GDRCC( Arrays.asList( "广东省农村信用社联合社" ) ),
    HANABANK( Arrays.asList( "韩亚银行" ) ),
    MTBANK( Arrays.asList( "浙江民泰商业银行" ) ),
    LANGFB( Arrays.asList( "廊坊银行" ) ),
    BOJZ( Arrays.asList( "锦州银行" ) ),
    TJBHB( Arrays.asList( "天津滨海农村商业银行" ) ),
    HSBANK( Arrays.asList( "徽商银行" ) ),
    NXRCU( Arrays.asList( "宁夏黄河农村商业银行" ) ),
    QLBANK( Arrays.asList( "齐鲁银行" ) ),
    WRCB( Arrays.asList( "无锡农村商业银行" ) ),
    CGXYYH( Arrays.asList( "长葛轩辕村镇银行" ) ),
    IBK( Arrays.asList( "企业银行" ) ),
    BANKWF( Arrays.asList( "潍坊银行" ) ),
    CZBANK( Arrays.asList( "浙商银行" ) ),
    BJBANK( Arrays.asList( "北京银行" ) ),
    HRXJB( Arrays.asList( "华融湘江银行" ) ),
    JZCBANK( Arrays.asList( "焦作中旅银行" ) ),
    JSRCU( Arrays.asList( "江苏省农村信用社联合社" ) ),
    HKBEA( Arrays.asList( "东亚银行" ) ),
    GZRCU( Arrays.asList( "贵州省农村信用社联合社" ) ),
    ZZYH( Arrays.asList( "枣庄银行" ) ),
    ZRCBANK( Arrays.asList( "张家港农村商业银行" ) ),
    QDCCB( Arrays.asList( "青岛银行" ) ),
    LHBANK( Arrays.asList( "漯河银行" ) ),
    ARCU( Arrays.asList( "安徽省农村信用社" ) ),
    ZGCCB( Arrays.asList( "自贡银行" ) ),
    BOHAIB( Arrays.asList( "渤海银行" ) ),
    SDEB( Arrays.asList( "顺德农商银行" ) ),
    HBC( Arrays.asList( "湖北银行" ) ),
    LYCB( Arrays.asList( "辽阳银行" ) ),
    FXCB( Arrays.asList( "阜新银行" ) ),
    WJRCB( Arrays.asList( "苏州农村商业银行" ) ),
    SDZFQFCZYH( Arrays.asList( "山东芝罘齐丰村镇银行" ) ),
    HSB( Arrays.asList( "恒生银行" ) ),
    NYBANK( Arrays.asList( "广东南粤银行" ) ),
    BGB( Arrays.asList( "广西北部湾银行" ) ),
    DAQINGB( Arrays.asList( "龙江银行" ) ),
    HXBANK( Arrays.asList( "华夏银行" ) ),
    CDCB( Arrays.asList( "成都银行" ) ),
    HLDB( Arrays.asList( "葫芦岛银行" ) ),
    WZCB( Arrays.asList( "温州银行" ) ),
    H3CB( Arrays.asList( "内蒙古银行" ) ),
    GRCB( Arrays.asList( "广州农村商业银行" ) ),
    HSBC( Arrays.asList( "汇丰银行（中国）" ) ),
    QHRC( Arrays.asList( "青海省农村信用社" ) ),
    LSCCB( Arrays.asList( "乐山市商业银行" ) ),
    SZSBK( Arrays.asList( "石嘴山银行" ) ),
    SINO( Arrays.asList( "永丰银行" ) ),
    CCQTGB( Arrays.asList( "重庆三峡银行" ) ),
    HSBK( Arrays.asList( "衡水市商业银行" ) ),
    SXBANK( Arrays.asList( "三湘银行" ) ),
    DLB( Arrays.asList( "大连银行" ) ),
    BHB( Arrays.asList( "河北银行" ) ),
    YQCCB( Arrays.asList( "阳泉市商业银行" ) ),
    SJBANK( Arrays.asList( "盛京银行" ) ),
    XTB( Arrays.asList( "邢台银行" ) ),
    DYCCB( Arrays.asList( "东营银行" ) ),
    BDCBANK( Arrays.asList( "保定银行" ) ),
    DZBANK( Arrays.asList( "德州银行" ) ),
    ANTBANK( Arrays.asList( "网商银行" ) ),
    PZBANK( Arrays.asList( "盘锦银行" ) ),
    ZJNX( Arrays.asList( "浙江省农村信用社联合社" ) ),
    CSCB( Arrays.asList( "长沙银行" ) ),
    JZBANK( Arrays.asList( "晋中银行" ) ),
    BOCFCB( Arrays.asList( "中银富登村镇银行" ) ),
    SRCB( Arrays.asList( "深圳农村商业银行" ) ),
    ZYB( Arrays.asList( "中原银行" ) ),
    SDRCU( Arrays.asList( "山东省农村信用社联合社" ) ),
    GCB( Arrays.asList( "广州银行" ) ),
    SXRCCU( Arrays.asList( "陕西省农信社" ) ),
    XJRCU( Arrays.asList( "新疆农村信用社" ) ),
    JLBANK( Arrays.asList( "吉林银行" ) ),
    TACCB( Arrays.asList( "泰安银行" ) ),
    GYCB( Arrays.asList( "贵阳银行" ) ),
    XHCZYH( Arrays.asList( "新华村镇银行" ) ),
    RZB( Arrays.asList( "日照银行" ) ),
    KLB( Arrays.asList( "昆仑银行" ) ),
    XZBANK( Arrays.asList( "西藏银行" ) ),
    JJBANK( Arrays.asList( "九江银行" ) ),
    SXRCU( Arrays.asList( "山西省农村信用社" ) ),
    HNBANK( Arrays.asList( "海南银行股份有限公司" ) ),
    CGNB( Arrays.asList( "四川天府银行" ) ),
    CZCB( Arrays.asList( "浙江稠州商业银行" ) ),
    WZMSBANK( Arrays.asList( "温州民商银行" ) ),
    SHRCB( Arrays.asList( "上海农商银行" ) ),
    TLBANK( Arrays.asList( "铁岭银行" ) ),
    SNCCB( Arrays.asList( "遂宁银行" ) ),
    NXBANK( Arrays.asList( "宁夏银行" ) ),
    NMGNXS( Arrays.asList( "内蒙古农村信用社联合社" ) ),
    DBSCN( Arrays.asList( "星展银行" ) ),
    HBRCU( Arrays.asList( "河北省农村信用社" ) ),
    LNRCC( Arrays.asList( "辽宁省农村信用社" ) ),
    DYLSCB( Arrays.asList( "东营莱商村镇银行" ) ),
    TCCB( Arrays.asList( "天津银行" ) ),
    BOQZ( Arrays.asList( "泉州银行" ) ),
    WHRCB( Arrays.asList( "武汉农村商业银行" ) ),
    NCB( Arrays.asList( "江西银行" ) ),
    BJRCB( Arrays.asList( "北京农商行" ) ),
    ZJKCCB( Arrays.asList( "张家口银行" ) ),
    JNBANK( Arrays.asList( "济宁银行" ) ),
    HRBANK( Arrays.asList( "哈尔滨银行" ) ),
    BOQH( Arrays.asList( "青海银行" ) ),
    YBCCB( Arrays.asList( "宜宾市商业银行" ) ),
    LZYH( Arrays.asList( "兰州银行" ) ),
    NJCB( Arrays.asList( "南京银行" ) ),
    JINCHB( Arrays.asList( "晋城银行" ) ),
    TZCB( Arrays.asList( "台州银行" ) ),
    CQBANK( Arrays.asList( "重庆银行" ) ),
    URB( Arrays.asList( "联合村镇银行" ) ),
    SCRCU( Arrays.asList( "四川省农村信用社联合社" ) ),
    FDB( Arrays.asList( "富滇银行" ) ),
    LYRTCZYH( Arrays.asList( "长春绿园融泰村镇银行" ) ),
    AHXABANK( Arrays.asList( "安徽新安银行" ) ),
    YTBANK( Arrays.asList( "烟台银行" ) ),
    DLRCB( Arrays.asList( "大连农村商业银行" ) ),
    QYBANK( Arrays.asList( "韩国企业银行" ) ),
    QHDBANK( Arrays.asList( "秦皇岛银行" ) ),
    NBCBANK( Arrays.asList( "宁波通商银行" ) ),
    SRBANK( Arrays.asList( "上饶银行" ) ),
    HNRCU( Arrays.asList( "河南省农村信用社" ) ),
    HNSSXNSCZYH( Arrays.asList( "山东金乡蓝海村镇银行" ) ),
    BOSZ( Arrays.asList( "苏州银行" ) ),
    YXCCB( Arrays.asList( "云南红塔银行" ) ),
    XIB( Arrays.asList( "厦门国际银行" ) ),
    BOCD( Arrays.asList( "承德银行" ) ),
    HNRCC( Arrays.asList( "湖南省农村信用社" ) ),
    XABANK( Arrays.asList( "西安银行" ) ),
    TRCB( Arrays.asList( "天津农商银行" ) ),
    BOSH( Arrays.asList( "新韩银行" ) ),
    URMQCCB( Arrays.asList( "乌鲁木齐银行" ) ),
    GHB( Arrays.asList( "广东华兴银行" ) ),
    CCHRCZYH( Arrays.asList( "长春朝阳和润村镇银行" ) ),
    CZRCB( Arrays.asList( "江南农村商业银行" ) ),
    MYBANK( Arrays.asList( "绵阳市商业银行" ) ),
    HDBANK( Arrays.asList( "邯郸银行" ) ),
    JRCB( Arrays.asList( "江苏江阴农村商业银行" ) ),
    CITICN( Arrays.asList( "花旗银行(中国)" ) ),
    JSZZLHCZYH( Arrays.asList( "辽宁大石桥隆丰村镇银行" ) ),
    KJCZYH( Arrays.asList( "梅县客家村镇银行" ) ),
    BNY( Arrays.asList( "南阳市商业银行" ) ),
    HLJRCU( Arrays.asList( "黑龙江省农村信用社联合社" ) ),
    KCBEBANK( Arrays.asList( "天津金城银行" ) ),
    DYCB( Arrays.asList( "长城华西银行" ) ),
    SCBBANK( Arrays.asList( "商丘市商业银行" ) ),
    BOD( Arrays.asList( "东莞银行" ) ),
    NCBANK( Arrays.asList( "南洋商业银行" ) ),
    WHCCB( Arrays.asList( "威海市商业银行" ) ),
    BOCZ( Arrays.asList( "沧州银行" ) ),
    BOCY( Arrays.asList( "朝阳银行" ) ),
    CABANK( Arrays.asList( "长安银行" ) ),
    HKB( Arrays.asList( "汉口银行" ) ),
    BOL( Arrays.asList( "洛阳银行" ) ),
    GXRCU( Arrays.asList( "广西壮族自治区农村信用社联合社" ) ),
    BOP( Arrays.asList( "平顶山银行" ) ),
    SXCB( Arrays.asList( "绍兴银行" ) ),
    YKYHCCB( Arrays.asList( "营口沿海银行" ) ),
    ZBCB( Arrays.asList( "齐商银行" ) ),
    GZB( Arrays.asList( "赣州银行" ) ),
    FJNX( Arrays.asList( "福建省农村信用社联合社" ) ),
    HZCCB( Arrays.asList( "湖州银行" ) ),
    QJCCB( Arrays.asList( "曲靖市商业银行" ) ),
    ZXBXBANK( Arrays.asList( "百信银行" ) ),
    JXBANK( Arrays.asList( "嘉兴银行" ) ),
    KSRB( Arrays.asList( "昆山农村商业银行" ) ),
    FJHXBC( Arrays.asList( "福建海峡银行" ) ),
    ZYCBANK( Arrays.asList( "贵州银行" ) ),
    KYHNSCZYH( Arrays.asList( "象山国民村镇银行" ) ),
    YGCB( Arrays.asList( "前郭县阳光村镇银行" ) ),
    ZJTLCB( Arrays.asList( "浙江泰隆商业银行" ) ),
    CJCCB( Arrays.asList( "江苏长江商业银行" ) ),
    NHB( Arrays.asList( "南海农商银行" ) ),
    LZCCB( Arrays.asList( "柳州银行" ) ),
    FBBANK( Arrays.asList( "富邦华一银行" ) ),
    FSCB( Arrays.asList( "抚顺银行" ) ),
    CZCCB( Arrays.asList( "长治银行" ) ),
    LUZBANK( Arrays.asList( "泸州市商业银行" ) ),
    GSRCU( Arrays.asList( "甘肃省农村信用社" ) ),
    GLBANK( Arrays.asList( "桂林银行" ) ),
    ZZBANK( Arrays.asList( "郑州银行" ) ),
    TCRCB( Arrays.asList( "江苏太仓农村商业银行" ) ),
    HSCZB( Arrays.asList( "湖商村镇银行" ) ),
    CDRCB( Arrays.asList( "成都农商银行" ) ),
    CBKF( Arrays.asList( "开封市商业银行" ) ),
    YDNSCZYH( Arrays.asList( "尧都农商银行村镇银行" ) ),
    ORBANK( Arrays.asList( "鄂尔多斯银行" ) ),
    NBYZ( Arrays.asList( "宁波鄞州农商行" ) ),
    JSBANK( Arrays.asList( "江苏银行" ) ),
    SCB( Arrays.asList( "渣打银行" ) ),
    JLRCU( Arrays.asList( "吉林省农村信用社联合社" ) ),
    YNRCC( Arrays.asList( "云南省农村信用社" ) ),
    BSBK( Arrays.asList( "包商银行" ) ),
    GLGMCB( Arrays.asList( "桂林国民村镇银行" ) ),
    GX966888( Arrays.asList( "广西省农村信用社" ) ),

    ;

    private final List<String> desc;

    BankCodeGTType( List<String> desc ) {
        this.desc = desc;
    }

    public static BankCodeGTType getCodeByDesc( String desc ) {
        for ( BankCodeGTType enumType : BankCodeGTType.values() ) {
            if ( enumType.getDesc().contains( desc ) ) {
                return enumType;
            }
        }
        return null;
    }
}
