package com.qiqilm.server.admin.enums;

import lombok.Getter;

import java.util.Arrays;
import java.util.List;

@Getter
public enum BankCodeDaNiuType {
    //
    a1(Arrays.asList("工商银行", "中国工商银行", "中国工商")),
    a2(Arrays.asList("农业银行", "中国农业银行")),
    a3(Arrays.asList("中国银行")),
    a4(Arrays.asList("建设银行", "中国建设银行")),
    a5(Arrays.asList("民生银行")),
    a6(Arrays.asList("交通银行")),
    a7(Arrays.asList("中信银行")),
    a8(Arrays.asList("光大银行")),
    a9(Arrays.asList("华夏银行")),
    a10(Arrays.asList("广东发展银行", "广发银行")),
    a11(Arrays.asList("平安银行")),
    a12(Arrays.asList("招商银行", "中国招商银行")),
    a13(Arrays.asList("兴业银行")),
    a14(Arrays.asList("浦发银行", "上海浦东发展银行", "浦东发展银行")),
    a15(Arrays.asList("北京银行")),
    a16(Arrays.asList("天津银行")),
    a17(Arrays.asList("河北银行")),
    a18(Arrays.asList("邢台银行")),
    a19(Arrays.asList("承德银行")),
    a20(Arrays.asList("沧州银行")),
    a21(Arrays.asList("廊坊银行")),
    a22(Arrays.asList("衡水银行")),
    a23(Arrays.asList("晋商银行")),
    a24(Arrays.asList("晋城银行")),
    a25(Arrays.asList("晋中银行")),
    a26(Arrays.asList("内蒙古银行")),
    a27(Arrays.asList("包商银行")),
    a28(Arrays.asList("乌海银行")),
    a29(Arrays.asList("鄂尔多斯银行")),
    a30(Arrays.asList("大连银行")),
    a31(Arrays.asList("锦州银行")),
    a32(Arrays.asList("葫芦岛银行")),
    a33(Arrays.asList("营口银行")),
    a34(Arrays.asList("阜新银行")),
    a35(Arrays.asList("吉林银行")),
    a36(Arrays.asList("哈尔滨银行")),
    a37(Arrays.asList("龙江银行")),
    a38(Arrays.asList("南京银行")),
    a39(Arrays.asList("江苏银行")),
    a40(Arrays.asList("苏州银行")),
    a41(Arrays.asList("杭州银行")),
    a42(Arrays.asList("温州银行")),
    a43(Arrays.asList("嘉兴银行")),
    a44(Arrays.asList("湖州银行")),
    a45(Arrays.asList("绍兴银行")),
    a46(Arrays.asList("台州银行")),
    a47(Arrays.asList("福建海峡银行")),
    a48(Arrays.asList("厦门银行")),
    a49(Arrays.asList("泉州银行")),
    a50(Arrays.asList("南昌银行")),
    a51(Arrays.asList("赣州银行")),
    a52(Arrays.asList("上饶银行")),
    a53(Arrays.asList("齐鲁银行")),
    a54(Arrays.asList("青岛银行")),
    a55(Arrays.asList("齐商银行")),
    a56(Arrays.asList("枣庄银行")),
    a57(Arrays.asList("东营银行")),
    a58(Arrays.asList("烟台银行")),
    a59(Arrays.asList("潍坊银行")),
    a60(Arrays.asList("济宁银行")),
    a61(Arrays.asList("莱商银行")),
    a62(Arrays.asList("德州银行")),
    a63(Arrays.asList("临商银行")),
    a64(Arrays.asList("日照银行")),
    a65(Arrays.asList("郑州银行")),
    a66(Arrays.asList("中原银行")),
    a67(Arrays.asList("洛阳银行")),
    a68(Arrays.asList("平顶山银行")),
    a69(Arrays.asList("汉口银行")),
    a70(Arrays.asList("湖北银行")),
    a71(Arrays.asList("华融湘江银行")),
    a72(Arrays.asList("长沙银行")),
    a73(Arrays.asList("广州银行")),
    a74(Arrays.asList("珠海华润银行")),
    a75(Arrays.asList("广东华兴银行")),
    a76(Arrays.asList("广东南粤银行")),
    a77(Arrays.asList("柳州银行")),
    a78(Arrays.asList("德阳银行")),
    a79(Arrays.asList("富滇银行")),
    a80(Arrays.asList("西安银行")),
    a81(Arrays.asList("长安银行")),
    a82(Arrays.asList("兰州银行")),
    a83(Arrays.asList("青海银行")),
    a84(Arrays.asList("宁夏银行")),
    a85(Arrays.asList("昆仑银行")),
    a86(Arrays.asList("恒丰银行")),
    a87(Arrays.asList("渤海银行")),
    a88(Arrays.asList("徽商银行")),
    a89(Arrays.asList("深圳前海微众银行")),
    a90(Arrays.asList("上海银行")),
    a91(Arrays.asList("鄞州银行")),
    a92(Arrays.asList("福建省农村信用社", "福建农信", "福建农村信用社银行", "福建农村信用社", "福建省农村信用社银行")),
    a93(Arrays.asList("邮政储蓄银行", "中国邮政储蓄银行", "中国邮政银行", "中国邮政储蓄", "中国邮政", "邮政银行", "邮政储蓄")),
    a94(Arrays.asList("厦门国际银行")),
    a95(Arrays.asList("安义融兴村镇银行")),
    a96(Arrays.asList("鞍山市商业银行")),
    a97(Arrays.asList("澳新银行")),
    a98(Arrays.asList("巴彦融兴村镇银行")),
    a99(Arrays.asList("拜泉融兴村镇银行")),
    a100(Arrays.asList("保定银行")),
    a101(Arrays.asList("北京昌平包商村镇银行")),
    a102(Arrays.asList("北京怀柔融兴村镇银行")),
    a103(Arrays.asList("北京农村商业银行", "北京农商")),
    a104(Arrays.asList("北京顺义银座村镇银行")),
    a105(Arrays.asList("北京中关村银行")),
    a106(Arrays.asList("北屯国民村镇银行")),
    a107(Arrays.asList("毕节发展村镇银行")),
    a108(Arrays.asList("博乐国民村镇银行")),
    a109(Arrays.asList("昌吉国民村镇银行")),
    a110(Arrays.asList("朝阳银行")),
    a111(Arrays.asList("成都农村商业银行", "成都农商")),
    a112(Arrays.asList("成都银行")),
    a113(Arrays.asList("城市商业银行")),
    a114(Arrays.asList("城市信用社")),
    a115(Arrays.asList("长城华西银行")),
    a116(Arrays.asList("长治银行")),
    a117(Arrays.asList("重庆农村商业银行", "重庆农商")),
    a118(Arrays.asList("重庆彭水民泰村镇银行")),
    a119(Arrays.asList("重庆黔江银座村镇银行")),
    a120(Arrays.asList("重庆三峡银行")),
    a121(Arrays.asList("重庆银行")),
    a122(Arrays.asList("重庆渝北银座村镇银行")),
    a123(Arrays.asList("村镇银行")),
    a124(Arrays.asList("大华银行")),
    a125(Arrays.asList("大连金州联丰村镇银行")),
    a126(Arrays.asList("丹东银行")),
    a127(Arrays.asList("德意志银行")),
    a128(Arrays.asList("东莞农村商业银行", "东莞农商")),
    a129(Arrays.asList("东莞银行")),
    a130(Arrays.asList("东兴国民村镇银行")),
    a131(Arrays.asList("东亚银行")),
    a132(Arrays.asList("东营莱商村镇银行")),
    a133(Arrays.asList("佛山顺德农村商业银行", "顺德农商")),
    a134(Arrays.asList("阜新银行结算中心")),
    a135(Arrays.asList("富邦华一银行")),
    a136(Arrays.asList("甘肃省农村信用社", "甘肃农信", "甘肃农村信用社银行", "甘肃农村信用社", "甘肃省农村信用社银行")),
    a137(Arrays.asList("甘肃银行")),
    a138(Arrays.asList("固阳包商村镇银行")),
    a139(Arrays.asList("广东省农村信用社", "广东农信", "广东农村信用社银行", "广东农村信用社", "广东省农村信用社银行")),
    a140(Arrays.asList("广西北部湾银行")),
    a141(Arrays.asList("广西农村信用社", "广西农信", "广西农村信用社银行")),
    a142(Arrays.asList("广西浦北国民村镇银行")),
    a143(Arrays.asList("广西上林国民村镇银行")),
    a144(Arrays.asList("广西银海国民村镇银行")),
    a145(Arrays.asList("广州农村商业银行", "广州农商")),
    a146(Arrays.asList("贵阳花溪建设村镇银行")),
    a147(Arrays.asList("贵阳市商业银行")),
    a148(Arrays.asList("贵州省农村信用社", "贵州农信", "贵州农村信用社银行", "贵州农村信用社", "贵州省农村信用社银行")),
    a149(Arrays.asList("贵州银行")),
    a150(Arrays.asList("桂林银行")),
    a151(Arrays.asList("国家开发银行")),
    a152(Arrays.asList("国民银行")),
    a153(Arrays.asList("哈密红星国民村镇银行")),
    a154(Arrays.asList("海口联合农村商业银行", "海口农商")),
    a155(Arrays.asList("海南保亭融兴村镇银行")),
    a156(Arrays.asList("海南省农村信用社", "海南农信", "海南农村信用社银行", "海南农村信用社", "海南省农村信用社银行")),
    a157(Arrays.asList("海南银行")),
    a158(Arrays.asList("邯郸市商业银行")),
    a159(Arrays.asList("韩亚银行")),
    a160(Arrays.asList("合浦国民村镇银行")),
    a161(Arrays.asList("河南省农村信用社", "河南农信", "河南农村信用社银行", "河南农村信用社", "河南省农村信用社银行")),
    a162(Arrays.asList("洪湖融兴村镇银行")),
    a163(Arrays.asList("湖北省农村信用社", "湖北农信", "湖北农村信用社银行", "湖北农村信用社", "湖北省农村信用社银行")),
    a164(Arrays.asList("湖南三湘银行")),
    a165(Arrays.asList("湖南省农村信用社", "湖南农信", "湖南农村信用社银行", "湖南农村信用社", "湖南省农村信用社银行")),
    a166(Arrays.asList("花旗银行")),
    a167(Arrays.asList("化德包商村镇银行")),
    a168(Arrays.asList("桦川融兴村镇银行")),
    a169(Arrays.asList("汇丰银行")),
    a170(Arrays.asList("会宁会师村镇银行")),
    a171(Arrays.asList("江苏长江商业银行")),
    a172(Arrays.asList("江苏常熟农村商业银行", "常熟农商")),
    a173(Arrays.asList("江苏邗江民泰村镇银行")),
    a174(Arrays.asList("江苏惠山民泰村镇银行")),
    a175(Arrays.asList("江苏江南农村商业银行", "江南农商")),
    a176(Arrays.asList("江苏江阴农村商业银行", "江阴农商")),
    a177(Arrays.asList("江苏如东融兴村镇银行")),
    a178(Arrays.asList("江苏苏宁银行")),
    a179(Arrays.asList("江苏仪征包商村镇银行")),
    a180(Arrays.asList("江西赣州银座村镇银行")),
    a181(Arrays.asList("江西瑞金光大村镇银行")),
    a182(Arrays.asList("江西省农村信用社", "江西农信", "江西农村信用社银行", "江西农村信用社", "江西省农村信用社银行")),
    a183(Arrays.asList("江西银行")),
    a184(Arrays.asList("焦作中旅银行")),
    a185(Arrays.asList("金华银行")),
    a186(Arrays.asList("九江银行")),
    a187(Arrays.asList("九台龙嘉村镇银行")),
    a188(Arrays.asList("鄄城包商村镇银行")),
    a189(Arrays.asList("库车国民村镇银行")),
    a190(Arrays.asList("奎屯国民村镇银行")),
    a191(Arrays.asList("昆山农村商业银行", "昆山农商")),
    a192(Arrays.asList("乐平融兴村镇银行")),
    a193(Arrays.asList("乐山市商业银行")),
    a194(Arrays.asList("耒阳融兴村镇银行")),
    a195(Arrays.asList("辽宁省农村信用社", "辽宁农信", "辽宁农村信用社银行", "辽宁农村信用社", "辽宁省农村信用社银行")),
    a196(Arrays.asList("辽阳银行")),
    a197(Arrays.asList("泸州市商业银行")),
    a198(Arrays.asList("梅州客商银行")),
    a199(Arrays.asList("绵阳市商业银行")),
    a200(Arrays.asList("摩根大通银行")),
    a201(Arrays.asList("莫力达瓦包商村镇银行")),
    a202(Arrays.asList("宁波东海银行")),
    a203(Arrays.asList("宁波通商银行")),
    a204(Arrays.asList("宁波银行")),
    a205(Arrays.asList("宁波鄞州农村合作银行")),
    a206(Arrays.asList("宁城包商村镇银行")),
    a207(Arrays.asList("宁夏贺兰回商村镇银行")),
    a208(Arrays.asList("宁夏黄河农村商业银行", "黄河农商")),
    a209(Arrays.asList("农村合作银行")),
    a210(Arrays.asList("农村商业银行（停用）")),
    a211(Arrays.asList("攀枝花市商业银行")),
    a212(Arrays.asList("平果国民村镇银行")),
    a213(Arrays.asList("清徐惠民村镇银行")),
    a214(Arrays.asList("曲靖市商业银行")),
    a215(Arrays.asList("瑞士银行")),
    a216(Arrays.asList("山东省农村信用社", "山东农信", "山东省农村信用社联合社", "山东农村信用社银行", "山东农村信用社", "山东省农村信用社银行")),
    a217(Arrays.asList("陕西省农村信用社", "陕西农信", "陕西农村信用社银行")),
    a218(Arrays.asList("上海华瑞银行")),
    a219(Arrays.asList("上海农村商业银行", "上海农商")),
    a220(Arrays.asList("上海浦东发展银行")),
    a221(Arrays.asList("深圳宝安融兴村镇银行")),
    a222(Arrays.asList("深圳福田银座村镇银行")),
    a223(Arrays.asList("深圳农村商业银行", "深圳农商")),
    a224(Arrays.asList("盛京银行")),
    a225(Arrays.asList("石河子国民村镇银行")),
    a226(Arrays.asList("石嘴山银行")),
    a227(Arrays.asList("四川省农村信用社", "四川农信", "四川农村信用社银行", "四川农村信用社", "四川省农村信用社银行")),
    a228(Arrays.asList("四川天府银行")),
    a229(Arrays.asList("遂宁安居融兴村镇银行")),
    a230(Arrays.asList("遂宁银行")),
    a231(Arrays.asList("太仓农村商业银行", "太仓农商")),
    a232(Arrays.asList("泰安银行")),
    a233(Arrays.asList("唐山银行")),
    a234(Arrays.asList("天津滨海农村商业银行", "滨海农商")),
    a235(Arrays.asList("天津津南村镇银行")),
    a236(Arrays.asList("天津农村商业银行", "天津农商")),
    a237(Arrays.asList("威海市商业银行")),
    a238(Arrays.asList("温州民商银行")),
    a239(Arrays.asList("乌鲁木齐市商业银行")),
    a240(Arrays.asList("乌审旗包商村镇银银行")),
    a241(Arrays.asList("无锡农村商业银行", "无锡农商")),
    a242(Arrays.asList("吴江农村商业银行", "吴江农商")),
    a243(Arrays.asList("五家渠国民村镇银行")),
    a244(Arrays.asList("武冈包商村镇银行")),
    a245(Arrays.asList("武汉农村商业银行", "武汉农商")),
    a246(Arrays.asList("武隆融兴村镇银行")),
    a247(Arrays.asList("西藏银行")),
    a248(Arrays.asList("息烽包商黔隆村镇银行")),
    a249(Arrays.asList("象山国民村镇银行")),
    a250(Arrays.asList("新安融兴村镇银行")),
    a251(Arrays.asList("新都桂城村镇银行")),
    a252(Arrays.asList("新韩银行")),
    a253(Arrays.asList("新疆汇和银行")),
    a254(Arrays.asList("新疆绿洲国民村镇银行")),
    a255(Arrays.asList("新网银行")),
    a256(Arrays.asList("延寿融兴村镇银行")),
    a257(Arrays.asList("偃师融兴村镇银行")),
    a258(Arrays.asList("伊犁国民村镇银行")),
    a259(Arrays.asList("宜宾市商业银行")),
    a260(Arrays.asList("银行间市场清算所")),
    a261(Arrays.asList("营口沿海银行")),
    a262(Arrays.asList("应城融兴村镇银行")),
    a263(Arrays.asList("永丰银行")),
    a264(Arrays.asList("友利银行")),
    a265(Arrays.asList("榆树融兴村镇银行")),
    a266(Arrays.asList("云南红塔银行")),
    a267(Arrays.asList("云南省农村信用社", "云南农信", "云南农村信用社银行", "云南农村信用社", "云南省农村信用社银行")),
    a268(Arrays.asList("渣打银行")),
    a269(Arrays.asList("张家港农村商业银行", "张家港农商")),
    a270(Arrays.asList("张家口银行")),
    a271(Arrays.asList("浙江稠州商业银行")),
    a272(Arrays.asList("浙江景宁银座村镇银行")),
    a273(Arrays.asList("浙江龙泉民泰村镇银行")),
    a274(Arrays.asList("浙江民泰商业银行")),
    a275(Arrays.asList("浙江三门银座村镇银行")),
    a276(Arrays.asList("浙江省农村信用社", "浙江农信", "浙江农村信用社银行", "浙江农村信用社", "浙江省农村信用社银行")),
    a277(Arrays.asList("浙江泰隆商业银行")),
    a278(Arrays.asList("浙江网商银行")),
    a280(Arrays.asList("中德住房储蓄银行")),
    a281(Arrays.asList("中国进出口银行")),
    a282(Arrays.asList("中国农业发展银行")),
    a283(Arrays.asList("中信百信银行")),
    a284(Arrays.asList("株洲县融兴村镇银银行")),
    a285(Arrays.asList("准格尔旗包商村镇银行")),
    a286(Arrays.asList("自贡市商业银行")),
    a287(Arrays.asList("焦作市商业银行")),
    a288(Arrays.asList("南充市商业银行")),
    a289(Arrays.asList("玉溪市商业银行")),
    a290(Arrays.asList("吉林农村信用社", "吉林农信")),
    a291(Arrays.asList("江苏省农村信用社联合社", "江苏农信", "江苏农村信用社银行", "江苏农村信用社", "江苏省农村信用社银行")),
    a292(Arrays.asList("安徽省农村信用社联合社", "安徽农信", "安徽农村信用社银行", "安徽农村信用社", "安徽省农村信用社银行")),
    a293(Arrays.asList("江苏农村商业银行", "江苏农商", "江苏农商银行")),
    a294(Arrays.asList("广州农村信用社", "广州农信", "广州农村信用社银行")),
    a279(Arrays.asList("浙商银行")),
    ;

    private final List<String> desc;

    BankCodeDaNiuType(List<String> desc) {
        this.desc = desc;
    }

    public static BankCodeDaNiuType getCodeByDesc(String desc) {
        for (BankCodeDaNiuType enumType : BankCodeDaNiuType.values()) {
            if (enumType.getDesc().contains(desc)) {
                return enumType;
            }
        }
        return null;
    }
}
