package com.qiqilm.server.admin.enums;

import lombok.Getter;

import java.util.Arrays;
import java.util.List;

@Getter
public enum BankCodeZhiYuanType {
    //
    ICBC( Arrays.asList( "工商银行", "中国工商银行", "中国工商" ) ),
    ZJRCBANK( Arrays.asList( "珠江村镇银行" ) ),
    QHNX( Arrays.asList( "青海农信" ) ),
    CCB( Arrays.asList( "建设银行", "中国建设银行" ) ),
    YIZHANGBANK( Arrays.asList( "宜章长行村镇银行" ) ),
    CMBC( Arrays.asList( "民生银行" ) ),
    SPDB( Arrays.asList( "浦发银行", "上海浦东发展银行", "浦东发展银行" ) ),
    ECITIC( Arrays.asList( "中信银行" ) ),
    ABC( Arrays.asList( "农业银行", "中国农业银行" ) ),
    BOBJ( Arrays.asList( "北京银行" ) ),
    BOC( Arrays.asList( "中国银行" ) ),
    CMB( Arrays.asList( "招商银行" ) ),
    ZY( Arrays.asList( "中原银行" ) ),
    BOCM( Arrays.asList( "交通银行" ) ),
    PSBC( Arrays.asList( "邮政储蓄银行", "中国邮政储蓄银行", "中国邮政银行", "中国邮政储蓄", "中国邮政", "邮政银行" ) ),
    JSB( Arrays.asList( "晋商银行" ) ),
    HBNX( Arrays.asList( "湖北农信" ) ),
    HXB( Arrays.asList( "华夏银行" ) ),
    LIAOSHEN( Arrays.asList( "辽沈银行" ) ),
    CEB( Arrays.asList( "光大银行", "中国光大银行" ) ),
    GLB( Arrays.asList( "桂林银行" ) ),
    PAB( Arrays.asList( "平安银行" ) ),
    HFB( Arrays.asList( "恒丰银行" ) ),
    SDNSB( Arrays.asList( "山东农商银行" ) ),
    QLB( Arrays.asList( "齐鲁银行" ) ),
    GZNXB( Arrays.asList( "贵州农信" ) ),
    GDNXB( Arrays.asList( "广东农信" ) ),
    GZB( Arrays.asList( "广州银行" ) ),
    DGB( Arrays.asList( "东莞银行" ) ),
    GXNXB( Arrays.asList( "广西农信" ) ),
    DGNXB( Arrays.asList( "东莞农商银行" ) ),
    JGB( Arrays.asList( "九江银行" ) ),
    HNNXB( Arrays.asList( "河南农信" ) ),
    CIB( Arrays.asList( "兴业银行" ) ),
    JXNSB( Arrays.asList( "江西农商银行" ) ),
    GXBBWB( Arrays.asList( "广西北部湾银行" ) ),
    GYB( Arrays.asList( "贵阳银行" ) ),
    GZHB( Arrays.asList( "贵州银行" ) ),
    SHB( Arrays.asList( "上海银行" ) ),
    GMCZB( Arrays.asList( "国民村镇银行" ) ),
    GZNSB( Arrays.asList( "广州农商银行" ) ),
    GDHXB( Arrays.asList( "广东华兴银行" ) ),
    NJCB( Arrays.asList( "南京银行" ) ),
    NCB( Arrays.asList( "江西银行" ) ),
    CGB( Arrays.asList( "广发银行" ) ),
    KSNSB( Arrays.asList( "昆山农商银行" ) ),
    SZNSHB( Arrays.asList( "深圳农商行" ) ),
    SCNXB( Arrays.asList( "四川农信" ) ),
    ZJGNXB( Arrays.asList( "张家港农商银行" ) ),
    BOSZ( Arrays.asList( "苏州银行" ) ),
    JSNXB( Arrays.asList( "江苏农信" ) ),
    JSBANK( Arrays.asList( "江苏银行" ) ),
    HUNNXB( Arrays.asList( "湖南农信" ) ),
    HAINNXSB( Arrays.asList( "海南农信" ) ),
    SZSBK( Arrays.asList( "石嘴山银行" ) ),
    HSBANK( Arrays.asList( "徽商银行" ) ),
    DZBANK( Arrays.asList( "德州银行" ) ),
    TJBHNSB( Arrays.asList( "天津滨海农商银行" ) ),
    JLNXB( Arrays.asList( "吉林农信" ) ),
    CRCBANK( Arrays.asList( "重庆农村商业银行" ) ),
    NMGNXS( Arrays.asList( "内蒙古农信" ) ),
    NXBANK( Arrays.asList( "宁夏银行" ) ),
    FCFYCZB( Arrays.asList( "方城凤裕村镇银行" ) ),
    BOCD( Arrays.asList( "承德银行" ) ),
    ZJKCCB( Arrays.asList( "张家口银行" ) ),
    TSB( Arrays.asList( "唐山银行" ) ),
    BOBJSY( Arrays.asList( "北京农商银行" ) ),
    HZCB( Arrays.asList( "杭州银行" ) ),
    SJBANK( Arrays.asList( "盛京银行" ) ),
    SHNSYXBANK( Arrays.asList( "上海农商银行" ) ),
    DAQINGB( Arrays.asList( "龙江银行" ) ),
    WHNSHB( Arrays.asList( "武汉农商行" ) ),
    SXXHB( Arrays.asList( "陕西信合" ) ),
    CABANK( Arrays.asList( "长安银行" ) ),
    HNB( Arrays.asList( "海南银行" ) ),
    ZZBANK( Arrays.asList( "郑州银行" ) ),
    CZBANK( Arrays.asList( "浙商银行" ) ),
    JLBANK( Arrays.asList( "吉林银行" ) ),
    HKB( Arrays.asList( "汉口银行" ) ),
    AHNJB( Arrays.asList( "安徽农金" ) ),
    HFNSB( Arrays.asList( "海丰农商银行" ) ),
    BOQZ( Arrays.asList( "泉州银行" ) ),
    HRBANK( Arrays.asList( "哈尔滨银行" ) ),
    YZB( Arrays.asList( "银座银行" ) ),
    GSXHB( Arrays.asList( "甘肃信合" ) ),
    HBNXB( Arrays.asList( "河北农信" ) ),
    BHB( Arrays.asList( "河北银行" ) ),
    GSBANK( Arrays.asList( "甘肃银行" ) ),
    LZYH( Arrays.asList( "兰州银行" ) ),
    CSNSB( Arrays.asList( "常熟农商银行" ) ),
    HNCZB( Arrays.asList( "湖商村镇银行" ) ),
    TJNSB( Arrays.asList( "天津农商银行" ) ),
    QDCCB( Arrays.asList( "青岛银行" ) ),
    SGNSB( Arrays.asList( "韶关农商银行" ) ),
    DLB( Arrays.asList( "大连银行" ) ),
    BOHAIB( Arrays.asList( "渤海银行" ) ),
    BOCY( Arrays.asList( "朝阳银行" ) ),
    TCCB( Arrays.asList( "天津银行" ) ),
    DZB( Arrays.asList( "达州银行" ) ),
    JZZLB( Arrays.asList( "焦作中旅银行" ) ),
    ZBCB( Arrays.asList( "齐商银行" ) ),
    SRBANK( Arrays.asList( "上饶银行" ) ),
    ZJNX( Arrays.asList( "浙江农信" ) ),
    SXB( Arrays.asList( "山西银行" ) ),
    HLJNXB( Arrays.asList( "黑龙江农信" ) ),
    DYCCB( Arrays.asList( "东营银行" ) ),
    SDNSDBG( Arrays.asList( "顺德农商银行" ) ),
    HDBANK( Arrays.asList( "邯郸银行" ) ),
    HRXJBANK( Arrays.asList( "华融湘江银行" ) ),
    BJSYYZCZYXBANK( Arrays.asList( "北京顺义银座村镇银行" ) ),
    SXSNCXYSLHSBANK( Arrays.asList( "陕西省农村信用社联合社" ) ),
    GDSDNCSYYXBANK( Arrays.asList( "广东顺德农村商业银行" ) ),
    ZJMTSYYXBANK( Arrays.asList( "浙江民泰商业银行" ) ),
    SXRCU( Arrays.asList( "山西农信" ) ),
    XABANK( Arrays.asList( "西安银行" ) ),
    YNNXB( Arrays.asList( "云南农信" ) ),
    FDB( Arrays.asList( "富滇银行" ) ),
    JXYMB( Arrays.asList( "江西裕民银行" ) ),
    CDNSB( Arrays.asList( "成都农商银行" ) ),
    WHBB( Arrays.asList( "威海市商业银行" ) ),
    FJNXB( Arrays.asList( "福建农信" ) ),
    KMNLSBANK( Arrays.asList( "昆明农联社" ) ),
    CDCB( Arrays.asList( "成都银行" ) ),
    ZJCZB( Arrays.asList( "浙信村镇银行" ) ),
    WXNSB( Arrays.asList( "无锡农商行" ) ),
    HKYH( Arrays.asList( "汉口银行" ) ),
    GANZB( Arrays.asList( "赣州银行" ) ),
    PJB( Arrays.asList( "盘锦银行" ) ),
    LANGFB( Arrays.asList( "廊坊银行" ) ),
    GYNSB( Arrays.asList( "贵阳农商银行" ) ),
    LNNXB( Arrays.asList( "辽宁农信" ) ),
    YZZJB( Arrays.asList( "鄞州银行" ) ),
    ZYFDB( Arrays.asList( "中银富登" ) ),
    TZCB( Arrays.asList( "台州银行" ) ),
    BDCB( Arrays.asList( "保定银行" ) ),
    NBTSB( Arrays.asList( "宁波通商银行" ) ),
    ZBB( Arrays.asList( "众邦银行" ) ),
    BOJZ( Arrays.asList( "锦州银行" ) ),
    GLGMCZB( Arrays.asList( "桂林国民村镇银行" ) ),
    DHCZB( Arrays.asList( "东海村镇银行" ) ),
    HBC( Arrays.asList( "湖北银行" ) ),
    SHMYB( Arrays.asList( "三河蒙银" ) ),
    CJB( Arrays.asList( "长江银行" ) ),
    WJRCB( Arrays.asList( "苏州农商行" ) ),
    DDB( Arrays.asList( "丹东银行" ) ),
    TACCB( Arrays.asList( "泰安银行" ) ),
    RBOZ( Arrays.asList( "珠海华润银行" ) ),
    CGNB( Arrays.asList( "四川天府银行" ) ),
    XTB( Arrays.asList( "邢台银行" ) ),
    MSB( Arrays.asList( "蒙商银行" ) ),
    WAHMB( Arrays.asList( "文安惠民银行" ) ),
    LYJDCZB( Arrays.asList( "莱阳胶东村镇银行" ) ),
    ZZB( Arrays.asList( "枣庄银行" ) ),
    RZB( Arrays.asList( "日照银行" ) ),
    CYQQMB( Arrays.asList( "察右前旗蒙银" ) ),
    ZZMB( Arrays.asList( "卓资蒙银" ) ),
    BZSFCZB( Arrays.asList( "霸州舜丰村镇银行" ) ),
    LSBC( Arrays.asList( "临商银行" ) ),
    NMGB( Arrays.asList( "内蒙古银行" ) ),
    KLB( Arrays.asList( "昆仑银行" ) ),
    ZJTLCB( Arrays.asList( "泰隆银行" ) ),
    JNB( Arrays.asList( "江南银行" ) ),
    CQBANK( Arrays.asList( "重庆银行" ) ),
    TCNSB( Arrays.asList( "太仓农商行" ) ),
    CZCB( Arrays.asList( "稠州银行" ) ),
    FXCB( Arrays.asList( "阜新银行" ) ),
    BOQH( Arrays.asList( "青海银行" ) ),
    YCDVB( Arrays.asList( "郾城发展村镇银行" ) ),
    BOCZ( Arrays.asList( "沧州银行" ) ),
    MYQFRB( Arrays.asList( "蒙阴齐丰村镇银行" ) ),
    LSBANK( Arrays.asList( "莱商银行" ) ),
    JNBANK( Arrays.asList( "济宁银行" ) ),
    MTB( Arrays.asList( "民泰银行" ) ),
    XFCZB( Arrays.asList( "兴福村镇银行" ) ),
    XJRCU( Arrays.asList( "新疆农信" ) ),
    NBBANK( Arrays.asList( "宁波银行" ) ),
    CSXBANK( Arrays.asList( "湖南三湘银行" ) ),
    SYRCB( Arrays.asList( "沈阳农商银行" ) ),
    LZCCB( Arrays.asList( "泸州银行" ) ),
    LZB( Arrays.asList( "柳州银行" ) ),
    ZFJG( Arrays.asList( "支付机构" ) ),
    SHPDB( Arrays.asList( "上海浦东发展银行" ) ),
    XNSCZYH( Arrays.asList( "邢农商村镇银行" ) ),
    GRCBANK( Arrays.asList( "潮州农商银行" ) ),
    SCNXSBANK( Arrays.asList( "四川省农村信用社" ) ),
    SDLSBANK( Arrays.asList( "山东莱山齐丰村镇银行" ) ),
    PYBANK( Arrays.asList( "平原圆融村镇银行" ) ),
    GDRCBANK( Arrays.asList( "广东博罗农村商业银行" ) ),
    CZCBANK( Arrays.asList( "广州花都稠州村镇银行" ) ),
    GXLYBANK( Arrays.asList( "广西柳江柳银村镇银行" ) ),
    XAB( Arrays.asList( "新安银行" ) ),
    UNBANK( Arrays.asList( "海口联合农商银行" ) ),
    RFBANK( Arrays.asList( "瑞丰银行" ) ),
    SZFZBANK( Arrays.asList( "深圳发展银行" ) ),
    SCNXBANK( Arrays.asList( "四川农商银行" ) ),
    DLNSBANK( Arrays.asList( "大连农商银行" ) ),
    AXNSBANK( Arrays.asList( "安溪美法信用社" ) ),
    YBCBANK( Arrays.asList( "宜宾农村商业银行" ) ),
    GDRCB( Arrays.asList( "广东农商银行" ) ),
    JNNSB( Arrays.asList( "江南农村商业银行" ) ),
    JSNSB( Arrays.asList( "江苏农村商业银行" ) ),
    JSCJSB( Arrays.asList( "江苏长江商业银行" ) ),
    ZJNSB( Arrays.asList( "浙江农商银行" ) ),
    HNNSB( Arrays.asList( "海南农商" ) ),
    HNTCB( Arrays.asList( "海南屯昌长江村镇银行" ) ),
    SZBAGYB( Arrays.asList( "深圳宝安桂银村镇银行股份有限公司" ) ),
    SZFTYZB( Arrays.asList( "深圳福田银座村镇银行" ) ),
    HBNSB( Arrays.asList( "湖北农商银行" ) ),
    HNNXBANK( Arrays.asList( "湖南省农村信用社联合社" ) ),
    FJNXBANK( Arrays.asList( "福建农村信用社联合社" ) ),
    SHNXB( Arrays.asList( "上海农村商业银行" ) ),
    HNNXLHSB( Arrays.asList( "河南省农村信用社联合社" ) ),
    GDFZB( Arrays.asList( "广东发展银行" ) ),
    SXNXLHSB( Arrays.asList( "山西省农村信用社联合社借记卡行" ) ),
    JSNXBANK( Arrays.asList( "江苏省农村信用社" ) ),
    ZJJNYZBANK( Arrays.asList( "浙江景宁银座村镇银行" ) ),
    SCSNCXYSLHSBAN( Arrays.asList( "四川省农村信用社联合社" ) ),
    WSCZRB( Arrays.asList( "万山长征村镇银行" ) ),
    HXCZYH( Arrays.asList( "公主岭华兴村镇银行" ) ),
    GDNCXYSBANK( Arrays.asList( "广东省农村信用社" ) ),
    GDNYYXBANK( Arrays.asList( "广东南粤银行" ) ),
    NBYZBANK( Arrays.asList( "宁波鄞州农村合作银行" ) ),
    SDNXBANK( Arrays.asList( "山东农村信用联合社" ) ),
    JSNXLHSBANK( Arrays.asList( "江苏省农村信用社联合社" ) ),
    HBNXLHSBANK( Arrays.asList( "河北省农村信用社联合社借记卡行" ) ),
    HNNXLHSBANK( Arrays.asList( "湖南省农村信用社" ) ),
    BOHN( Arrays.asList( "海南省农村信用社" ) ),
    DGNSBANK( Arrays.asList( "东莞农村商业银行" ) ),
    TJBHNSBANK( Arrays.asList( "天津滨海农村商业银行" ) ),
    CDSYBANK( Arrays.asList( "成都商业银行" ) ),
    GDSNCXYSLHSBANK( Arrays.asList( "广东省农村信用社联合社" ) ),
    CSNSBANK( Arrays.asList( "长沙农村商业银行" ) ),
    ZJNXBANK( Arrays.asList( "浙江省农村信用社" ) ),
    XIB( Arrays.asList( "厦门国际银行" ) ),
    SCYHBANK( Arrays.asList( "四川银行" ) ),
    XTQFCZYH( Arrays.asList( "新泰齐丰村镇银行" ) ),
    HNNXCLHSBANK( Arrays.asList( "海南省农村信用社联合社" ) ),
    SHNSBANK( Arrays.asList( "上海市农村商业银行" ) ),
    SZNSBANK( Arrays.asList( "深圳农商银行" ) ),
    SDNLSBANK( Arrays.asList( "山东省农联社" ) ),
    GDNXBANK( Arrays.asList( "广东省农信" ) ),
    CQSXBANK( Arrays.asList( "重庆三峡银行" ) ),
    JXBANK( Arrays.asList( "嘉兴银行" ) ),
    XMBANK( Arrays.asList( "厦门银行" ) ),
    BOP( Arrays.asList( "平顶山银行" ) ),
    WQBANK( Arrays.asList( "武清村镇银行" ) ),
    XHBANK( Arrays.asList( "新华村镇银行" ) ),
    ORDOSBANK( Arrays.asList( "鄂尔多斯银行" ) ),
    ZRCBANK( Arrays.asList( "张家港农村商业银行" ) ),
    CSCB( Arrays.asList( "长沙银行" ) ),
    QSCYBANK( Arrays.asList( "确山郑银村镇银行" ) ),
    BANKOFYK( Arrays.asList( "营口银行" ) ),
    TXGYCBANK( Arrays.asList( "藤县桂银村镇银行" ) ),
    BANKWF( Arrays.asList( "潍坊银行" ) ),
    GRXCC( Arrays.asList( "广西农村信用社联合社" ) ),
    LDHFBANK( Arrays.asList( "乐东惠丰村镇银行" ) ),
    QHDBANK( Arrays.asList( "秦皇岛银行" ) ),
    BANKOFFS( Arrays.asList( "抚顺银行" ) ),
    DRCCB( Arrays.asList( "东辽农商村镇银行" ) ),
    HENGSHUIBANK( Arrays.asList( "衡水银行" ) ),
    HLDB( Arrays.asList( "葫芦岛银行" ) ),
    LNRCC( Arrays.asList( "辽宁省农村信用社" ) ),
    BOL( Arrays.asList( "洛阳银行" ) ),
    QJHMBANK( Arrays.asList( "曲靖惠民村镇银行" ) ),
    WRCB( Arrays.asList( "无锡农村商业银行" ) ),
    SDNCXYSLHSBANK( Arrays.asList( "山东省农村信用社联合社" ) ),
    YZZCCZYX( Arrays.asList( "兖州中成村镇银行" ) ),
    ;

    private final List<String> desc;

    BankCodeZhiYuanType( List<String> desc ) {
        this.desc = desc;
    }

    public static BankCodeZhiYuanType getCodeByDesc( String desc ) {
        for ( BankCodeZhiYuanType enumType : BankCodeZhiYuanType.values() ) {
            if ( enumType.getDesc().contains( desc ) ) {
                return enumType;
            }
            for ( String s : enumType.getDesc() ) {
                if ( s.contains( desc ) ) {
                    return enumType;
                }
            }
        }
        return null;
    }
}
